// Decompiled with JetBrains decompiler
// Type: LcDevPack_TeamDamonA.Tools.MemoryWorker.MonsterComboEditor
// Assembly: LcDevPack_TeamDamonA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: B13AD660-B9C7-4C88-A534-19FC9102A906
// Assembly location: C:\Users\westy\Desktop\my lc\LC_TOOLS\LCT\Debug\LcDevPack_TeamDamonA.exe

using LcDevPack_TeamDamonA.Properties;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace LcDevPack_TeamDamonA.Tools.MemoryWorker
{
  public class MonsterComboEditor : Form
  {
    private IContainer components = (IContainer) null;
    private ListBox listBox1;
    private Button BtnAdd;
    private Button BtnCopy;
    private Button BtnDelete;
    private TextBox TbSearch;
    private Label LblSearch;
    private GroupBox GbIcon;
    private LinkLabel linkLabel1;
    private PictureBox PbIcon;
    private TextBox TbCol;
    private Label LblCol;
    private TextBox TbID;
    private Label LblID;
    private Label LblRow;
    private TextBox TbRow;
    private GroupBox GbComboData;
    private DataGridView dataGridView1;
    private GroupBox GbRegenCombo;
    private Button BtnAddCombo;
    private Button BtnDeleteCombo;
    private Button BtnCopyCombo;
    private GroupBox GbSort;
    private Label LblName;
    private TextBox TbName;
    private TextBox TbComboID;
    private Label LblComboID;
    private TextBox TbNas;
    private Label lblPoint;
    private Label lblNas;
    private CheckBox CbEnable;
    private PictureBox pictureBox1;
    private TextBox textBox1;
    private CheckBox CbPoint;
    private CheckBox CbGold;
    private MenuStrip menuStrip1;
    private PictureBox pictureBox2;
    private ToolStripMenuItem exportToolStripMenuItem;
    private ToolStripMenuItem lODToolStripMenuItem;
    private ToolStripMenuItem stringToolStripMenuItem;
    private ToolStripMenuItem sQLToolStripMenuItem;
    private Label label8;
    private Label LblLang;

    public MonsterComboEditor() => this.InitializeComponent();

    private void CbEnable_CheckedChanged(object sender, EventArgs e)
    {
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (MonsterComboEditor));
      this.listBox1 = new ListBox();
      this.BtnAdd = new Button();
      this.BtnCopy = new Button();
      this.BtnDelete = new Button();
      this.TbSearch = new TextBox();
      this.LblSearch = new Label();
      this.GbIcon = new GroupBox();
      this.linkLabel1 = new LinkLabel();
      this.PbIcon = new PictureBox();
      this.TbCol = new TextBox();
      this.LblCol = new Label();
      this.TbID = new TextBox();
      this.LblID = new Label();
      this.LblRow = new Label();
      this.TbRow = new TextBox();
      this.GbComboData = new GroupBox();
      this.pictureBox2 = new PictureBox();
      this.pictureBox1 = new PictureBox();
      this.textBox1 = new TextBox();
      this.TbNas = new TextBox();
      this.lblPoint = new Label();
      this.lblNas = new Label();
      this.CbEnable = new CheckBox();
      this.TbComboID = new TextBox();
      this.LblComboID = new Label();
      this.LblName = new Label();
      this.TbName = new TextBox();
      this.dataGridView1 = new DataGridView();
      this.GbRegenCombo = new GroupBox();
      this.BtnAddCombo = new Button();
      this.BtnDeleteCombo = new Button();
      this.BtnCopyCombo = new Button();
      this.GbSort = new GroupBox();
      this.CbPoint = new CheckBox();
      this.CbGold = new CheckBox();
      this.menuStrip1 = new MenuStrip();
      this.exportToolStripMenuItem = new ToolStripMenuItem();
      this.lODToolStripMenuItem = new ToolStripMenuItem();
      this.stringToolStripMenuItem = new ToolStripMenuItem();
      this.sQLToolStripMenuItem = new ToolStripMenuItem();
      this.label8 = new Label();
      this.LblLang = new Label();
      this.GbIcon.SuspendLayout();
      ((ISupportInitialize) this.PbIcon).BeginInit();
      this.GbComboData.SuspendLayout();
      ((ISupportInitialize) this.pictureBox2).BeginInit();
      ((ISupportInitialize) this.pictureBox1).BeginInit();
      ((ISupportInitialize) this.dataGridView1).BeginInit();
      this.GbRegenCombo.SuspendLayout();
      this.GbSort.SuspendLayout();
      this.menuStrip1.SuspendLayout();
      this.SuspendLayout();
      this.listBox1.FormattingEnabled = true;
      this.listBox1.Location = new Point(12, 57);
      this.listBox1.Name = "listBox1";
      this.listBox1.Size = new Size(179, 342);
      this.listBox1.TabIndex = 0;
      this.BtnAdd.Location = new Point(11, 405);
      this.BtnAdd.Name = "BtnAdd";
      this.BtnAdd.Size = new Size(47, 23);
      this.BtnAdd.TabIndex = 1;
      this.BtnAdd.Text = "Add";
      this.BtnAdd.UseVisualStyleBackColor = true;
      this.BtnCopy.Location = new Point(65, 405);
      this.BtnCopy.Name = "BtnCopy";
      this.BtnCopy.Size = new Size(57, 23);
      this.BtnCopy.TabIndex = 2;
      this.BtnCopy.Text = "Copy";
      this.BtnCopy.UseVisualStyleBackColor = true;
      this.BtnDelete.Location = new Point(126, 405);
      this.BtnDelete.Name = "BtnDelete";
      this.BtnDelete.Size = new Size(64, 23);
      this.BtnDelete.TabIndex = 3;
      this.BtnDelete.Text = "Delete";
      this.BtnDelete.UseVisualStyleBackColor = true;
      this.TbSearch.Location = new Point(56, 31);
      this.TbSearch.Name = "TbSearch";
      this.TbSearch.Size = new Size(135, 20);
      this.TbSearch.TabIndex = 4;
      this.LblSearch.AutoSize = true;
      this.LblSearch.Location = new Point(9, 34);
      this.LblSearch.Name = "LblSearch";
      this.LblSearch.Size = new Size(44, 13);
      this.LblSearch.TabIndex = 5;
      this.LblSearch.Text = "Search:";
      this.GbIcon.Controls.Add((Control) this.linkLabel1);
      this.GbIcon.Controls.Add((Control) this.PbIcon);
      this.GbIcon.Controls.Add((Control) this.TbCol);
      this.GbIcon.Controls.Add((Control) this.LblCol);
      this.GbIcon.Controls.Add((Control) this.TbID);
      this.GbIcon.Controls.Add((Control) this.LblID);
      this.GbIcon.Controls.Add((Control) this.LblRow);
      this.GbIcon.Controls.Add((Control) this.TbRow);
      this.GbIcon.Location = new Point(192, 249);
      this.GbIcon.Name = "GbIcon";
      this.GbIcon.Size = new Size(211, 100);
      this.GbIcon.TabIndex = 41;
      this.GbIcon.TabStop = false;
      this.GbIcon.Text = "Icon";
      this.linkLabel1.AutoSize = true;
      this.linkLabel1.LinkColor = Color.Blue;
      this.linkLabel1.Location = new Point(124, 75);
      this.linkLabel1.Name = "linkLabel1";
      this.linkLabel1.Size = new Size(61, 13);
      this.linkLabel1.TabIndex = 96;
      this.linkLabel1.TabStop = true;
      this.linkLabel1.Text = "Icon Picker";
      this.PbIcon.BackColor = SystemColors.ButtonHighlight;
      this.PbIcon.BorderStyle = BorderStyle.FixedSingle;
      this.PbIcon.Cursor = Cursors.Default;
      this.PbIcon.Location = new Point(134, 20);
      this.PbIcon.Name = "PbIcon";
      this.PbIcon.Size = new Size(40, 40);
      this.PbIcon.SizeMode = PictureBoxSizeMode.StretchImage;
      this.PbIcon.TabIndex = 95;
      this.PbIcon.TabStop = false;
      this.TbCol.BorderStyle = BorderStyle.FixedSingle;
      this.TbCol.Location = new Point(61, 74);
      this.TbCol.Name = "TbCol";
      this.TbCol.Size = new Size(37, 20);
      this.TbCol.TabIndex = 38;
      this.LblCol.AutoSize = true;
      this.LblCol.Location = new Point(13, 76);
      this.LblCol.Name = "LblCol";
      this.LblCol.Size = new Size(25, 13);
      this.LblCol.TabIndex = 39;
      this.LblCol.Text = "Col:";
      this.TbID.BorderStyle = BorderStyle.FixedSingle;
      this.TbID.Location = new Point(61, 20);
      this.TbID.Name = "TbID";
      this.TbID.Size = new Size(37, 20);
      this.TbID.TabIndex = 34;
      this.LblID.AutoSize = true;
      this.LblID.Location = new Point(13, 22);
      this.LblID.Name = "LblID";
      this.LblID.Size = new Size(21, 13);
      this.LblID.TabIndex = 35;
      this.LblID.Text = "ID:";
      this.LblRow.AutoSize = true;
      this.LblRow.Location = new Point(13, 48);
      this.LblRow.Name = "LblRow";
      this.LblRow.Size = new Size(32, 13);
      this.LblRow.TabIndex = 37;
      this.LblRow.Text = "Row:";
      this.TbRow.BorderStyle = BorderStyle.FixedSingle;
      this.TbRow.Location = new Point(61, 46);
      this.TbRow.Name = "TbRow";
      this.TbRow.Size = new Size(37, 20);
      this.TbRow.TabIndex = 36;
      this.GbComboData.Controls.Add((Control) this.pictureBox2);
      this.GbComboData.Controls.Add((Control) this.pictureBox1);
      this.GbComboData.Controls.Add((Control) this.textBox1);
      this.GbComboData.Controls.Add((Control) this.TbNas);
      this.GbComboData.Controls.Add((Control) this.lblPoint);
      this.GbComboData.Controls.Add((Control) this.lblNas);
      this.GbComboData.Controls.Add((Control) this.CbEnable);
      this.GbComboData.Controls.Add((Control) this.TbComboID);
      this.GbComboData.Controls.Add((Control) this.LblComboID);
      this.GbComboData.Controls.Add((Control) this.LblName);
      this.GbComboData.Controls.Add((Control) this.TbName);
      this.GbComboData.Location = new Point(194, 92);
      this.GbComboData.Name = "GbComboData";
      this.GbComboData.Size = new Size(210, 151);
      this.GbComboData.TabIndex = 42;
      this.GbComboData.TabStop = false;
      this.GbComboData.Text = "Combo Data";
      this.pictureBox2.BackgroundImage = (Image) Resources.gold1;
      this.pictureBox2.BackgroundImageLayout = ImageLayout.Stretch;
      this.pictureBox2.Location = new Point(37, 118);
      this.pictureBox2.Name = "pictureBox2";
      this.pictureBox2.Size = new Size(20, 19);
      this.pictureBox2.TabIndex = 42;
      this.pictureBox2.TabStop = false;
      this.pictureBox1.BackgroundImage = (Image) Resources.gold1;
      this.pictureBox1.BackgroundImageLayout = ImageLayout.Stretch;
      this.pictureBox1.Location = new Point(37, 92);
      this.pictureBox1.Name = "pictureBox1";
      this.pictureBox1.Size = new Size(20, 20);
      this.pictureBox1.TabIndex = 41;
      this.pictureBox1.TabStop = false;
      this.textBox1.Location = new Point(60, 117);
      this.textBox1.Name = "textBox1";
      this.textBox1.Size = new Size(144, 20);
      this.textBox1.TabIndex = 40;
      this.TbNas.Location = new Point(58, 91);
      this.TbNas.Name = "TbNas";
      this.TbNas.Size = new Size(146, 20);
      this.TbNas.TabIndex = 39;
      this.lblPoint.AutoSize = true;
      this.lblPoint.Location = new Point(7, 120);
      this.lblPoint.Name = "lblPoint";
      this.lblPoint.Size = new Size(34, 13);
      this.lblPoint.TabIndex = 38;
      this.lblPoint.Text = "Point:";
      this.lblNas.AutoSize = true;
      this.lblNas.Location = new Point(9, 96);
      this.lblNas.Name = "lblNas";
      this.lblNas.Size = new Size(32, 13);
      this.lblNas.TabIndex = 37;
      this.lblNas.Text = "Gold:";
      this.CbEnable.BackgroundImageLayout = ImageLayout.None;
      this.CbEnable.FlatStyle = FlatStyle.Flat;
      this.CbEnable.Location = new Point(93, 17);
      this.CbEnable.Name = "CbEnable";
      this.CbEnable.Size = new Size(111, 22);
      this.CbEnable.TabIndex = 36;
      this.CbEnable.Text = "Enable";
      this.CbEnable.UseVisualStyleBackColor = true;
      this.TbComboID.Location = new Point(47, 19);
      this.TbComboID.Name = "TbComboID";
      this.TbComboID.Size = new Size(40, 20);
      this.TbComboID.TabIndex = 3;
      this.LblComboID.AutoSize = true;
      this.LblComboID.Location = new Point(22, 22);
      this.LblComboID.Name = "LblComboID";
      this.LblComboID.Size = new Size(21, 13);
      this.LblComboID.TabIndex = 2;
      this.LblComboID.Text = "ID:";
      this.LblName.AutoSize = true;
      this.LblName.Location = new Point(7, 57);
      this.LblName.Name = "LblName";
      this.LblName.Size = new Size(38, 13);
      this.LblName.TabIndex = 1;
      this.LblName.Text = "Name:";
      this.TbName.Location = new Point(47, 53);
      this.TbName.Name = "TbName";
      this.TbName.Size = new Size(157, 20);
      this.TbName.TabIndex = 0;
      this.dataGridView1.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
      this.dataGridView1.Location = new Point(6, 19);
      this.dataGridView1.Name = "dataGridView1";
      this.dataGridView1.Size = new Size(309, 364);
      this.dataGridView1.TabIndex = 43;
      this.GbRegenCombo.Controls.Add((Control) this.dataGridView1);
      this.GbRegenCombo.Location = new Point(410, 4);
      this.GbRegenCombo.Name = "GbRegenCombo";
      this.GbRegenCombo.Size = new Size(321, 389);
      this.GbRegenCombo.TabIndex = 44;
      this.GbRegenCombo.TabStop = false;
      this.GbRegenCombo.Text = "ComboRegen";
      this.BtnAddCombo.Location = new Point(416, 399);
      this.BtnAddCombo.Name = "BtnAddCombo";
      this.BtnAddCombo.Size = new Size(81, 23);
      this.BtnAddCombo.TabIndex = 45;
      this.BtnAddCombo.Text = "Add Regen";
      this.BtnAddCombo.UseVisualStyleBackColor = true;
      this.BtnDeleteCombo.Location = new Point(649, 399);
      this.BtnDeleteCombo.Name = "BtnDeleteCombo";
      this.BtnDeleteCombo.Size = new Size(81, 23);
      this.BtnDeleteCombo.TabIndex = 46;
      this.BtnDeleteCombo.Text = "Delete Regen";
      this.BtnDeleteCombo.UseVisualStyleBackColor = true;
      this.BtnCopyCombo.Location = new Point(562, 399);
      this.BtnCopyCombo.Name = "BtnCopyCombo";
      this.BtnCopyCombo.Size = new Size(81, 23);
      this.BtnCopyCombo.TabIndex = 47;
      this.BtnCopyCombo.Text = "Copy Regen";
      this.BtnCopyCombo.UseVisualStyleBackColor = true;
      this.GbSort.Controls.Add((Control) this.CbPoint);
      this.GbSort.Controls.Add((Control) this.CbGold);
      this.GbSort.Location = new Point(194, 31);
      this.GbSort.Name = "GbSort";
      this.GbSort.Size = new Size(210, 60);
      this.GbSort.TabIndex = 48;
      this.GbSort.TabStop = false;
      this.GbSort.Text = "Sort";
      this.CbPoint.AutoSize = true;
      this.CbPoint.Location = new Point(115, 28);
      this.CbPoint.Name = "CbPoint";
      this.CbPoint.Size = new Size(89, 17);
      this.CbPoint.TabIndex = 1;
      this.CbPoint.Text = "Point Amount";
      this.CbPoint.UseVisualStyleBackColor = true;
      this.CbGold.AutoSize = true;
      this.CbGold.Location = new Point(12, 28);
      this.CbGold.Name = "CbGold";
      this.CbGold.Size = new Size(87, 17);
      this.CbGold.TabIndex = 0;
      this.CbGold.Text = "Gold Amount";
      this.CbGold.UseVisualStyleBackColor = true;
      this.menuStrip1.BackColor = SystemColors.ControlLightLight;
      this.menuStrip1.Items.AddRange(new ToolStripItem[1]
      {
        (ToolStripItem) this.exportToolStripMenuItem
      });
      this.menuStrip1.Location = new Point(0, 0);
      this.menuStrip1.Name = "menuStrip1";
      this.menuStrip1.Size = new Size(732, 24);
      this.menuStrip1.TabIndex = 49;
      this.menuStrip1.Text = "menuStrip1";
      this.exportToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[3]
      {
        (ToolStripItem) this.lODToolStripMenuItem,
        (ToolStripItem) this.stringToolStripMenuItem,
        (ToolStripItem) this.sQLToolStripMenuItem
      });
      this.exportToolStripMenuItem.Name = "exportToolStripMenuItem";
      this.exportToolStripMenuItem.Size = new Size(52, 20);
      this.exportToolStripMenuItem.Text = "Export";
      this.lODToolStripMenuItem.Name = "lODToolStripMenuItem";
      this.lODToolStripMenuItem.Size = new Size(105, 22);
      this.lODToolStripMenuItem.Text = "LOD";
      this.stringToolStripMenuItem.Name = "stringToolStripMenuItem";
      this.stringToolStripMenuItem.Size = new Size(105, 22);
      this.stringToolStripMenuItem.Text = "String";
      this.sQLToolStripMenuItem.Name = "sQLToolStripMenuItem";
      this.sQLToolStripMenuItem.Size = new Size(105, 22);
      this.sQLToolStripMenuItem.Text = "SQL";
      this.label8.AutoSize = true;
      this.label8.BackColor = SystemColors.ControlLightLight;
      this.label8.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label8.Location = new Point(139, 4);
      this.label8.Name = "label8";
      this.label8.Size = new Size(154, 16);
      this.label8.TabIndex = 50;
      this.label8.Text = "Current Language is :";
      this.LblLang.AutoSize = true;
      this.LblLang.BackColor = SystemColors.ControlLightLight;
      this.LblLang.ForeColor = Color.Blue;
      this.LblLang.Location = new Point(294, 7);
      this.LblLang.Name = "LblLang";
      this.LblLang.Size = new Size(41, 13);
      this.LblLang.TabIndex = 51;
      this.LblLang.Text = "English";
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(732, 433);
      this.Controls.Add((Control) this.LblLang);
      this.Controls.Add((Control) this.label8);
      this.Controls.Add((Control) this.GbSort);
      this.Controls.Add((Control) this.BtnCopyCombo);
      this.Controls.Add((Control) this.BtnDeleteCombo);
      this.Controls.Add((Control) this.BtnAddCombo);
      this.Controls.Add((Control) this.GbRegenCombo);
      this.Controls.Add((Control) this.GbComboData);
      this.Controls.Add((Control) this.GbIcon);
      this.Controls.Add((Control) this.LblSearch);
      this.Controls.Add((Control) this.TbSearch);
      this.Controls.Add((Control) this.BtnDelete);
      this.Controls.Add((Control) this.BtnCopy);
      this.Controls.Add((Control) this.BtnAdd);
      this.Controls.Add((Control) this.listBox1);
      this.Controls.Add((Control) this.menuStrip1);
      this.Icon = (Icon) componentResourceManager.GetObject("$this.Icon");
      this.MainMenuStrip = this.menuStrip1;
      this.Name = nameof (MonsterComboEditor);
      this.Text = nameof (MonsterComboEditor);
      this.GbIcon.ResumeLayout(false);
      this.GbIcon.PerformLayout();
      ((ISupportInitialize) this.PbIcon).EndInit();
      this.GbComboData.ResumeLayout(false);
      this.GbComboData.PerformLayout();
      ((ISupportInitialize) this.pictureBox2).EndInit();
      ((ISupportInitialize) this.pictureBox1).EndInit();
      ((ISupportInitialize) this.dataGridView1).EndInit();
      this.GbRegenCombo.ResumeLayout(false);
      this.GbSort.ResumeLayout(false);
      this.GbSort.PerformLayout();
      this.menuStrip1.ResumeLayout(false);
      this.menuStrip1.PerformLayout();
      this.ResumeLayout(false);
      this.PerformLayout();
    }
  }
}
