/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_Bullet_INCLUDED
#define _EntitiesMP_Bullet_INCLUDED 1
#include <EntitiesMP/BasicEffects.h>
#include <EntitiesMP/EnemyBase.h>
#include <Engine/Classes/MovableEntity.h>
#define EVENTCODE_EBulletInit 0x01f60000
class DECL_DLL EBulletInit : public CEntityEvent {
public:
	EBulletInit();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	CEntityID eidOwner;
	FLOAT fDamage;
};
DECL_DLL inline void ClearToDefault(EBulletInit &e) { e = EBulletInit(); } ;
extern "C" DECL_DLL CDLLEntityClass CBullet_DLLClass;
class DECL_DLL  CBullet : public CEntity {
public:
	 virtual void SetDefaultProperties(void);
	CEntityPointer m_penOwner;
	FLOAT m_fDamage;
	FLOAT3D m_vTarget;
	FLOAT3D m_vTargetCopy;
	FLOAT3D m_vHitPoint;
	INDEX m_iBullet;
	enum DamageType m_EdtDamage;
	FLOAT m_fBulletSize;
   
#line 60 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Bullet.es"
void SetDamage(FLOAT fDamage);
   
#line 65 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Bullet.es"
void CalcTarget(FLOAT fRange);
   
#line 73 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Bullet.es"
void CalcTarget(CEntity * pen,FLOAT fRange);
   
#line 98 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Bullet.es"
void CalcJitterTarget(FLOAT fR);
   
#line 123 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Bullet.es"
void CalcJitterTargetFixed(FLOAT fX,FLOAT fY,FLOAT fJitter);
   
#line 135 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Bullet.es"
void LaunchBullet(BOOL bSound,BOOL bTrail,BOOL bHitFX);
   
#line 268 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Bullet.es"
void DestroyBullet(void);
   
#line 278 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Bullet.es"
void SpawnTrail(void);
#define  STATE_CBullet_Main 1
	BOOL 
#line 322 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Bullet.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_Bullet_INCLUDED
