/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_Character_INCLUDED
#define _EntitiesMP_Character_INCLUDED 1
#include <EntitiesMP/Missile.h>
#include <EntitiesMP/EnemyBase.h>
#include <EntitiesMP/Global.h>
#include <EntitiesMP/BasicEffects.h>
#include <EntitiesMP/CharacterBase.h>
#include <EntitiesMP/BasicEffects.h>
#include <EntitiesMP/EnemyBase.h>
#include <EntitiesMP/Player.h>
#include <EntitiesMP/PetBase.h>
#include <EntitiesMP/WildPet.h>
#define EVENTCODE_EChaAttackDamage 0x05e70000
class DECL_DLL EChaAttackDamage : public CEntityEvent {
public:
	EChaAttackDamage();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
};
DECL_DLL inline void ClearToDefault(EChaAttackDamage &e) { e = EChaAttackDamage(); } ;
#define EVENTCODE_EChaSkillDamage 0x05e70001
class DECL_DLL EChaSkillDamage : public CEntityEvent {
public:
	EChaSkillDamage();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
};
DECL_DLL inline void ClearToDefault(EChaSkillDamage &e) { e = EChaSkillDamage(); } ;
extern "C" DECL_DLL CDLLEntityClass CCharacter_DLLClass;
class CCharacter : public CCharacterBase {
public:
	DECL_DLL virtual void SetDefaultProperties(void);
	FLOAT m_fBodyAnimTime;
	FLOAT m_fStretch;
	INDEX m_ChaList;
	FLOAT m_tmDireStrikeStart;
	CSoundObject m_soMessage;
	FLOAT m_fScale;
	BOOL m_bRide;
	INDEX m_iRideType;
	BOOL m_bWildRide;
	BOOL m_bPlayAction;
	FLOAT m_fActionAnimTime;
	INDEX m_nSitDown;
	INDEX idBodyAnim;
	INDEX m_nWearArmorUp;
	INDEX m_nWearWeapon;
	INDEX m_nWearArmorDown;
	INDEX m_nWearShield;
	INDEX m_nWearGlove;
	INDEX m_nWearBoots;
	INDEX m_nWearHead;
	INDEX m_nWearWing;
	BOOL m_bExtension;
	INDEX m_nHairStyle;
	INDEX m_nFaceStyle;
	INDEX m_nPkMode;
	INDEX m_nPkTitle;
	BOOL m_bPlayProduce;
	INDEX m_nPlayProduceNum;
	FLOAT m_tmDamageTime;
	BOOL m_bChangingTwice;
	INDEX m_nChangeMonsterIdTwice;
	INDEX m_nPkState;
	INDEX m_nLegit;
	BOOL m_bDie;
	BOOL m_bDisappearWeapon;
	BOOL m_bChanging;
	INDEX m_nChangeMonsterId;
	BOOL m_bTransforming;
	INDEX m_ChaState;
	INDEX m_iPolymophStep;
	BOOL m_bTransformMinimize;
	INDEX m_iTransformType;
INDEX m_nEffectStep;
CEffectGroup * m_pSkillReadyEffect;
CStaticArray < TagInfo > m_saLastEffectInfo;
INDEX m_iSkillEffectStep;
CStaticArray < FLOAT > m_afHardCodeValue;
CCharacterAnimation m_AnimationIndices;
CModelInstance * m_pRiderModelInstance;
CModelInstance * m_pRidePetModelInstance;
CModelInstance * m_pRideCharModelInstance;
QVect mi_qvOffset;
INDEX mi_iParentBoneID;
INDEX m_iPlaying_Ani_Attack;
BOOL m_bReadyAction;
BOOL m_bStillAction;
BOOL m_bFireAction;
BOOL m_bAttachPlayerEffect;
BOOL m_bAttachEnemyEffect;
CStaticArray < INDEX > m_iCostumeWear;
INDEX m_nWildPetType;
   
#line 211 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   
#line 249 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void AdjustMipFactor(FLOAT & fMipFactor);
  
#line 255 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
virtual FLOAT GetLockRotationSpeed(void);
   
#line 261 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
CModelInstance * GetCurrentPlayerModelInstance();
  
#line 285 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
virtual void RidingPet(CEntity * pCharacter,INDEX iPetType);
  
#line 345 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
virtual void LeavingPet(CEntity * pCharacter);
   
#line 377 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void InitBeastAnimation(void);
   
#line 396 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void SetBeastAnimation(CEntity * pWildPet);
  
#line 418 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
virtual void RidingWildPet(CEntity * pCharacter,CEntity * pWildPet,CTString strFileName);
  
#line 480 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
virtual void LeavingWildPet(CEntity * pCharacter);
   
#line 513 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void OnInitialize(const CEntityEvent & eeInput);
   
#line 518 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void OnEnd(void);
   
#line 524 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void CCharacter_OnInitClass(void);
   
#line 544 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void SetAnimation(INDEX iType);
  
#line 553 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
   
#line 561 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void * GetEntityInfo(void);
   
#line 566 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void Precache(void);
  
#line 575 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
virtual BOOL IsCharacter()const;
   
#line 578 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void InflictDirectDamage(CEntity * penToDamage,CEntity * penInflictor,enum DamageType dmtType,
#line 579 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 672 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 673 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 720 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
INDEX AnimForDamage(FLOAT fDamage);
   
#line 813 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
INDEX AnimForDeath(void);
   
#line 911 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
FLOAT WaitForDust(FLOAT3D & vStretch);
   
#line 923 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void DeathNotify(void);
   
#line 930 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void IdleAnim(void);
   
#line 1049 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void StandingAnim(void);
   
#line 1102 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void RunningAnim(void);
   
#line 1298 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void WalkingAnim(void);
   
#line 1348 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void RotatingAnim(void);
   
#line 1354 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void EnemyPostInit(void);
   
#line 1360 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void InitCurrentWearing();
   
#line 1380 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void WearingDefaultArmor(int type);
   
#line 1469 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void DisplayCurrentWear();
  
#line 1483 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
virtual void DeleteDefaultArmor(int type);
   
#line 1505 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void DeleteCurrentArmor(int index);
   
#line 1534 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void DeleteWearingWeapon(BOOL bException,BOOL bSkillReady);
   
#line 1618 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void AppearWearingWeapon(BOOL bSkillEnd);
   
#line 1680 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void TakeOffWearing(int wear_pos,ObjectBase * pObject);
   
#line 1742 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void TakeOffWearing(int wear_pos);
   
#line 1790 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void WearingArmor(int index,int pos);
   
#line 1988 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
BOOL IsEXRogue(int job);
   
#line 1993 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
BOOL IsEXMage(int job);
   
#line 2003 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
INDEX IsThereWearing(int pos);
   
#line 2063 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
INDEX IsThereCostumeWearing(int pos);
   
#line 2074 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void SetWearing(int pos,int itemId);
   
#line 2109 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void SetCostumeWearing(int pos,int itemId);
   
#line 2120 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void GetTargetDirection(FLOAT3D & vTargetPos,FLOAT3D & vDirection);
   
#line 2157 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void SetAttackSpeed(SBYTE attackspeed);
   
#line 2176 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void TransformSorcerer(int iType,BOOL bAppear);
   
#line 2215 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void ReturnSorcerer(BOOL bDie);
   
#line 2321 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void MonsterChange(int iType,BOOL bAppear);
   
#line 2371 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void ReturnChange(BOOL bDie);
   
#line 2461 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void MinMaximize();
   
#line 2608 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void Transforming();
   
#line 2624 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void SetPolymophMobIndex(int mobId);
   
#line 2635 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void PolymophEnd();
   
#line 2667 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
BOOL PreSkillAnimationEx(BOOL bOnlyTest);
   
#line 2893 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
BOOL FireSkillAnimation(BOOL bOnlyTest);
   
#line 3296 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
BOOL HardCodingSkill(BOOL bOnlyTest);
   
#line 3637 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void SetNickNameDamageEffect(INDEX iNickIndex,NickNameEffectType iType);
   
#line 3666 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void SetCustomTitleEffect(CTString effectName);
   
#line 3675 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
void SkillAnimationStop();
#define  STATE_CCharacter_Main 1
	BOOL 
#line 3696 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
Main(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_Fire 0x05e70002
	BOOL 
#line 3801 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
Fire(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_Hit 0x05e70003
	BOOL 
#line 3806 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
Hit(const CEntityEvent &__eeInput);
	BOOL H0x05e70004_Hit_01(const CEntityEvent &__eeInput);
	BOOL H0x05e70005_Hit_02(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_AttackTarget 0x05e70006
	BOOL 
#line 3812 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
AttackTarget(const CEntityEvent &__eeInput);
	BOOL H0x05e70007_AttackTarget_01(const CEntityEvent &__eeInput);
	BOOL H0x05e70008_AttackTarget_02(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_AttackAnimation 0x05e70009
	BOOL 
#line 3821 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
AttackAnimation(const CEntityEvent &__eeInput);
	BOOL H0x05e7000a_AttackAnimation_01(const CEntityEvent &__eeInput);
	BOOL H0x05e7000b_AttackAnimation_02(const CEntityEvent &__eeInput);
	BOOL H0x05e7000c_AttackAnimation_03(const CEntityEvent &__eeInput);
	BOOL H0x05e7000d_AttackAnimation_04(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_SkillingTarget 0x05e7000e
	BOOL 
#line 4494 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
SkillingTarget(const CEntityEvent &__eeInput);
	BOOL H0x05e7000f_SkillingTarget_01(const CEntityEvent &__eeInput);
	BOOL H0x05e70010_SkillingTarget_02(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_SpellSkill 0x05e70011
	BOOL 
#line 4506 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
SpellSkill(const CEntityEvent &__eeInput);
	BOOL H0x05e70012_SpellSkill_01(const CEntityEvent &__eeInput);
	BOOL H0x05e70013_SpellSkill_02(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_ProduceAnimation 0x05e70014
	BOOL 
#line 4515 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
ProduceAnimation(const CEntityEvent &__eeInput);
	BOOL H0x05e70015_ProduceAnimation_01(const CEntityEvent &__eeInput);
	BOOL H0x05e70016_ProduceAnimation_02(const CEntityEvent &__eeInput);
	BOOL H0x05e70017_ProduceAnimation_03(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_ConsensusAnimation 0x05e70018
	BOOL 
#line 4558 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
ConsensusAnimation(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_ActionAnimation 0x05e70019
	BOOL 
#line 4569 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
ActionAnimation(const CEntityEvent &__eeInput);
	BOOL H0x05e7001a_ActionAnimation_01(const CEntityEvent &__eeInput);
	BOOL H0x05e7001b_ActionAnimation_02(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_PreSkillAnimation 0x05e7001c
	BOOL 
#line 4894 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
PreSkillAnimation(const CEntityEvent &__eeInput);
	BOOL H0x05e7001d_PreSkillAnimation_01(const CEntityEvent &__eeInput);
	BOOL H0x05e7001e_PreSkillAnimation_02(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_SkillAnimation 0x05e7001f
	BOOL 
#line 4978 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
SkillAnimation(const CEntityEvent &__eeInput);
	BOOL H0x05e70020_SkillAnimation_01(const CEntityEvent &__eeInput);
	BOOL H0x05e70021_SkillAnimation_02(const CEntityEvent &__eeInput);
	BOOL H0x05e70022_SkillAnimation_03(const CEntityEvent &__eeInput);
	BOOL H0x05e70023_SkillAnimation_04(const CEntityEvent &__eeInput);
	BOOL H0x05e70024_SkillAnimation_05(const CEntityEvent &__eeInput);
	BOOL H0x05e70025_SkillAnimation_06(const CEntityEvent &__eeInput);
	BOOL H0x05e70026_SkillAnimation_07(const CEntityEvent &__eeInput);
	BOOL H0x05e70027_SkillAnimation_08(const CEntityEvent &__eeInput);
	BOOL H0x05e70028_SkillAnimation_09(const CEntityEvent &__eeInput);
	BOOL H0x05e70029_SkillAnimation_10(const CEntityEvent &__eeInput);
	BOOL H0x05e7002a_SkillAnimation_11(const CEntityEvent &__eeInput);
	BOOL H0x05e7002b_SkillAnimation_12(const CEntityEvent &__eeInput);
	BOOL H0x05e7002c_SkillAnimation_13(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_NormalAttack 0x05e7002d
	BOOL 
#line 5545 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
NormalAttack(const CEntityEvent &__eeInput);
	BOOL H0x05e7002e_NormalAttack_01(const CEntityEvent &__eeInput);
	BOOL H0x05e7002f_NormalAttack_02(const CEntityEvent &__eeInput);
	BOOL H0x05e70030_NormalAttack_03(const CEntityEvent &__eeInput);
	BOOL H0x05e70031_NormalAttack_04(const CEntityEvent &__eeInput);
	BOOL H0x05e70032_NormalAttack_05(const CEntityEvent &__eeInput);
	BOOL H0x05e70033_NormalAttack_06(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_Polymoph 0x05e70034
	BOOL 
#line 5585 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
Polymoph(const CEntityEvent &__eeInput);
	BOOL H0x05e70035_Polymoph_01(const CEntityEvent &__eeInput);
	BOOL H0x05e70036_Polymoph_02(const CEntityEvent &__eeInput);
	BOOL H0x05e70037_Polymoph_03(const CEntityEvent &__eeInput);
	BOOL H0x05e70038_Polymoph_04(const CEntityEvent &__eeInput);
#define  STATE_CCharacter_Evocate 0x05e70039
	BOOL 
#line 5622 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Character.es"
Evocate(const CEntityEvent &__eeInput);
	BOOL H0x05e7003a_Evocate_01(const CEntityEvent &__eeInput);
	BOOL H0x05e7003b_Evocate_02(const CEntityEvent &__eeInput);
	BOOL H0x05e7003c_Evocate_03(const CEntityEvent &__eeInput);
	BOOL H0x05e7003d_Evocate_04(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_Character_INCLUDED
