/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_EnvironmentMarker_INCLUDED
#define _EntitiesMP_EnvironmentMarker_INCLUDED 1
#include <EntitiesMP/Marker.h>
extern "C" DECL_DLL CDLLEntityClass CEnvironmentMarker_DLLClass;
class CEnvironmentMarker : public CMarker {
public:
	DECL_DLL virtual void SetDefaultProperties(void);
	FLOAT m_fWaitTime;
	FLOAT m_fRandomTime;
	RANGE m_fMarkerRange;
	BOOL m_bFixedAnimLength;
	BOOL m_bChangeDefaultAnim;
	FLOAT m_fMoveSpeed;
	FLOAT m_fRotateSpeed;
	CTFileName m_fnMdl;
	ANIMATION m_iAnim;
	CModelObject m_moAnimData;
   
#line 32 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/EnvironmentMarker.es"
BOOL MovesByTargetedRoute(CTString & strTargetProperty)const;
   
#line 37 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/EnvironmentMarker.es"
BOOL DropsMarker(CTFileName & fnmMarkerClass,CTString & strTargetProperty)const;
   
#line 43 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/EnvironmentMarker.es"
CAnimData * GetAnimData(SLONG slPropertyOffset);
   
#line 54 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/EnvironmentMarker.es"
void SetModelObject(void);
#define  STATE_CEnvironmentMarker_Main 1
	BOOL 
#line 77 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/EnvironmentMarker.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_EnvironmentMarker_INCLUDED
