/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_MessageHolder_INCLUDED
#define _EntitiesMP_MessageHolder_INCLUDED 1
extern "C" DECL_DLL CDLLEntityClass CMessageHolder_DLLClass;
class CMessageHolder : public CRationalEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
	DECL_DLL virtual void SetDefaultProperties(void);
	CTString m_strName;
	INDEX m_iStringIndex;
	CTString m_strRealString;
#define  STATE_CMessageHolder_Main 1
	BOOL 
#line 46 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/MessageHolder.es"
Main(const CEntityEvent &__eeInput);
	BOOL H0x00e20000_Main_01(const CEntityEvent &__eeInput);
	BOOL H0x00e20001_Main_02(const CEntityEvent &__eeInput);
#define  STATE_CMessageHolder_MainMessageType 0x00e20002
	BOOL 
#line 113 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/MessageHolder.es"
MainMessageType(const CEntityEvent &__eeInput);
	BOOL H0x00e20003_MainMessageType_01(const CEntityEvent &__eeInput);
	BOOL H0x00e20004_MainMessageType_02(const CEntityEvent &__eeInput);
	BOOL H0x00e20005_MainMessageType_03(const CEntityEvent &__eeInput);
	BOOL H0x00e20006_MainMessageType_04(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_MessageHolder_INCLUDED
