/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_Player_INCLUDED
#define _EntitiesMP_Player_INCLUDED 1
#include <EntitiesMP/AnimationChanger.h>
extern DECL_DLL CEntityPropertyEnumType PlayerViewType_enum;
enum PlayerViewType {
	PVT_PLAYEREYES = 0,
	PVT_PLAYERAUTOVIEW = 1,
	PVT_SCENECAMERA = 2,
	PVT_3RDPERSONVIEW = 3,
};
DECL_DLL inline void ClearToDefault(PlayerViewType &e) { e = (PlayerViewType)0; } ;
extern DECL_DLL CEntityPropertyEnumType PlayerState_enum;
enum PlayerState {
	PST_STAND = 0,
	PST_SWIM = 2,
	PST_DIVE = 3,
	PST_FALL = 4,
	PST_BEFORECLIMB = 5,
	PST_CLIMBWALL = 6,
	PST_AFTERCLIMB = 7,
};
DECL_DLL inline void ClearToDefault(PlayerState &e) { e = (PlayerState)0; } ;
extern DECL_DLL CEntityPropertyEnumType PlayerTeleportCause_enum;
enum PlayerTeleportCause {
	TPC_FIRSTINIT = 0,
	TPC_WORLDCHANGED = 1,
	TPC_OTHER = 2,
};
DECL_DLL inline void ClearToDefault(PlayerTeleportCause &e) { e = (PlayerTeleportCause)0; } ;
extern DECL_DLL CEntityPropertyEnumType NickNameEffectType_enum;
enum NickNameEffectType {
	NICKNAME_ATTACK_EFFECT = 0,
	NICKNAME_DAMAGE_EFFECT = 1,
};
DECL_DLL inline void ClearToDefault(NickNameEffectType &e) { e = (NickNameEffectType)0; } ;
#define EVENTCODE_ECameraStart 0x01910000
class DECL_DLL ECameraStart : public CEntityEvent {
public:
	ECameraStart();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	CEntityPointer penCamera;
};
DECL_DLL inline void ClearToDefault(ECameraStart &e) { e = ECameraStart(); } ;
#define EVENTCODE_ECameraStop 0x01910001
class DECL_DLL ECameraStop : public CEntityEvent {
public:
	ECameraStop();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	CEntityPointer penCamera;
};
DECL_DLL inline void ClearToDefault(ECameraStop &e) { e = ECameraStop(); } ;
#define EVENTCODE_ESlaveKilledEnemy 0x01910002
class DECL_DLL ESlaveKilledEnemy : public CEntityEvent {
public:
	ESlaveKilledEnemy();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
};
DECL_DLL inline void ClearToDefault(ESlaveKilledEnemy &e) { e = ESlaveKilledEnemy(); } ;
#define EVENTCODE_EAutoLogin 0x01910003
class DECL_DLL EAutoLogin : public CEntityEvent {
public:
	EAutoLogin();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
};
DECL_DLL inline void ClearToDefault(EAutoLogin &e) { e = EAutoLogin(); } ;
#define EVENTCODE_EStopLerp 0x01910004
class DECL_DLL EStopLerp : public CEntityEvent {
public:
	EStopLerp();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	BOOL bActive;
};
DECL_DLL inline void ClearToDefault(EStopLerp &e) { e = EStopLerp(); } ;
#define EVENTCODE_ERebirth 0x01910005
class DECL_DLL ERebirth : public CEntityEvent {
public:
	ERebirth();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
};
DECL_DLL inline void ClearToDefault(ERebirth &e) { e = ERebirth(); } ;
#define EVENTCODE_EPlayerRebirth 0x01910006
class DECL_DLL EPlayerRebirth : public CEntityEvent {
public:
	EPlayerRebirth();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	INDEX iRespawnInPlace;
};
DECL_DLL inline void ClearToDefault(EPlayerRebirth &e) { e = EPlayerRebirth(); } ;
#define EVENTCODE_EDisconnected 0x01910007
class DECL_DLL EDisconnected : public CEntityEvent {
public:
	EDisconnected();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
};
DECL_DLL inline void ClearToDefault(EDisconnected &e) { e = EDisconnected(); } ;
#define EVENTCODE_EAutoAction 0x01910008
class DECL_DLL EAutoAction : public CEntityEvent {
public:
	EAutoAction();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	CEntityID eidFirstMarker;
};
DECL_DLL inline void ClearToDefault(EAutoAction &e) { e = EAutoAction(); } ;
#define EVENTCODE_EPlayerKilledEnemy 0x01910009
class DECL_DLL EPlayerKilledEnemy : public CEntityEvent {
public:
	EPlayerKilledEnemy();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	CEntityID eidEnemy;
	INDEX iScore;
	enum CauseOfDeath eCauseOfDeath;
	enum KillType eKillType;
};
DECL_DLL inline void ClearToDefault(EPlayerKilledEnemy &e) { e = EPlayerKilledEnemy(); } ;
#define EVENTCODE_EPlayerDeath 0x0191000a
class DECL_DLL EPlayerDeath : public CEntityEvent {
public:
	EPlayerDeath();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	CEntityID eidInflictor;
	FLOAT3D vDirection;
	FLOAT3D vHitPoint;
	FLOAT fAmount;
	enum DamageType dmtType;
};
DECL_DLL inline void ClearToDefault(EPlayerDeath &e) { e = EPlayerDeath(); } ;
#define EVENTCODE_EShowConsole 0x0191000b
class DECL_DLL EShowConsole : public CEntityEvent {
public:
	EShowConsole();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
};
DECL_DLL inline void ClearToDefault(EShowConsole &e) { e = EShowConsole(); } ;
#define EVENTCODE_EPlayerStats 0x0191000c
class DECL_DLL EPlayerStats : public CEntityEvent {
public:
	EPlayerStats();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	INDEX iIndex;
	INDEX iFrags;
	INDEX iKills;
	INDEX iDeaths;
};
DECL_DLL inline void ClearToDefault(EPlayerStats &e) { e = EPlayerStats(); } ;
#define EVENTCODE_EAddBulletSpray 0x0191000d
class DECL_DLL EAddBulletSpray : public CEntityEvent {
public:
	EAddBulletSpray();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	FLOAT3D vPos;
	EffectParticlesType eptType;
	FLOAT3D vReflected;
};
DECL_DLL inline void ClearToDefault(EAddBulletSpray &e) { e = EAddBulletSpray(); } ;
#define EVENTCODE_EAddGoreSpray 0x0191000e
class DECL_DLL EAddGoreSpray : public CEntityEvent {
public:
	EAddGoreSpray();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	INDEX iEntityHit;
	FLOAT3D vPos;
	FLOAT3D vHit;
	SprayParticlesType sptType;
	COLOR colParticles;
};
DECL_DLL inline void ClearToDefault(EAddGoreSpray &e) { e = EAddGoreSpray(); } ;
extern "C" DECL_DLL CDLLEntityClass CPlayer_DLLClass;
class DECL_DLL  CPlayer : public CPlayerEntity {
public:
	 virtual void SetDefaultProperties(void);
	CTString m_strName;
	COLOR m_ulLastButtons;
	FLOAT m_fArmor;
	CTString m_strGroup;
	INDEX m_ulKeys;
	FLOAT m_fMaxHealth;
	INDEX m_ulFlags;
	CEntityPointer m_penWeapons;
	CEntityPointer m_penAnimator;
	CEntityPointer m_penView;
	CEntityPointer m_pen3rdPersonView;
	INDEX m_iViewState;
	INDEX m_iLastViewState;
	CAnimObject m_aoLightAnimation;
	FLOAT m_fDamageAmmount;
	FLOAT m_tmWoundedTime;
	INDEX m_iGender;
	enum PlayerState m_pstState;
	FLOAT m_fFallTime;
	FLOAT m_fSwimTime;
	FLOAT m_tmOutOfWater;
	FLOAT m_tmMoveSound;
	BOOL m_bMoveSoundLeft;
	FLOAT m_tmNextAmbientOnce;
	FLOAT m_tmMouthSoundLast;
	CEntityPointer m_penCamera;
	CTString m_strCenterMessage;
	FLOAT m_tmCenterMessageEnd;
	BOOL m_bPendingMessage;
	FLOAT m_tmMessagePlay;
	FLOAT m_tmAnalyseEnd;
	BOOL m_bComputerInvoked;
	FLOAT m_tmAnimateInbox;
	CEntityPointer m_penMainMusicHolder;
	FLOAT m_tmLastDamage;
	FLOAT m_fMaxDamageAmmount;
	FLOAT3D m_vDamage;
	FLOAT m_tmSpraySpawned;
	FLOAT m_fSprayDamage;
	CEntityPointer m_penSpray;
	CSoundObject m_soWeapon0;
	CSoundObject m_soWeapon1;
	CSoundObject m_soWeapon2;
	CSoundObject m_soWeapon3;
	CSoundObject m_soWeaponAmbient;
	CSoundObject m_soPowerUpBeep;
	CSoundObject m_soMouth;
	CSoundObject m_soFootL;
	CSoundObject m_soFootR;
	CSoundObject m_soBody;
	CSoundObject m_soLocalAmbientLoop;
	CSoundObject m_soLocalAmbientOnce;
	CSoundObject m_soMessage;
	INDEX m_iHighScore;
	INDEX m_iBeatenHighScore;
	FLOAT m_tmLatency;
	FLOAT m_tmLatencyLastAvg;
	FLOAT m_tmLatencyAvgSum;
	INDEX m_ctLatencyAvg;
	BOOL m_bEndOfLevel;
	BOOL m_bEndOfGame;
	INDEX m_iMayRespawn;
	FLOAT m_tmSpawned;
	FLOAT3D m_vDied;
	FLOAT3D m_aDied;
	FLOAT m_tmEstTime;
	INDEX m_iTimeScore;
	INDEX m_iStartTime;
	INDEX m_iEndTime;
	FLOAT m_tmLevelStarted;
	CTString m_strLevelStats;
	CEntityPointer m_penActionMarker;
	FLOAT m_fAutoSpeed;
	INDEX m_iAutoOrgWeapon;
	FLOAT3D m_vAutoSpeed;
	FLOAT m_tmSpiritStart;
	FLOAT m_tmFadeStart;
	FLOAT m_tmLastPicked;
	CTString m_strPickedName;
	FLOAT m_fPickedAmmount;
	FLOAT m_fPickedMana;
	FLOAT3D m_vLastStain;
	INDEX m_iLastRotationH;
	INDEX m_iLastRotationP;
	INDEX m_iLastRotationB;
	INDEX m_iLastViewRotationH;
	INDEX m_iLastViewRotationP;
	INDEX m_iLastViewRotationB;
	FLOAT3D m_vLastTranslation;
	ANGLE3D m_aLocalRotation;
	ANGLE3D m_aLocalViewRotation;
	FLOAT3D m_vLocalTranslation;
	FLOAT m_tmInvisibility;
	FLOAT m_tmInvulnerability;
	FLOAT m_tmSeriousDamage;
	FLOAT m_tmSeriousSpeed;
	FLOAT m_tmInvisibilityMax;
	FLOAT m_tmInvulnerabilityMax;
	FLOAT m_tmSeriousDamageMax;
	FLOAT m_tmSeriousSpeedMax;
	FLOAT m_tmChainShakeEnd;
	FLOAT m_fChainShakeStrength;
	FLOAT m_fChainShakeFreqMod;
	FLOAT m_fChainsawShakeDX;
	FLOAT m_fChainsawShakeDY;
	INDEX m_sbAttackspeed;
	INDEX m_sbMagicspeed;
	FLOAT m_fAttackrange;
	FLOAT m_fRunspeed;
	FLOAT m_fWalkspeed;
	INDEX m_iWeaponsID;
	INDEX m_iAnimatorID;
	BOOL m_bInitializeOverNet;
	BOOL m_bDontLerpView;
	BOOL m_bMdl;
	FLOAT3D m_LocCurrent;
	FLOAT3D m_LocDesired;
	FLOAT m_tmSpawnedForInv;
	BOOL m_bIsMove;
	BOOL m_bStartAttack;
	FLOAT3D m_vDesiredPosition;
	ANGLE m_aRotateSpeed;
	FLOAT m_fMoveSpeed;
	FLOAT m_fMoveFrequency;
	BOOL m_bMoving;
	FLOAT m_fBurnPower;
	FLOAT m_fBurnRatio;
	FLOAT m_fBurnTime;
	FLOAT m_fBurnFadeInTime;
	FLOAT m_fBurnFadeOutTime;
	CEntityPointer m_penAttackingEnemy;
	BOOL m_bLockMove;
	BOOL m_bReserveMove;
	BOOL m_bForward;
	BOOL m_bKeyMove;
	INDEX m_nDesiredSkillNum;
	BOOL m_bReserveSkill;
	BOOL m_bSkilling;
	INDEX m_nCurrentSkillNum;
	INDEX m_nReservedSkillNum;
	FLOAT m_fSkillDistance;
	INDEX m_idCurrentSkillAnim;
	FLOAT m_tmSkillStartTime;
	FLOAT m_tmSkillAnimTime;
	FLOAT m_fSkillAnimTime;
	BOOL m_bWaitForSkillTarget;
	ANGLE m_aHeadingRotation;
	INDEX m_nPreDesiredSkillNum;
	BOOL m_bWaitForSkillResponse;
	FLOAT m_fCameraAngle;
	BOOL m_bPlayAction;
	INDEX m_nPlayActionNum;
	CEntityPointer m_penWillDeathMob;
	BOOL m_bReservedCancel;
	BOOL m_bNotRenderParticles;
	BOOL m_bRcvAtMsg;
	BOOL m_bCriticalDamage;
	BOOL m_bReadySendSkillMessage;
	INDEX m_idCurrentActionAnim;
	INDEX m_nCurrentActionNum;
	INDEX m_nDesiredActionNum;
	BOOL m_bAction;
	BOOL m_nActionSit;
	CTFileName m_fnMusic;
	FLOAT m_fVolume;
	enum MusicType m_mtType;
	BOOL m_bFieldArea;
	BOOL m_bDying;
	BOOL m_bLockSkillCancel;
	BOOL m_bConnectEffect;
	BOOL m_bProduction;
	INDEX m_nProductionNum;
	BOOL m_bEnvironmentSound;
	BOOL m_bStartPostSkill;
	BOOL m_bRunningMode;
	INDEX m_iSkillEffectStep;
	BOOL m_bCriticalDamageMe;
	FLOAT m_tmSendSkillMessage;
	BOOL m_bSpeedUp;
	BOOL m_bSendStopMessage;
	FLOAT3D m_vMyPositionTmp;
	BOOL m_bMobChange;
	INDEX m_nLegit;
	BOOL m_bStuned;
	BOOL m_bDisappearWeapon;
	BOOL m_bChanging;
	INDEX m_nChangeMonsterId;
	INDEX m_nProduceItemDBIndex;
	BOOL m_bHold;
	BOOL m_bCannotUseSkill;
	BOOL m_bRide;
	INDEX m_iRideType;
	BOOL m_bWildRide;
	BOOL m_bDeathChk;
	BOOL m_bIsTransform;
	INDEX m_iTransformType;
	BOOL m_bTransforming;
	BOOL m_bOnlyRotate;
	BOOL m_bClicked;
	BOOL m_bCanSkillCancel;
ShellLaunchData ShellLaunchData_array;
INDEX m_iFirstEmptySLD;
BulletSprayLaunchData BulletSprayLaunchData_array;
INDEX m_iFirstEmptyBSLD;
GoreSprayLaunchData GoreSprayLaunchData_array;
INDEX m_iFirstEmptyGSLD;
ULONG ulButtonsNow;
ULONG ulButtonsBefore;
ULONG ulNewButtons;
ULONG ulReleasedButtons;
CSoundListener sliSound;
CSelectedEntities m_dcEnemies;
INDEX m_ctUnreadMessages;
PlayerStats m_psLevelStats;
PlayerStats m_psLevelTotal;
PlayerStats m_psGameStats;
PlayerStats m_psGameTotal;
CModelObject m_moRender;
CModelInstance m_miRender;
CAnyProjection3D m_apr;
CValue < FLOAT > m_fBurnLeftTime;
CValue < FLOAT > m_fLastBurnTime;
CEffectGroup * m_pPickingEffectGroup;
CEffectGroup * m_pSkillReadyEffect;
CEffectGroup * m_pAttachPlayerEffect;
CEffectGroup * m_pAttachEnemyEffect;
CEffectGroup * m_pHolyWaterEffectL;
CEffectGroup * m_pHolyWaterEffectR;
CEntityPointer m_penStillTarget;
MeshInstance miWeapon;
CStaticArray < FLOAT > m_afHardCodeValue;
CModelInstance * m_pRiderModelInstance;
CModelInstance * m_pRidePetModelInstance;
CModelInstance * m_pRideCharModelInstance;
QVect mi_qvOffset;
INDEX mi_iParentBoneID;
CEntityPointer m_penClickTarget;
CTextureObject m_pSkillTexture;
INDEX iDeathMotion;
BOOL m_bNoAniGuildSkill;
HUD_MLData m_HUDMLData;
HUD_MLData m_HUDItemData;
INDEX m_nWildPetType;
INDEX m_iEnermyID;
   
#line 2026 "C:/LC/Client/EntitiesMP/Player.es"
void Precache(void);
   
#line 2031 "C:/LC/Client/EntitiesMP/Player.es"
void LevelChangePlayerClear(void);
   
#line 2046 "C:/LC/Client/EntitiesMP/Player.es"
void OnEnd(void);
   
#line 2052 "C:/LC/Client/EntitiesMP/Player.es"
BOOL HandleEvent(const CEntityEvent & ee);
  
#line 2109 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetWeaponAndAnimator();
  
#line 2117 "C:/LC/Client/EntitiesMP/Player.es"
virtual SBYTE GetNetworkType()const;
   
#line 2122 "C:/LC/Client/EntitiesMP/Player.es"
void SetRotation(INDEX & iRotPacked,FLOAT fUnpacked);
   
#line 2127 "C:/LC/Client/EntitiesMP/Player.es"
FLOAT GetRotation(INDEX iRotPacked);
   
#line 2132 "C:/LC/Client/EntitiesMP/Player.es"
FLOAT GetRotationDiff(INDEX iRotPacked,FLOAT fUnpacked);
   
#line 2139 "C:/LC/Client/EntitiesMP/Player.es"
void PlaySound(CSoundObject & so,SLONG idSoundComponent,SLONG slPlayType);
   
#line 2145 "C:/LC/Client/EntitiesMP/Player.es"
void PlaySound(CSoundObject & so,const CTFileName & fnmSound,SLONG slPlayType);
   
#line 2152 "C:/LC/Client/EntitiesMP/Player.es"
void InitializeFromNet();
   
#line 2161 "C:/LC/Client/EntitiesMP/Player.es"
BOOL IsActionApplied();
  
#line 2165 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetActionApplied();
  
#line 2169 "C:/LC/Client/EntitiesMP/Player.es"
virtual void ClearActionApplied();
  
#line 2173 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsReapplyingActions();
  
#line 2176 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetReapplyingActions();
  
#line 2179 "C:/LC/Client/EntitiesMP/Player.es"
virtual void ClearReapplyingActions();
  
#line 2183 "C:/LC/Client/EntitiesMP/Player.es"
virtual void DumpToConsole();
  
#line 2226 "C:/LC/Client/EntitiesMP/Player.es"
virtual void ProcessProduce(SBYTE sbChaType,SLONG slChaIndex,SBYTE sbTargetType,SLONG slTargetIndex,SLONG slTargetHP);
   
#line 2270 "C:/LC/Client/EntitiesMP/Player.es"
void UpdateUnitInfo(CEntity * pEntity,INDEX iTargetID,SLONG lTargetHP);
  
#line 2299 "C:/LC/Client/EntitiesMP/Player.es"
virtual void HUD_DrawModel(CDrawPort * pdp,FLOAT fMinX,FLOAT fMinY,FLOAT fMaxX,FLOAT fMaxY,INDEX iType,FLOAT fDistance,FLOAT fHeight);
  
#line 2319 "C:/LC/Client/EntitiesMP/Player.es"
virtual void HUD_SetCharModelData(INDEX iJob,INDEX iHairStyle,INDEX iFaceStyle);
  
#line 2352 "C:/LC/Client/EntitiesMP/Player.es"
virtual void HUD_ChangeHairMesh(INDEX iJob,INDEX iHairStyle);
  
#line 2357 "C:/LC/Client/EntitiesMP/Player.es"
virtual void HUD_ChangeFaceMesh(INDEX iJob,INDEX iFaceStyle);
  
#line 2362 "C:/LC/Client/EntitiesMP/Player.es"
virtual void HUD_PlayAnimation(INDEX iJob,INDEX AnimID);
  
#line 2368 "C:/LC/Client/EntitiesMP/Player.es"
virtual void HUD_PlayAnimation(CTString strAniName);
  
#line 2374 "C:/LC/Client/EntitiesMP/Player.es"
virtual void HUD_SetModelColor(const COLOR ModelColor);
  
#line 2379 "C:/LC/Client/EntitiesMP/Player.es"
virtual void HUD_SetModelData(INDEX iType,INDEX iIndex,INDEX iUIType);
  
#line 2453 "C:/LC/Client/EntitiesMP/Player.es"
virtual FLOAT GetAnimationTime();
  
#line 2463 "C:/LC/Client/EntitiesMP/Player.es"
virtual void HUD_WearingModel(INDEX iType,INDEX iJob,INDEX iItem,BOOL bLogin);
  
#line 2497 "C:/LC/Client/EntitiesMP/Player.es"
virtual void HUD_SetTitleEffect(CTString strEffectName);
  
#line 2509 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsHudModel_Used();
  
#line 2514 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetHudModel_Use(BOOL bUse);
  
#line 2519 "C:/LC/Client/EntitiesMP/Player.es"
virtual CModelInstance * GetPlayerModelInstance(CEntity * pEntity);
   
#line 2536 "C:/LC/Client/EntitiesMP/Player.es"
CModelInstance * GetCurrentPlayerModelInstance();
  
#line 2560 "C:/LC/Client/EntitiesMP/Player.es"
virtual void EnemyTargetSelected_InputTab();
  
#line 2643 "C:/LC/Client/EntitiesMP/Player.es"
virtual void EvocationStart(LONG lIndex,int nSkillIndex);
  
#line 2670 "C:/LC/Client/EntitiesMP/Player.es"
virtual void EvocationStop(LONG lIndex);
  
#line 2716 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Read_net_Mob(int index,CNetworkMessage * istr);
  
#line 2804 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Read_net_Pet(int index,CNetworkMessage * istr);
  
#line 3018 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Read_net_WildPet(int index,CNetworkMessage * istr);
  
#line 3216 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Read_net_StatusPC(CNetworkMessage * istr);
  
#line 3455 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Read_net_StatusNPC(CNetworkMessage * istr);
  
#line 3555 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Read_net_StatusPet(CNetworkMessage * istr);
  
#line 3562 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Read_net_StatusElemental(CNetworkMessage * istr);
  
#line 3626 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Read_net_Damage_Character(CNetworkMessage * istr);
  
#line 4080 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Read_net_DissappearEffect(CNetworkMessage * istr);
  
#line 4096 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Read_net_Damage(SBYTE sbType,CNetworkMessage * istr);
  
#line 4419 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Read_net_Summon(int index,CNetworkMessage * istr);
  
#line 4520 "C:/LC/Client/EntitiesMP/Player.es"
virtual void OpenGate(int iGateNumber,BOOL bOpenGate);
  
#line 4640 "C:/LC/Client/EntitiesMP/Player.es"
virtual void StandDown(BOOL bStand);
  
#line 4664 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetChaData(int index,int type,ULONG hp,ULONG maxHp,SBYTE hairStyle,SBYTE faceStyle,CTString & strName,UWORD state,SBYTE pkTitle,SLONG pkstate);
  
#line 4745 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetCharacterState(CEntity * cha_Entity,INDEX ch_state);
  
#line 4753 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetShopData(INDEX index,SBYTE sbShopType);
  
#line 4774 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetImportantValues(FLOAT fWalkspeed,FLOAT fRunspeed,FLOAT fAttackrange,SBYTE sbAttackspeed,SBYTE sbMagicspeed);
  
#line 4782 "C:/LC/Client/EntitiesMP/Player.es"
virtual FLOAT GetWalkspeed();
  
#line 4786 "C:/LC/Client/EntitiesMP/Player.es"
virtual FLOAT GetRunspeed();
  
#line 4790 "C:/LC/Client/EntitiesMP/Player.es"
virtual FLOAT GetAttackrange();
  
#line 4794 "C:/LC/Client/EntitiesMP/Player.es"
virtual SBYTE GetAttackspeed();
  
#line 4798 "C:/LC/Client/EntitiesMP/Player.es"
virtual SBYTE GetMagicspeed();
  
#line 4803 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetSkillCancel(BOOL bCanSkillCancel);
  
#line 4810 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL CheckNormalAttack(CEntity * pEntity,FLOAT fDist);
  
#line 4837 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL CheckAttackTarget(INDEX iSkillIndex,CEntity * pEntity,FLOAT fDist);
  
#line 4893 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL CheckEntityOfTarget(CEntity * pEntity,CEntity * pTarget);
   
#line 4903 "C:/LC/Client/EntitiesMP/Player.es"
BOOL CheckDratanWarInside(CCharacterTarget * pTarget);
   
#line 4927 "C:/LC/Client/EntitiesMP/Player.es"
BOOL MyCheckDratanWarInside();
   
#line 4940 "C:/LC/Client/EntitiesMP/Player.es"
INDEX WarTypeAttackGroup(SBYTE sbType);
   
#line 4956 "C:/LC/Client/EntitiesMP/Player.es"
BOOL CheckAttackCharacter(CEntity * penEnt,FLOAT fLength);
   
#line 5217 "C:/LC/Client/EntitiesMP/Player.es"
BOOL CheckAttackPet(CEntity * pEntity,FLOAT fLength);
   
#line 5243 "C:/LC/Client/EntitiesMP/Player.es"
BOOL CheckAttackWildPet(CEntity * pEntity,FLOAT fLength);
   
#line 5279 "C:/LC/Client/EntitiesMP/Player.es"
BOOL CheckAttackSlave(CEntity * pEntity,FLOAT fLength);
   
#line 5304 "C:/LC/Client/EntitiesMP/Player.es"
BOOL CheckAttackEnemy(CEntity * pEntity,float fLength);
  
#line 5460 "C:/LC/Client/EntitiesMP/Player.es"
virtual void StartCamera(CEntity * pTarget,BOOL bRestart);
  
#line 5467 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetWideScreen(CEntity * pTarget,BOOL bWide,FLOAT fFov);
  
#line 5480 "C:/LC/Client/EntitiesMP/Player.es"
virtual void GetProjection(CAnyProjection3D & apr);
  
#line 5486 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetProduct(SLONG slChaIndex,SBYTE slProductType);
  
#line 5501 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetConsensus(SLONG slChaIndex);
  
#line 5520 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetSummonCommand(CEntity * pEntity,INDEX iCommand);
  
#line 5530 "C:/LC/Client/EntitiesMP/Player.es"
virtual void WarpTeleport(FLOAT fX,FLOAT fZ,FLOAT fH,FLOAT fR,SBYTE sbLayer);
   
#line 5571 "C:/LC/Client/EntitiesMP/Player.es"
CTFileName GetHairMeshName(int iJob,SBYTE sbHairType);
   
#line 5591 "C:/LC/Client/EntitiesMP/Player.es"
CTFileName GetHairTextureName(int iJob,SBYTE sbHairType,SBYTE sbSubType);
   
#line 5616 "C:/LC/Client/EntitiesMP/Player.es"
void SetCharacterHairChange(INDEX nSIdx,SBYTE sbType,BOOL IsMe);
   
#line 5684 "C:/LC/Client/EntitiesMP/Player.es"
void SetCharacterAppearance(CModelInstance * pMI,int iJob,SBYTE sbHairType,SBYTE sbFaceType);
   
#line 5690 "C:/LC/Client/EntitiesMP/Player.es"
void ChangeFaceMesh(CModelInstance * pMI,int iJob,SBYTE sbType);
  
#line 5753 "C:/LC/Client/EntitiesMP/Player.es"
virtual void ChangeHairMesh(CModelInstance * pMI,int iJob,SBYTE sbType);
  
#line 5829 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetChaWearing(CCharacterTarget * pTarget,CEntity * penEntity,CNetworkMessage * istr);
  
#line 5979 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetCharCostumeWearing(CCharacterTarget * pTarget,CEntity * penEntity,CNetworkMessage * istr);
  
#line 6004 "C:/LC/Client/EntitiesMP/Player.es"
virtual void WearingCostumeArmor(CNetworkMessage * istr);
  
#line 6150 "C:/LC/Client/EntitiesMP/Player.es"
virtual void WearingCostumeArmorOneSuit(CNetworkMessage * istr);
  
#line 6165 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsHelmet(INDEX iCharIndex);
   
#line 6181 "C:/LC/Client/EntitiesMP/Player.es"
void WearingCostumeArmorProcess(INDEX slCharIndex,INDEX sbWwearPos,INDEX slItemIndex);
   
#line 6294 "C:/LC/Client/EntitiesMP/Player.es"
void NickNameEffect(CEntity * pAttackEn,CEntity * pTargetEn,NickNameEffectType iType);
   
#line 6354 "C:/LC/Client/EntitiesMP/Player.es"
void SetNickNameDamageEffect(INDEX iNickIndex,NickNameEffectType iType);
   
#line 6383 "C:/LC/Client/EntitiesMP/Player.es"
void SetCustomTitleEffect(CTString effectName);
  
#line 6391 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetDecoModeCamera(FLOAT fDistance,FLOAT fHeight);
  
#line 6418 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetAppearanceData(int index,SBYTE hairstyle,SBYTE facestyle);
   
#line 6430 "C:/LC/Client/EntitiesMP/Player.es"
void ShowDamageResult(CEntity * pEntity,ULONG targetDamage,SBYTE targetFlag,SLONG skillIndex);
   
#line 6557 "C:/LC/Client/EntitiesMP/Player.es"
void ShowAttackResult(CEntity * penTargetEntity,ULONG targetDamage,SBYTE targetFlag,SLONG skillIndex);
#line 6627 "C:/LC/Client/EntitiesMP/Player.es"
#define IS_FLAG_ON(flagAll, flagVal) ( (flagAll) & (static_cast<SQUAD>((1L))<<(flagVal)) )
  
#line 6612 "C:/LC/Client/EntitiesMP/Player.es"
virtual void CancelProduct();
  
#line 6630 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Read_net_Character(int type,int sub_type,CNetworkMessage * istr);
   
#line 7357 "C:/LC/Client/EntitiesMP/Player.es"
void Read_net_Character_Item(int sub_type,CNetworkMessage * istr);
   
#line 7418 "C:/LC/Client/EntitiesMP/Player.es"
void Read_net_Character_Skill(int sub_type,CNetworkMessage * istr);
   
#line 7662 "C:/LC/Client/EntitiesMP/Player.es"
INDEX GenderSound(INDEX iSound);
   
#line 7667 "C:/LC/Client/EntitiesMP/Player.es"
void AddBouble(FLOAT3D vPos,FLOAT3D vSpeedRelative);
   
#line 7681 "C:/LC/Client/EntitiesMP/Player.es"
void ClearShellLaunchData(void);
   
#line 7691 "C:/LC/Client/EntitiesMP/Player.es"
void AddBulletSpray(FLOAT3D vPos,EffectParticlesType eptType,FLOAT3D vStretch);
   
#line 7704 "C:/LC/Client/EntitiesMP/Player.es"
void ClearBulletSprayLaunchData(void);
   
#line 7713 "C:/LC/Client/EntitiesMP/Player.es"
void AddGoreSpray(FLOAT3D vPos,FLOAT3D v3rdPos,SprayParticlesType sptType,FLOAT3D vSpilDirection,
#line 7714 "C:/LC/Client/EntitiesMP/Player.es"
FLOATaabbox3D boxHitted,FLOAT fDamagePower,COLOR colParticles);
   
#line 7731 "C:/LC/Client/EntitiesMP/Player.es"
void ClearGoreSprayLaunchData(void);
    CPlayer(void);
   
#line 7755 "C:/LC/Client/EntitiesMP/Player.es"
class CPlayerWeapons * GetPlayerWeapons(void);
   
#line 7760 "C:/LC/Client/EntitiesMP/Player.es"
class CPlayerAnimator * GetPlayerAnimator(void);
   
#line 7766 "C:/LC/Client/EntitiesMP/Player.es"
CPlayerSettings * GetSettings(void);
   void Copy(CEntity & enOther,ULONG ulFlags);
   
#line 7789 "C:/LC/Client/EntitiesMP/Player.es"
void UpdateLatency(FLOAT tmLatencyNow);
   
#line 7826 "C:/LC/Client/EntitiesMP/Player.es"
void ValidateCharacter(void);
   
#line 7836 "C:/LC/Client/EntitiesMP/Player.es"
void ParseGender(CTString & strName);
   
#line 7848 "C:/LC/Client/EntitiesMP/Player.es"
void Write_t(CTStream * ostr,BOOL bNetwork);
   
#line 7858 "C:/LC/Client/EntitiesMP/Player.es"
void Read_t(CTStream * istr,BOOL bNetwork);
   
#line 7904 "C:/LC/Client/EntitiesMP/Player.es"
TIME GetStatsInGameTimeLevel(void);
   
#line 7912 "C:/LC/Client/EntitiesMP/Player.es"
TIME GetStatsInGameTimeGame(void);
   
#line 7921 "C:/LC/Client/EntitiesMP/Player.es"
FLOAT GetStatsRealWorldTime(void);
   
#line 7932 "C:/LC/Client/EntitiesMP/Player.es"
CTString GetStatsRealWorldStarted(void);
   void GetStats(CTString & strStats,const CompStatType csType,INDEX ctCharsPerRow);
   
#line 7972 "C:/LC/Client/EntitiesMP/Player.es"
void GetShortStats(CTString & strStats);
   
#line 7979 "C:/LC/Client/EntitiesMP/Player.es"
void GetDetailStatsDM(CTString & strStats);
   
#line 8054 "C:/LC/Client/EntitiesMP/Player.es"
void GetDetailStatsCoop(CTString & strStats);
   
#line 8132 "C:/LC/Client/EntitiesMP/Player.es"
void GetDetailStatsSP(CTString & strStats,INDEX iCoopType);
   
#line 8225 "C:/LC/Client/EntitiesMP/Player.es"
void SayVoiceMessage(const CTFileName & fnmMessage);
   
#line 8255 "C:/LC/Client/EntitiesMP/Player.es"
void PlayLightAnim(INDEX iAnim,ULONG ulFlags);
   
#line 8262 "C:/LC/Client/EntitiesMP/Player.es"
BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   
#line 8327 "C:/LC/Client/EntitiesMP/Player.es"
CModelObject * GetModelForRendering(void);
   
#line 8401 "C:/LC/Client/EntitiesMP/Player.es"
CModelInstance * GetModelInstanceForRendering(void);
   
#line 8470 "C:/LC/Client/EntitiesMP/Player.es"
class CPlayerActionMarker * GetActionMarker(void);
   
#line 8475 "C:/LC/Client/EntitiesMP/Player.es"
void FindMusicHolder(void);
   
#line 8483 "C:/LC/Client/EntitiesMP/Player.es"
void UpdateLevelStats(void);
   
#line 8506 "C:/LC/Client/EntitiesMP/Player.es"
BOOL IsFuss(void);
   
#line 8517 "C:/LC/Client/EntitiesMP/Player.es"
void SetDefaultMouthPitch(void);
   
#line 8521 "C:/LC/Client/EntitiesMP/Player.es"
void SetRandomMouthPitch(FLOAT fMin,FLOAT fMax);
   
#line 8527 "C:/LC/Client/EntitiesMP/Player.es"
void ApplyShaking(CPlacement3D & plViewer);
   
#line 8580 "C:/LC/Client/EntitiesMP/Player.es"
COLOR GetWorldGlaring(void);
   
#line 8593 "C:/LC/Client/EntitiesMP/Player.es"
void RenderHudPicFX(CDrawPort * pdp);
   
#line 8607 "C:/LC/Client/EntitiesMP/Player.es"
void SetupView(CDrawPort * pdp,CAnyProjection3D & apr,CEntity * & penViewer,
#line 8608 "C:/LC/Client/EntitiesMP/Player.es"
CPlacement3D & plViewer,COLOR & colBlend,BOOL bCamera);
   
#line 8745 "C:/LC/Client/EntitiesMP/Player.es"
void ListenFromEntity(CEntity * penListener,const CPlacement3D & plSound);
   
#line 8775 "C:/LC/Client/EntitiesMP/Player.es"
void RenderDummyView(CDrawPort * pdp);
   
#line 8802 "C:/LC/Client/EntitiesMP/Player.es"
void RenderPlayerView(CDrawPort * pdp,BOOL bShowExtras);
   
#line 8934 "C:/LC/Client/EntitiesMP/Player.es"
void RenderCameraView(CDrawPort * pdp,BOOL bListen);
   
#line 9022 "C:/LC/Client/EntitiesMP/Player.es"
void RenderGameView(CDrawPort * pdp,void * pvUserData);
   
#line 9103 "C:/LC/Client/EntitiesMP/Player.es"
void PreMoving(void);
   
#line 9143 "C:/LC/Client/EntitiesMP/Player.es"
void DoMoving(void);
   
#line 9167 "C:/LC/Client/EntitiesMP/Player.es"
void PostMoving(void);
   
#line 9364 "C:/LC/Client/EntitiesMP/Player.es"
void SetUnconnected(void);
   
#line 9387 "C:/LC/Client/EntitiesMP/Player.es"
void SetConnected(void);
   
#line 9400 "C:/LC/Client/EntitiesMP/Player.es"
BOOL IsConnected(void)const;
  
#line 9411 "C:/LC/Client/EntitiesMP/Player.es"
virtual void LeaveStain(BOOL bGrow);
   
#line 9446 "C:/LC/Client/EntitiesMP/Player.es"
void DamageImpact(enum DamageType dmtType,
#line 9447 "C:/LC/Client/EntitiesMP/Player.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 9589 "C:/LC/Client/EntitiesMP/Player.es"
void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 9590 "C:/LC/Client/EntitiesMP/Player.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 9861 "C:/LC/Client/EntitiesMP/Player.es"
BOOL ShouldBlowUp(void);
   
#line 9876 "C:/LC/Client/EntitiesMP/Player.es"
FLOAT GetPlaneFrustumAngle(const FLOAT3D & vDir);
   
#line 9895 "C:/LC/Client/EntitiesMP/Player.es"
void * GetEntityInfo(void);
   
#line 9970 "C:/LC/Client/EntitiesMP/Player.es"
void ChangePlayerView();
   
#line 10019 "C:/LC/Client/EntitiesMP/Player.es"
void UsePressed(BOOL bOrComputer);
   
#line 10083 "C:/LC/Client/EntitiesMP/Player.es"
void SetGameEnd(void);
   
#line 10116 "C:/LC/Client/EntitiesMP/Player.es"
FLOAT CalculateViewRotationDamping(void);
   
#line 10133 "C:/LC/Client/EntitiesMP/Player.es"
void ApplyAction(const CPlayerAction & paOriginal,FLOAT tmLatency);
   
#line 10260 "C:/LC/Client/EntitiesMP/Player.es"
void Disconnect(void);
#line 10270 "C:/LC/Client/EntitiesMP/Player.es"
#define TRANSFORMATION_TIME		1.8f
   
#line 10274 "C:/LC/Client/EntitiesMP/Player.es"
void TransformSorcerer(int iType);
   
#line 10351 "C:/LC/Client/EntitiesMP/Player.es"
void ReturnSorcerer();
   
#line 10438 "C:/LC/Client/EntitiesMP/Player.es"
void MonsterChange(int type);
  
#line 10472 "C:/LC/Client/EntitiesMP/Player.es"
virtual void ReturnChange(BOOL bAppear);
   
#line 10567 "C:/LC/Client/EntitiesMP/Player.es"
void MinMaximize();
   
#line 10715 "C:/LC/Client/EntitiesMP/Player.es"
void Transforming();
   
#line 10734 "C:/LC/Client/EntitiesMP/Player.es"
void CharacterChanged(const CPlayerCharacter & pcNew);
   
#line 10842 "C:/LC/Client/EntitiesMP/Player.es"
BOOL CheckEscKey(void);
   
#line 10900 "C:/LC/Client/EntitiesMP/Player.es"
void AliveActions(const CPlayerAction & pa);
   
#line 10946 "C:/LC/Client/EntitiesMP/Player.es"
void AutoActions(const CPlayerAction & pa);
   
#line 11017 "C:/LC/Client/EntitiesMP/Player.es"
void GetLerpedWeaponPosition(FLOAT3D vRel,CPlacement3D & pl);
   
#line 11026 "C:/LC/Client/EntitiesMP/Player.es"
void SpawnBubbles(INDEX ctBubbles);
   
#line 11050 "C:/LC/Client/EntitiesMP/Player.es"
void ActiveActions(const CPlayerAction & paAction);
   
#line 11633 "C:/LC/Client/EntitiesMP/Player.es"
BOOL SkillCondition(INDEX skillIndex,CEntityPointer penTarget,BOOL & bLostTarget,BOOL & bAutoAttack);
   
#line 11715 "C:/LC/Client/EntitiesMP/Player.es"
BOOL SkillAnimationEx(void);
   
#line 12390 "C:/LC/Client/EntitiesMP/Player.es"
BOOL HardCodingSkill(BOOL bOnlyTest);
   
#line 12748 "C:/LC/Client/EntitiesMP/Player.es"
void RoundViewAngle(ANGLE & aViewAngle,ANGLE aRound);
   
#line 12761 "C:/LC/Client/EntitiesMP/Player.es"
void DeathActions(const CPlayerAction & paAction);
   
#line 12822 "C:/LC/Client/EntitiesMP/Player.es"
void ButtonsActions(CPlayerAction & paAction);
   
#line 13522 "C:/LC/Client/EntitiesMP/Player.es"
BOOL CheatsEnabled(void);
   
#line 13533 "C:/LC/Client/EntitiesMP/Player.es"
void GetLerpedAbsoluteViewPlacement(CPlacement3D & plView);
   
#line 13633 "C:/LC/Client/EntitiesMP/Player.es"
CEntity * GetViewEntity(BOOL bCamera);
   
#line 13670 "C:/LC/Client/EntitiesMP/Player.es"
void RenderChainsawParticles(BOOL bThird);
   
#line 13706 "C:/LC/Client/EntitiesMP/Player.es"
void RenderHUD(CPerspectiveProjection3D & prProjection,CDrawPort * pdp,
#line 13707 "C:/LC/Client/EntitiesMP/Player.es"
FLOAT3D vViewerLightDirection,COLOR colViewerLight,COLOR colViewerAmbient,
#line 13708 "C:/LC/Client/EntitiesMP/Player.es"
BOOL bRenderWeapon,INDEX iEye);
   
#line 13859 "C:/LC/Client/EntitiesMP/Player.es"
void RenderCursor(CDrawPort * pdp,void * pvUserData);
   
#line 13911 "C:/LC/Client/EntitiesMP/Player.es"
void InitializePlayer(BOOL bFirstInit);
   
#line 14017 "C:/LC/Client/EntitiesMP/Player.es"
FLOAT3D GetTeleportingOffset(void);
   
#line 14034 "C:/LC/Client/EntitiesMP/Player.es"
void RemapLevelNames(INDEX & iLevel);
   
#line 14082 "C:/LC/Client/EntitiesMP/Player.es"
void TeleportPlayer(enum WorldLinkType EwltType,PlayerTeleportCause eCause);
   
#line 14385 "C:/LC/Client/EntitiesMP/Player.es"
void CreateAnimAndBoneIDs(void);
   
#line 14401 "C:/LC/Client/EntitiesMP/Player.es"
void FillAnimAndBoneIDs();
   
#line 14417 "C:/LC/Client/EntitiesMP/Player.es"
void IdleAnim();
   
#line 14545 "C:/LC/Client/EntitiesMP/Player.es"
void ChangeWholeAnim(INDEX idBodyAnim,ULONG ulFlags,FLOAT fStrength,FLOAT fFadeTime,FLOAT fSpeed);
   
#line 15764 "C:/LC/Client/EntitiesMP/Player.es"
void SetHitEffect(INDEX idBodyAnim,int nHitType,CEntity * pen,INDEX iAttackType);
   
#line 16420 "C:/LC/Client/EntitiesMP/Player.es"
void SpawnTeleport(void);
   
#line 16440 "C:/LC/Client/EntitiesMP/Player.es"
void RenderParticles(void);
   
#line 16546 "C:/LC/Client/EntitiesMP/Player.es"
void TeleportToAutoMarker(CPlayerActionMarker * ppam);
   
#line 16575 "C:/LC/Client/EntitiesMP/Player.es"
void CheckDeathForRespawnInPlace(EPlayerDeath ePLDeath);
  
#line 16598 "C:/LC/Client/EntitiesMP/Player.es"
virtual ULONG SetDesiredMovement();
   
#line 16791 "C:/LC/Client/EntitiesMP/Player.es"
BOOL CheckTarget();
   
#line 18133 "C:/LC/Client/EntitiesMP/Player.es"
void StopAttack();
   
#line 18138 "C:/LC/Client/EntitiesMP/Player.es"
void StartAttack();
   
#line 18153 "C:/LC/Client/EntitiesMP/Player.es"
BOOL IsAttacking();
   
#line 18158 "C:/LC/Client/EntitiesMP/Player.es"
BOOL IsProduct();
   
#line 18163 "C:/LC/Client/EntitiesMP/Player.es"
void StopMove();
   
#line 18207 "C:/LC/Client/EntitiesMP/Player.es"
void ClearMove();
   
#line 18215 "C:/LC/Client/EntitiesMP/Player.es"
void StopMoveNoSendStopMsg();
   
#line 18235 "C:/LC/Client/EntitiesMP/Player.es"
void PickItem(ULONG targetindex);
  
#line 18245 "C:/LC/Client/EntitiesMP/Player.es"
virtual void PlayItemSound(BOOL bPick,BOOL bMoney);
   
#line 18264 "C:/LC/Client/EntitiesMP/Player.es"
void PlayButtonSound();
   
#line 18269 "C:/LC/Client/EntitiesMP/Player.es"
void PlayJewelDullSound();
   
#line 18274 "C:/LC/Client/EntitiesMP/Player.es"
void PlayJewelRefinementSound();
   
#line 18279 "C:/LC/Client/EntitiesMP/Player.es"
void PlayJewelShinySound();
   
#line 18284 "C:/LC/Client/EntitiesMP/Player.es"
void PlayPetStashEffectSound();
   
#line 18289 "C:/LC/Client/EntitiesMP/Player.es"
void PlayPetStashCardSelSound();
   
#line 18294 "C:/LC/Client/EntitiesMP/Player.es"
void PlayHolyWaterSound();
  
#line 18299 "C:/LC/Client/EntitiesMP/Player.es"
virtual void PlayItemEffect(SLONG itemindex,SBYTE effecttype);
   
#line 18340 "C:/LC/Client/EntitiesMP/Player.es"
BOOL DetectFloorHit(FLOAT deltaX,FLOAT deltaY,FLOAT deltaZ,CPlacement3D & plPlacement);
  
#line 18396 "C:/LC/Client/EntitiesMP/Player.es"
virtual void moveto(FLOAT3D vDelta);
   
#line 18449 "C:/LC/Client/EntitiesMP/Player.es"
void SendMyNextMovePosition(FLOAT3D vDelta);
   
#line 18600 "C:/LC/Client/EntitiesMP/Player.es"
BOOL Rotate(FLOAT3D vDelta,ANGLE aRotateSpeed,BOOL bFirstRotate);
   
#line 18659 "C:/LC/Client/EntitiesMP/Player.es"
void StopRotating();
   
#line 18665 "C:/LC/Client/EntitiesMP/Player.es"
void StopTranslating();
   
#line 18670 "C:/LC/Client/EntitiesMP/Player.es"
FLOAT CalcDistanceInPlaneToDestination(void);
   
#line 18678 "C:/LC/Client/EntitiesMP/Player.es"
void MoveNow();
   
#line 18689 "C:/LC/Client/EntitiesMP/Player.es"
void SetDefaultWearing();
  
#line 18696 "C:/LC/Client/EntitiesMP/Player.es"
virtual void DeleteCurrentArmor(int weartype);
  
#line 18724 "C:/LC/Client/EntitiesMP/Player.es"
virtual void DeleteDefaultArmor(int type);
  
#line 18735 "C:/LC/Client/EntitiesMP/Player.es"
virtual void WearingDefaultArmor(int type);
  
#line 18825 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsSocialActing();
  
#line 18837 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsPolymophing();
  
#line 18850 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsTransforming();
  
#line 18859 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsChanging();
   
#line 18870 "C:/LC/Client/EntitiesMP/Player.es"
void DeleteWearingWeapon(BOOL bException,BOOL bSkillReady);
   
#line 18930 "C:/LC/Client/EntitiesMP/Player.es"
void AppearWearingWeapon(BOOL bSkillEnd);
   
#line 18997 "C:/LC/Client/EntitiesMP/Player.es"
BOOL CheckSkillBuffer();
  
#line 19174 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL CheckSkill(void);
   
#line 19787 "C:/LC/Client/EntitiesMP/Player.es"
void SpellSkill(INDEX m_nCurrentSkillNum);
   
#line 19885 "C:/LC/Client/EntitiesMP/Player.es"
BOOL CheckAction();
   
#line 19911 "C:/LC/Client/EntitiesMP/Player.es"
void SkillAnimation(void);
  
#line 20654 "C:/LC/Client/EntitiesMP/Player.es"
virtual void UseSkill(int skillIndex);
  
#line 20752 "C:/LC/Client/EntitiesMP/Player.es"
virtual void UsePetPickItem();
  
#line 20764 "C:/LC/Client/EntitiesMP/Player.es"
virtual void UsePetSkill(int skillIndex);
  
#line 20803 "C:/LC/Client/EntitiesMP/Player.es"
virtual void UseSlaveSkill(CEntity * pEntity,int skillIndex);
  
#line 20808 "C:/LC/Client/EntitiesMP/Player.es"
virtual void UseWildSkill(CEntity * pEntity,int skillIndex);
  
#line 20820 "C:/LC/Client/EntitiesMP/Player.es"
virtual void UseAction(int ActionIndex);
  
#line 21048 "C:/LC/Client/EntitiesMP/Player.es"
virtual void ClearMultiTargets();
  
#line 21053 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsLegit();
   
#line 21065 "C:/LC/Client/EntitiesMP/Player.es"
void SetTargetNull();
  
#line 21073 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetTargetMe();
  
#line 21098 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsSameTarget(CEntity * penEntity);
  
#line 21103 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetTarget(CEntity * penEntity);
  
#line 21118 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetMobData(CEntity * penEntity,SLONG hp,SLONG maxHp,int level,BOOL bNpc,int mobIdx);
  
#line 21127 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetPetData(CEntity * penEntity,SLONG hp,SLONG maxHP);
  
#line 21133 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetWildPetData(CEntity * penEntity,SLONG hp,SLONG maxHP);
  
#line 21143 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetElementalData(CEntity * penEntity,SLONG hp,SLONG maxHP);
  
#line 21169 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetElementalStatus(CEntity * penEntity,SBYTE sbAttackSpeed,SBYTE sbMagicSpeed,LONG lSkillSpeed,FLOAT fWalkSpeed,FLOAT fRunSpeed,FLOAT fAttackRange);
  
#line 21188 "C:/LC/Client/EntitiesMP/Player.es"
virtual void CommandAttack();
  
#line 21198 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL CommandAction();
   
#line 21228 "C:/LC/Client/EntitiesMP/Player.es"
void InflictDirectDamage(CEntity * penToDamage,CEntity * penInflictor,enum DamageType dmtType,
#line 21229 "C:/LC/Client/EntitiesMP/Player.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
  
#line 21509 "C:/LC/Client/EntitiesMP/Player.es"
virtual void CancelSkill(BOOL bLostTarget,BOOL bAutoAttack,BOOL bSkillError);
  
#line 21655 "C:/LC/Client/EntitiesMP/Player.es"
virtual void Rebirth();
   
#line 21674 "C:/LC/Client/EntitiesMP/Player.es"
void CheckField();
  
#line 21726 "C:/LC/Client/EntitiesMP/Player.es"
virtual void PlayBGM(CTFileName fnFileName);
  
#line 21739 "C:/LC/Client/EntitiesMP/Player.es"
virtual void StopBGM(CTFileName fnFileName);
   
#line 21751 "C:/LC/Client/EntitiesMP/Player.es"
void PlayMusic();
  
#line 21831 "C:/LC/Client/EntitiesMP/Player.es"
virtual void AddDeathItem(CEntity * penEnemy,FLOAT3D pos,class CItemTarget * pItemTarget,class CItemData * pItemData);
  
#line 21839 "C:/LC/Client/EntitiesMP/Player.es"
virtual void DropDeathItem(CEntity * penEnemy);
   
#line 21845 "C:/LC/Client/EntitiesMP/Player.es"
bool IsTestClient();
  
#line 21857 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL BOTSearchItem(int X);
  
#line 21928 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SearchNearItem();
   
#line 22000 "C:/LC/Client/EntitiesMP/Player.es"
BOOL IsNotPersnalDungeon();
  
#line 22011 "C:/LC/Client/EntitiesMP/Player.es"
virtual void DeathYou();
  
#line 22249 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsAlreadyDie();
  
#line 22254 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetDie();
  
#line 22259 "C:/LC/Client/EntitiesMP/Player.es"
virtual void PlayerInit(bool bDeath);
   
#line 22321 "C:/LC/Client/EntitiesMP/Player.es"
BOOL IsPvp();
  
#line 22326 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsMoving();
  
#line 22331 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsInputMovingKey();
   
#line 22339 "C:/LC/Client/EntitiesMP/Player.es"
BOOL IsInputRotateKey();
  
#line 22347 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL InputKey(INDEX Code);
   
#line 22592 "C:/LC/Client/EntitiesMP/Player.es"
BOOL IsEXRogue(int job);
   
#line 22597 "C:/LC/Client/EntitiesMP/Player.es"
BOOL IsEXMage(int job);
  
#line 22606 "C:/LC/Client/EntitiesMP/Player.es"
virtual void ClearTargetInfo(CEntity * penEntity);
  
#line 22633 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsSkilling();
  
#line 22638 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsPetActing();
  
#line 22652 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsActionSitting();
  
#line 22661 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsSitting();
   
#line 22679 "C:/LC/Client/EntitiesMP/Player.es"
void LostTarget();
  
#line 22698 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsIdle();
  
#line 22709 "C:/LC/Client/EntitiesMP/Player.es"
virtual const BOOL IsTransform()const;
  
#line 22719 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetSpeedUp(BOOL bMe,INDEX index,BOOL bSpeedup);
  
#line 22738 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL IsRidePet(CEntity * pCharacter);
  
#line 22751 "C:/LC/Client/EntitiesMP/Player.es"
virtual void RidingPet(CEntity * pCharacter,INDEX iPetType);
  
#line 22837 "C:/LC/Client/EntitiesMP/Player.es"
virtual void LeavingPet(CEntity * pCharacter);
   
#line 22895 "C:/LC/Client/EntitiesMP/Player.es"
void InitBeastAnimation(void);
   
#line 22914 "C:/LC/Client/EntitiesMP/Player.es"
void SetBeastAnimation(CEntity * pWildPet);
  
#line 22935 "C:/LC/Client/EntitiesMP/Player.es"
virtual void RidingWildPet(CEntity * pCharacter,CEntity * pWildPet,CTString strFileName);
  
#line 23011 "C:/LC/Client/EntitiesMP/Player.es"
virtual void LeavingWildPet(CEntity * pCharacter);
   
#line 23067 "C:/LC/Client/EntitiesMP/Player.es"
void SetBodyAnimTime(float fAnimTime);
   
#line 23073 "C:/LC/Client/EntitiesMP/Player.es"
bool IsSealPet(LONG * remain);
   
#line 23099 "C:/LC/Client/EntitiesMP/Player.es"
const BOOL IsMovable();
  
#line 23133 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetRepairLegit(SLONG chainex,CCharacterTarget * Ct);
  
#line 23146 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SetLegit(UBYTE ubType,SLONG chaindex);
   
#line 23225 "C:/LC/Client/EntitiesMP/Player.es"
BOOL IsLegitTarget(CEntity * penEntity);
   
#line 23255 "C:/LC/Client/EntitiesMP/Player.es"
void DisplayChangeErr(SBYTE err);
  
#line 23295 "C:/LC/Client/EntitiesMP/Player.es"
virtual BOOL CheckChangeCondition(INDEX level,INDEX zone);
  
#line 23371 "C:/LC/Client/EntitiesMP/Player.es"
virtual void AppearChaPolymoph(CEntity * pentity,INDEX mobindex);
  
#line 23380 "C:/LC/Client/EntitiesMP/Player.es"
virtual void TransfromPet(CEntity * pentity,INDEX mobIndex,INDEX mobSize);
  
#line 23402 "C:/LC/Client/EntitiesMP/Player.es"
virtual void ReturnTransformPet(CEntity * pentity);
  
#line 23411 "C:/LC/Client/EntitiesMP/Player.es"
virtual void AppearChaTransform(CEntity * pEntity,INDEX iTransformType);
   
#line 23420 "C:/LC/Client/EntitiesMP/Player.es"
void StopPlayer();
   
#line 23425 "C:/LC/Client/EntitiesMP/Player.es"
BOOL IsVisibleCheckAll(CEntity * penEntity);
  
#line 23459 "C:/LC/Client/EntitiesMP/Player.es"
virtual void PlAddAccessoryEffect(CEntity * penEntity,CCharacterTarget * pTarget);
   
#line 23478 "C:/LC/Client/EntitiesMP/Player.es"
void SetTarget(SLONG targetID,SBYTE targetType);
   
#line 23555 "C:/LC/Client/EntitiesMP/Player.es"
void RaidSceneOutputProcessing(SLONG slOutputType,INDEX iObjIndex,INDEX iData);
  
#line 23683 "C:/LC/Client/EntitiesMP/Player.es"
virtual void ReceiveRaidScene(CNetworkMessage * istr);
  
#line 23763 "C:/LC/Client/EntitiesMP/Player.es"
virtual void SendTriggerEvent(INDEX iTarget,INDEX eetEventType);
  
#line 23782 "C:/LC/Client/EntitiesMP/Player.es"
virtual void ReceiveTriggerEvent(INDEX iIn,INDEX iOut,INDEX iContinued,CNetworkMessage * iStr);
  
#line 23838 "C:/LC/Client/EntitiesMP/Player.es"
virtual CEntity * GetClickObject(void);
#define  STATE_CPlayer_Main 1
	BOOL 
#line 23848 "C:/LC/Client/EntitiesMP/Player.es"
Main(const CEntityEvent &__eeInput);
	BOOL H0x0191000f_Main_01(const CEntityEvent &__eeInput);
	BOOL H0x01910010_Main_02(const CEntityEvent &__eeInput);
	BOOL H0x01910011_Main_03(const CEntityEvent &__eeInput);
	BOOL H0x01910012_Main_04(const CEntityEvent &__eeInput);
	BOOL H0x01910013_Main_05(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_Wounded 0x01910014
	BOOL 
#line 24301 "C:/LC/Client/EntitiesMP/Player.es"
Wounded(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_WorldChange 0x01910015
	BOOL 
#line 24309 "C:/LC/Client/EntitiesMP/Player.es"
WorldChange(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_WorldChangeDead 0x01910016
	BOOL 
#line 24381 "C:/LC/Client/EntitiesMP/Player.es"
WorldChangeDead(const CEntityEvent &__eeInput);
	BOOL H0x01910017_WorldChangeDead_01(const CEntityEvent &__eeInput);
	BOOL H0x01910018_WorldChangeDead_02(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_Death 0x01910019
	BOOL 
#line 24423 "C:/LC/Client/EntitiesMP/Player.es"
Death(const CEntityEvent &__eeInput);
	BOOL H0x0191001a_Death_01(const CEntityEvent &__eeInput);
	BOOL H0x0191001b_Death_02(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_TheEnd 0x0191001c
	BOOL 
#line 24617 "C:/LC/Client/EntitiesMP/Player.es"
TheEnd(const CEntityEvent &__eeInput);
	BOOL H0x0191001d_TheEnd_01(const CEntityEvent &__eeInput);
	BOOL H0x0191001e_TheEnd_02(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_FirstInit 0x0191001f
	BOOL 
#line 24671 "C:/LC/Client/EntitiesMP/Player.es"
FirstInit(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_Rebirth 0x01910020
	BOOL 
#line 24700 "C:/LC/Client/EntitiesMP/Player.es"
Rebirth(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_AutoGoToMarker 0x01910021
	BOOL 
#line 24744 "C:/LC/Client/EntitiesMP/Player.es"
AutoGoToMarker(const CEntityEvent &__eeInput);
	BOOL H0x01910022_AutoGoToMarker_01(const CEntityEvent &__eeInput);
	BOOL H0x01910023_AutoGoToMarker_02(const CEntityEvent &__eeInput);
	BOOL H0x01910024_AutoGoToMarker_03(const CEntityEvent &__eeInput);
	BOOL H0x01910025_AutoGoToMarker_04(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_AutoGoToMarkerAndStop 0x01910026
	BOOL 
#line 24776 "C:/LC/Client/EntitiesMP/Player.es"
AutoGoToMarkerAndStop(const CEntityEvent &__eeInput);
	BOOL H0x01910027_AutoGoToMarkerAndStop_01(const CEntityEvent &__eeInput);
	BOOL H0x01910028_AutoGoToMarkerAndStop_02(const CEntityEvent &__eeInput);
	BOOL H0x01910029_AutoGoToMarkerAndStop_03(const CEntityEvent &__eeInput);
	BOOL H0x0191002a_AutoGoToMarkerAndStop_04(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_AutoUseItem 0x0191002b
	BOOL 
#line 24816 "C:/LC/Client/EntitiesMP/Player.es"
AutoUseItem(const CEntityEvent &__eeInput);
	BOOL H0x0191002c_AutoUseItem_01(const CEntityEvent &__eeInput);
	BOOL H0x0191002d_AutoUseItem_02(const CEntityEvent &__eeInput);
	BOOL H0x0191002e_AutoUseItem_03(const CEntityEvent &__eeInput);
	BOOL H0x0191002f_AutoUseItem_04(const CEntityEvent &__eeInput);
	BOOL H0x01910030_AutoUseItem_05(const CEntityEvent &__eeInput);
	BOOL H0x01910031_AutoUseItem_06(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_AutoPickItem 0x01910032
	BOOL 
#line 24866 "C:/LC/Client/EntitiesMP/Player.es"
AutoPickItem(const CEntityEvent &__eeInput);
	BOOL H0x01910033_AutoPickItem_01(const CEntityEvent &__eeInput);
	BOOL H0x01910034_AutoPickItem_02(const CEntityEvent &__eeInput);
	BOOL H0x01910035_AutoPickItem_03(const CEntityEvent &__eeInput);
	BOOL H0x01910036_AutoPickItem_04(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_AutoFallDown 0x01910037
	BOOL 
#line 24902 "C:/LC/Client/EntitiesMP/Player.es"
AutoFallDown(const CEntityEvent &__eeInput);
	BOOL H0x01910038_AutoFallDown_01(const CEntityEvent &__eeInput);
	BOOL H0x01910039_AutoFallDown_02(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_AutoFallToAbys 0x0191003a
	BOOL 
#line 24914 "C:/LC/Client/EntitiesMP/Player.es"
AutoFallToAbys(const CEntityEvent &__eeInput);
	BOOL H0x0191003b_AutoFallToAbys_01(const CEntityEvent &__eeInput);
	BOOL H0x0191003c_AutoFallToAbys_02(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_AutoLookAround 0x0191003d
	BOOL 
#line 24927 "C:/LC/Client/EntitiesMP/Player.es"
AutoLookAround(const CEntityEvent &__eeInput);
	BOOL H0x0191003e_AutoLookAround_01(const CEntityEvent &__eeInput);
	BOOL H0x0191003f_AutoLookAround_02(const CEntityEvent &__eeInput);
	BOOL H0x01910040_AutoLookAround_03(const CEntityEvent &__eeInput);
	BOOL H0x01910041_AutoLookAround_04(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_AutoTeleport 0x01910042
	BOOL 
#line 24951 "C:/LC/Client/EntitiesMP/Player.es"
AutoTeleport(const CEntityEvent &__eeInput);
#define  STATE_CPlayer_DoAutoActions 0x01910043
	BOOL 
#line 24961 "C:/LC/Client/EntitiesMP/Player.es"
DoAutoActions(const CEntityEvent &__eeInput);
	BOOL H0x01910044_DoAutoActions_01(const CEntityEvent &__eeInput);
	BOOL H0x01910045_DoAutoActions_02(const CEntityEvent &__eeInput);
	BOOL H0x01910046_DoAutoActions_03(const CEntityEvent &__eeInput);
	BOOL H0x01910047_DoAutoActions_04(const CEntityEvent &__eeInput);
	BOOL H0x01910048_DoAutoActions_05(const CEntityEvent &__eeInput);
	BOOL H0x01910049_DoAutoActions_06(const CEntityEvent &__eeInput);
	BOOL H0x0191004a_DoAutoActions_07(const CEntityEvent &__eeInput);
	BOOL H0x0191004b_DoAutoActions_08(const CEntityEvent &__eeInput);
	BOOL H0x0191004c_DoAutoActions_09(const CEntityEvent &__eeInput);
	BOOL H0x0191004d_DoAutoActions_10(const CEntityEvent &__eeInput);
	BOOL H0x0191004e_DoAutoActions_11(const CEntityEvent &__eeInput);
	BOOL H0x0191004f_DoAutoActions_12(const CEntityEvent &__eeInput);
	BOOL H0x01910050_DoAutoActions_13(const CEntityEvent &__eeInput);
	BOOL H0x01910051_DoAutoActions_14(const CEntityEvent &__eeInput);
	BOOL H0x01910052_DoAutoActions_15(const CEntityEvent &__eeInput);
	BOOL H0x01910053_DoAutoActions_16(const CEntityEvent &__eeInput);
	BOOL H0x01910054_DoAutoActions_17(const CEntityEvent &__eeInput);
	BOOL H0x01910055_DoAutoActions_18(const CEntityEvent &__eeInput);
	BOOL H0x01910056_DoAutoActions_19(const CEntityEvent &__eeInput);
	BOOL H0x01910057_DoAutoActions_20(const CEntityEvent &__eeInput);
	BOOL H0x01910058_DoAutoActions_21(const CEntityEvent &__eeInput);
	BOOL H0x01910059_DoAutoActions_22(const CEntityEvent &__eeInput);
	BOOL H0x0191005a_DoAutoActions_23(const CEntityEvent &__eeInput);
	BOOL H0x0191005b_DoAutoActions_24(const CEntityEvent &__eeInput);
	BOOL H0x0191005c_DoAutoActions_25(const CEntityEvent &__eeInput);
	BOOL H0x0191005d_DoAutoActions_26(const CEntityEvent &__eeInput);
	BOOL H0x0191005e_DoAutoActions_27(const CEntityEvent &__eeInput);
	BOOL H0x0191005f_DoAutoActions_28(const CEntityEvent &__eeInput);
	BOOL H0x01910060_DoAutoActions_29(const CEntityEvent &__eeInput);
	BOOL H0x01910061_DoAutoActions_30(const CEntityEvent &__eeInput);
	BOOL H0x01910062_DoAutoActions_31(const CEntityEvent &__eeInput);
	BOOL H0x01910063_DoAutoActions_32(const CEntityEvent &__eeInput);
	BOOL H0x01910064_DoAutoActions_33(const CEntityEvent &__eeInput);
	BOOL H0x01910065_DoAutoActions_34(const CEntityEvent &__eeInput);
	BOOL H0x01910066_DoAutoActions_35(const CEntityEvent &__eeInput);
	BOOL H0x01910067_DoAutoActions_36(const CEntityEvent &__eeInput);
	BOOL H0x01910068_DoAutoActions_37(const CEntityEvent &__eeInput);
	BOOL H0x01910069_DoAutoActions_38(const CEntityEvent &__eeInput);
	BOOL H0x0191006a_DoAutoActions_39(const CEntityEvent &__eeInput);
	BOOL H0x0191006b_DoAutoActions_40(const CEntityEvent &__eeInput);
	BOOL H0x0191006c_DoAutoActions_41(const CEntityEvent &__eeInput);
	BOOL H0x0191006d_DoAutoActions_42(const CEntityEvent &__eeInput);
	BOOL H0x0191006e_DoAutoActions_43(const CEntityEvent &__eeInput);
	BOOL H0x0191006f_DoAutoActions_44(const CEntityEvent &__eeInput);
	BOOL H0x01910070_DoAutoActions_45(const CEntityEvent &__eeInput);
	BOOL H0x01910071_DoAutoActions_46(const CEntityEvent &__eeInput);
	BOOL H0x01910072_DoAutoActions_47(const CEntityEvent &__eeInput);
	BOOL H0x01910073_DoAutoActions_48(const CEntityEvent &__eeInput);
	BOOL H0x01910074_DoAutoActions_49(const CEntityEvent &__eeInput);
	BOOL H0x01910075_DoAutoActions_50(const CEntityEvent &__eeInput);
	BOOL H0x01910076_DoAutoActions_51(const CEntityEvent &__eeInput);
	BOOL H0x01910077_DoAutoActions_52(const CEntityEvent &__eeInput);
	BOOL H0x01910078_DoAutoActions_53(const CEntityEvent &__eeInput);
	BOOL H0x01910079_DoAutoActions_54(const CEntityEvent &__eeInput);
	BOOL H0x0191007a_DoAutoActions_55(const CEntityEvent &__eeInput);
	BOOL H0x0191007b_DoAutoActions_56(const CEntityEvent &__eeInput);
	BOOL H0x0191007c_DoAutoActions_57(const CEntityEvent &__eeInput);
	BOOL H0x0191007d_DoAutoActions_58(const CEntityEvent &__eeInput);
	BOOL H0x0191007e_DoAutoActions_59(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_Player_INCLUDED
