/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_SunMoon_INCLUDED
#define _EntitiesMP_SunMoon_INCLUDED 1
#include <EntitiesMP/Light.h>
#include <EntitiesMP/EnvironmentParticlesHolder.h>
#include <EntitiesMP/BackgroundViewer.h>
#include <EntitiesMP/WorldSettingsController.h>
#include <EntitiesMP/ModelHolder3.h>
#include <EntitiesMP/HazeMarker.h>
#include <EntitiesMP/FogMarker.h>
extern "C" DECL_DLL CDLLEntityClass CSunMoon_DLLClass;
class CSunMoon : public CMovableModelEntity {
public:
virtual BOOL IsTargetable(void) const { return TRUE; };
virtual const CTString &GetName(void) const { return m_strName; };
	DECL_DLL virtual void SetDefaultProperties(void);
	CTString m_strName;
	CEntityPointer m_epLight;
	CEntityPointer m_epSky;
	CEntityPointer m_epSkyHorizon;
	CEntityPointer m_epHaze;
	CEntityPointer m_epFog;
	FLOAT m_fLength;
	FLOAT m_fHeight;
	BOOL m_bWeatherSun;
	COLOR m_colRainAmbient;
	COLOR m_colHazeDefault;
	COLOR m_colFogDefault;
	BOOL m_bActive;
	enum LensFlareType m_lftSun;
	enum LensFlareType m_lftMoon;
	CTFileName m_fnmColAniFile;
	ANIMATION m_iSkyColAni;
	CAnimObject m_aoSkyColAni;
	CEntityPointer m_epSunModel;
	CEntityPointer m_epMoonModel;
	enum EventEType m_eetMorningEvent;
	enum EventEType m_eetEveningEvent;
	CEntityPointer m_epMorningTarget;
	CEntityPointer m_epEveningTarget;
	BOOL m_bNoon;
	BOOL m_bNight;
DOUBLE m_dPrevGWTime;
FLOAT m_fFadeTime;
FLOAT m_fAllFadeTime;
CLensFlareType * m_plftDefault;
   
#line 81 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
void InitModelHolder(void);
   
#line 99 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
BOOL IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget);
   
#line 128 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
CEnvironmentParticlesHolder * GetEPH();
   
#line 145 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
CLight * GetLight();
   
#line 153 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
CModelHolder3 * GetSky();
   
#line 161 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
CModelHolder3 * GetSkyHorizon();
   
#line 169 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
CHazeMarker * GetHaze();
   
#line 177 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
CFogMarker * GetFog();
   
#line 185 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
void SetSunModelColor(COLOR col);
   
#line 207 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
void SetMoonModelColor(COLOR col);
   
#line 230 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
void SetLensFlare(LensFlareType lft);
   
#line 281 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
COLOR GetCurrentSkyAniColor(COLOR colBase);
   
#line 299 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
COLOR GetCurrentSkyAniColor();
   
#line 303 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
CAnimData * GetAnimData(SLONG slPropertyOffset);
   
#line 315 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
void SetLightPlacement3D();
   
#line 378 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
void SetCurrentColor();
   
#line 434 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
void LightProcess();
#define  STATE_CSunMoon_Main 1
	BOOL 
#line 445 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
Main(const CEntityEvent &__eeInput);
#define  STATE_CSunMoon_FadeInRain 0x03e90000
	BOOL 
#line 516 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
FadeInRain(const CEntityEvent &__eeInput);
	BOOL H0x03e90001_FadeInRain_01(const CEntityEvent &__eeInput);
	BOOL H0x03e90002_FadeInRain_02(const CEntityEvent &__eeInput);
	BOOL H0x03e90003_FadeInRain_03(const CEntityEvent &__eeInput);
	BOOL H0x03e90004_FadeInRain_04(const CEntityEvent &__eeInput);
#define  STATE_CSunMoon_FadeOutRain 0x03e90005
	BOOL 
#line 543 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
FadeOutRain(const CEntityEvent &__eeInput);
	BOOL H0x03e90006_FadeOutRain_01(const CEntityEvent &__eeInput);
	BOOL H0x03e90007_FadeOutRain_02(const CEntityEvent &__eeInput);
	BOOL H0x03e90008_FadeOutRain_03(const CEntityEvent &__eeInput);
	BOOL H0x03e90009_FadeOutRain_04(const CEntityEvent &__eeInput);
#define  STATE_CSunMoon_GoodWeather 0x03e9000a
	BOOL 
#line 569 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
GoodWeather(const CEntityEvent &__eeInput);
	BOOL H0x03e9000b_GoodWeather_01(const CEntityEvent &__eeInput);
	BOOL H0x03e9000c_GoodWeather_02(const CEntityEvent &__eeInput);
	BOOL H0x03e9000d_GoodWeather_03(const CEntityEvent &__eeInput);
	BOOL H0x03e9000e_GoodWeather_04(const CEntityEvent &__eeInput);
#define  STATE_CSunMoon_MainLoop 0x03e9000f
	BOOL 
#line 584 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/SunMoon.es"
MainLoop(const CEntityEvent &__eeInput);
	BOOL H0x03e90010_MainLoop_01(const CEntityEvent &__eeInput);
	BOOL H0x03e90011_MainLoop_02(const CEntityEvent &__eeInput);
	BOOL H0x03e90012_MainLoop_03(const CEntityEvent &__eeInput);
	BOOL H0x03e90013_MainLoop_04(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_SunMoon_INCLUDED
