/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_Watcher_INCLUDED
#define _EntitiesMP_Watcher_INCLUDED 1
#define EVENTCODE_EWatcherInit 0x02bc0000
class DECL_DLL EWatcherInit : public CEntityEvent {
public:
	EWatcherInit();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	CEntityID eidOwner;
};
DECL_DLL inline void ClearToDefault(EWatcherInit &e) { e = EWatcherInit(); } ;
#define EVENTCODE_EWatch 0x02bc0001
class DECL_DLL EWatch : public CEntityEvent {
public:
	EWatch();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	CEntityID eidSeen;
};
DECL_DLL inline void ClearToDefault(EWatch &e) { e = EWatch(); } ;
extern "C" DECL_DLL CDLLEntityClass CWatcher_DLLClass;
class DECL_DLL  CWatcher : public CRationalEntity {
public:
virtual CEntity *GetPredictionPair(void) { return m_penPrediction; };
virtual void SetPredictionPair(CEntity *penPair) { m_penPrediction = penPair; };
virtual BOOL IsSentOverNet(void) const { return FALSE; };
	 virtual void SetDefaultProperties(void);
	CEntityPointer m_penOwner;
	FLOAT m_tmDelay;
	FLOAT m_fClosestPlayer;
	INDEX m_iPlayerToCheck;
	INDEX m_iOwnerID;
	CEntityPointer m_penPrediction;
   
#line 40 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
class CEnemyBase * GetOwner(void);
   
#line 48 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
INDEX GetRandomPlayer(void);
   
#line 128 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
CEntity * FindClosestPlayer(void);
   
#line 161 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
void SendWatchEvent(CEntity * penPlayer);
   
#line 168 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
void CheckIfPlayerVisible(void);
   
#line 219 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
void SetWatchDelays(void);
   
#line 245 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
void Watch(void);
   
#line 292 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
CEntity * CheckCloserPlayer(CEntity * penCurrentTarget,FLOAT fRange);
   
#line 386 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
CEntity * CheckAnotherPlayer(CEntity * penCurrentTarget);
   
#line 437 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
SLONG GetUsedMemory(void);
#define  STATE_CWatcher_Main 1
	BOOL 
#line 443 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
Main(const CEntityEvent &__eeInput);
	BOOL H0x02bc0002_Main_01(const CEntityEvent &__eeInput);
	BOOL H0x02bc0003_Main_02(const CEntityEvent &__eeInput);
#define  STATE_CWatcher_Active 0x02bc0004
	BOOL 
#line 484 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
Active(const CEntityEvent &__eeInput);
	BOOL H0x02bc0005_Active_01(const CEntityEvent &__eeInput);
	BOOL H0x02bc0006_Active_02(const CEntityEvent &__eeInput);
	BOOL H0x02bc0007_Active_03(const CEntityEvent &__eeInput);
	BOOL H0x02bc0008_Active_04(const CEntityEvent &__eeInput);
#define  STATE_CWatcher_Inactive 0x02bc0009
	BOOL 
#line 506 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
Inactive(const CEntityEvent &__eeInput);
	BOOL H0x02bc000a_Inactive_01(const CEntityEvent &__eeInput);
	BOOL H0x02bc000b_Inactive_02(const CEntityEvent &__eeInput);
#define  STATE_CWatcher_Dummy 0x02bc000c
	BOOL 
#line 516 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/Watcher.es"
Dummy(const CEntityEvent &__eeInput);
	BOOL H0x02bc000d_Dummy_01(const CEntityEvent &__eeInput);
	BOOL H0x02bc000e_Dummy_02(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_Watcher_INCLUDED
