/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_WildPetBase_INCLUDED
#define _EntitiesMP_WildPetBase_INCLUDED 1
#include <EntitiesMP/Player.h>
#include <EntitiesMP/BasicEffects.h>
#include <EntitiesMP/Projectile.h>
#include <EntitiesMP/Debris.h>
#include <EntitiesMP/EnemyMarker.h>
#include <EntitiesMP/MusicHolder.h>
#include <EntitiesMP/BloodSpray.h>
#include <EntitiesMP/Unit.h>
#define EVENTCODE_EWildPetBaseReconsiderBehavior 0x4c910000
class DECL_DLL EWildPetBaseReconsiderBehavior : public CEntityEvent {
public:
	EWildPetBaseReconsiderBehavior();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
};
DECL_DLL inline void ClearToDefault(EWildPetBaseReconsiderBehavior &e) { e = EWildPetBaseReconsiderBehavior(); } ;
#define EVENTCODE_EWildPetBaseDeath 0x4c910001
class DECL_DLL EWildPetBaseDeath : public CEntityEvent {
public:
	EWildPetBaseDeath();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	CEntityID eidInflictor;
};
DECL_DLL inline void ClearToDefault(EWildPetBaseDeath &e) { e = EWildPetBaseDeath(); } ;
#define EVENTCODE_EWildPetBaseDamage 0x4c910002
class DECL_DLL EWildPetBaseDamage : public CEntityEvent {
public:
	EWildPetBaseDamage();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
	CEntityID eidInflictor;
	FLOAT3D vDirection;
	FLOAT3D vHitPoint;
	FLOAT fAmount;
	enum DamageType dmtType;
	FLOAT fHealth;
};
DECL_DLL inline void ClearToDefault(EWildPetBaseDamage &e) { e = EWildPetBaseDamage(); } ;
extern "C" DECL_DLL CDLLEntityClass CWildPetBase_DLLClass;
class DECL_DLL  CWildPetBase : public CUnit {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
	 virtual void SetDefaultProperties(void);
	CEntityPointer m_penOwner;
	CEntityPointer m_penEnemy;
	CEntityPointer m_penKillEnemy;
	CEntityPointer m_penPathMarker;
	CEntityPointer m_penMarker;
	CEntityPointer m_penSpray;
	CEntityPointer m_penMainMusicHolder;
	CEntityPointer m_penPlayerOfEnemy;
	CEntityPointer m_penPetOfEnemy;
	CSoundObject m_WildPetSound;
	CTString m_strName;
	CTString m_strDescription;
	enum EventEType m_eeDeathType;
	enum SprayParticlesType m_sptType;
	enum wPetAIState m_wPetState;
	BOOL m_bFadeOut;
	BOOL m_bMoving;
	BOOL m_bStop;
	BOOL m_bAttack;
	BOOL m_bPreSkilling;
	FLOAT m_fFadeStartTime;
	FLOAT m_fFadeTime;
	FLOAT m_fRangeLast;
	FLOAT m_fTacticVar3;
	FLOAT m_fTacticVar4;
	FLOAT m_fTacticVar5;
	FLOAT m_fSpiritStartTime;
	FLOAT m_fAttackFrequency;
	FLOAT m_fAttackStartTime;
	FLOAT m_fImpactTime;
	FLOAT3D m_vLastStain;
	FLOAT3D m_vPlayerSpotted;
	FLOAT3D m_vTacticsStartPosition;
	INDEX m_nAttackCnt;
	COLOR m_colColor;
CSelectedEntities m_dcTargets;
    CWildPetBase(void);
  
#line 144 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void OnEnd(void);
  
#line 150 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void MovementAnimation(ULONG ulFlags);
   
#line 180 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL SetTargetEntity(CEntity * pen);
   
#line 197 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL SetEnemyEntity(CEntity * pen,int type);
   
#line 221 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void SetNoTargetEntity(void);
   
#line 226 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL SetKillTargetEntity(CEntity * penKill);
   
#line 232 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL CheckTarget(CEntity * penTarget);
   
#line 239 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void DeathNow();
   
#line 255 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void MoveNow();
   
#line 263 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void AttackNow();
   
#line 275 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void StopNow();
   
#line 286 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void SkillNow();
   
#line 297 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void PreSkillNow();
   
#line 308 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void ActionNow();
   
#line 319 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void SendActEvent();
   
#line 327 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void StopandTeleport();
   
#line 348 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmount,
#line 349 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 373 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void SetTargetNone(void);
   
#line 380 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL SetTargetItem(CEntity * pItem);
   
#line 393 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL SetTargetSoft(CEntity * penPlayer);
   
#line 418 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL SetTargetHard(CEntity * penPlayer);
   
#line 434 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL SetTargetHardForce(CEntity * penPlayer);
   void Copy(CEntity & enOther,ULONG ulFlags);
  
#line 456 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual FLOAT3D MyOwnerDestinationPos(void);
  
#line 465 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual FLOAT3D EnemyDestinationPos(void);
  
#line 474 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual FLOAT3D TargetDestinationPos(wPetAIState wpst);
  
#line 491 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual CEntity * GetTargetEntity(wPetAIState wpst);
   
#line 508 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
const CTString & GetDescription(void)const;
   
#line 520 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   
#line 555 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL ShouldCeaseAttack(void);
  
#line 570 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual FLOAT GetAttackMoveFrequency(FLOAT fEnemyDistance);
  
#line 575 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void SetSpeedsToDesiredPosition(const FLOAT3D & vPosDelta,FLOAT fPosDist,BOOL bGoingToPlayer);
   
#line 637 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL CanAttackEnemy(CEntity * penTarget,FLOAT fCosAngle);
   
#line 658 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL SeeEntity(CEntity * pen,FLOAT fCosAngle);
   
#line 668 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL SeeEntityInPlane(CEntity * pen,FLOAT fCosAngle);
  
#line 689 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void LeaveStain(BOOL bGrow);
   
#line 731 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void WoundedNotify(const EWildPetBaseDamage & eEBDamage);
   
#line 750 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void SeeNotify();
  
#line 767 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void ChargeAnim(void);
  
#line 768 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual INDEX AnimForDamage(FLOAT fDamage);
  
#line 769 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void BlowUpNotify(void);
  
#line 770 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual INDEX AnimForDeath(void);
  
#line 771 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual FLOAT WaitForDust(FLOAT3D & vStretch);
  
#line 772 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void DeathNotify(void);
  
#line 773 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void IdleSound(void);
  
#line 775 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void WoundSound(void);
  
#line 776 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void DeathSound(void);
  
#line 777 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual FLOAT GetLockRotationSpeed(void);
  
#line 778 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void AttackAnim(void);
  
#line 779 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void IdleLoop(void);
  
#line 780 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void StandUpAnim(void);
  
#line 781 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void AISearch();
   
#line 784 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void RenderParticles(void);
  
#line 802 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
virtual void EnemyPostInit(void);
   
#line 806 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL HandleEvent(const CEntityEvent & ee);
   
#line 851 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
FLOAT GetAnimLength(int iAnim);
   
#line 861 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
FLOAT GetCurrentAnimLength(void);
   
#line 871 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BOOL IsAnimFinished();
   
#line 880 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
FLOAT3D & GetModelStretch();
   
#line 890 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void StretchModel(FLOAT3D vStretch);
   
#line 900 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
void StretchSingleModel(FLOAT3D vStretch);
   
#line 910 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
SLONG GetUsedMemory(void);
#define  STATE_CWildPetBase_Main 1
	BOOL 
#line 986 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
Main(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_StopAttack 0x4c910003
	BOOL 
#line 999 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
StopAttack(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_InitializeAttack 0x4c910004
	BOOL 
#line 1011 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
InitializeAttack(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_WPetAction 0x4c910005
	BOOL 
#line 1033 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
WPetAction(const CEntityEvent &__eeInput);
	BOOL H0x4c910006_WPetAction_01(const CEntityEvent &__eeInput);
	BOOL H0x4c910007_WPetAction_02(const CEntityEvent &__eeInput);
	BOOL H0x4c910008_WPetAction_03(const CEntityEvent &__eeInput);
	BOOL H0x4c910009_WPetAction_04(const CEntityEvent &__eeInput);
	BOOL H0x4c91000a_WPetAction_05(const CEntityEvent &__eeInput);
	BOOL H0x4c91000b_WPetAction_06(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_PerFormWPet 0x4c91000c
	BOOL 
#line 1051 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
PerFormWPet(const CEntityEvent &__eeInput);
	BOOL H0x4c91000d_PerFormWPet_01(const CEntityEvent &__eeInput);
	BOOL H0x4c91000e_PerFormWPet_02(const CEntityEvent &__eeInput);
	BOOL H0x4c91000f_PerFormWPet_03(const CEntityEvent &__eeInput);
	BOOL H0x4c910010_PerFormWPet_04(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_FireOrHit 0x4c910011
	BOOL 
#line 1273 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
FireOrHit(const CEntityEvent &__eeInput);
	BOOL H0x4c910012_FireOrHit_01(const CEntityEvent &__eeInput);
	BOOL H0x4c910013_FireOrHit_02(const CEntityEvent &__eeInput);
	BOOL H0x4c910014_FireOrHit_03(const CEntityEvent &__eeInput);
	BOOL H0x4c910015_FireOrHit_04(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_Hit 0x4c910016
	BOOL 
#line 1307 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
Hit(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_Fire 0x4c910017
	BOOL 
#line 1313 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
Fire(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_BeWounded 0x4c910018
	BOOL 
#line 1325 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
BeWounded(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_Die 0x4c910019
	BOOL 
#line 1333 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
Die(const CEntityEvent &__eeInput);
	BOOL H0x4c91001a_Die_01(const CEntityEvent &__eeInput);
	BOOL H0x4c91001b_Die_02(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_Death 0x4c91001c
	BOOL 
#line 1388 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
Death(const CEntityEvent &__eeInput);
	BOOL H0x4c91001d_Death_01(const CEntityEvent &__eeInput);
	BOOL H0x4c91001e_Death_02(const CEntityEvent &__eeInput);
	BOOL H0x4c91001f_Death_03(const CEntityEvent &__eeInput);
	BOOL H0x4c910020_Death_04(const CEntityEvent &__eeInput);
	BOOL H0x4c910021_Death_05(const CEntityEvent &__eeInput);
	BOOL H0x4c910022_Death_06(const CEntityEvent &__eeInput);
	BOOL H0x4c910023_Death_07(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_DeathSequence 0x4c910024
	BOOL 
#line 1446 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
DeathSequence(const CEntityEvent &__eeInput);
	BOOL H0x4c910025_DeathSequence_01(const CEntityEvent &__eeInput);
	BOOL H0x4c910026_DeathSequence_02(const CEntityEvent &__eeInput);
	BOOL H0x4c910027_DeathSequence_03(const CEntityEvent &__eeInput);
	BOOL H0x4c910028_DeathSequence_04(const CEntityEvent &__eeInput);
	BOOL H0x4c910029_DeathSequence_05(const CEntityEvent &__eeInput);
	BOOL H0x4c91002a_DeathSequence_06(const CEntityEvent &__eeInput);
	BOOL H0x4c91002b_DeathSequence_07(const CEntityEvent &__eeInput);
	BOOL H0x4c91002c_DeathSequence_08(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_Active 0x4c91002d
	BOOL 
#line 1493 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
Active(const CEntityEvent &__eeInput);
	BOOL H0x4c91002e_Active_01(const CEntityEvent &__eeInput);
	BOOL H0x4c91002f_Active_02(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_PreMainLoop 0x4c910030
	BOOL 
#line 1654 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
PreMainLoop(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_MainLoop_internal 0x4c910031
	BOOL 
#line 1659 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
MainLoop_internal(const CEntityEvent &__eeInput);
	BOOL H0x4c910032_MainLoop_internal_01(const CEntityEvent &__eeInput);
	BOOL H0x4c910033_MainLoop_internal_02(const CEntityEvent &__eeInput);
	BOOL H0x4c910034_MainLoop_internal_03(const CEntityEvent &__eeInput);
	BOOL H0x4c910035_MainLoop_internal_04(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_MainLoop 0x4c910036
	BOOL 
#line 1697 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
MainLoop(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_StandardBehavior 0x4c910037
	BOOL 
#line 1705 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
StandardBehavior(const CEntityEvent &__eeInput);
	BOOL H0x4c910038_StandardBehavior_01(const CEntityEvent &__eeInput);
	BOOL H0x4c910039_StandardBehavior_02(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_AttackTarget 0x4c91003a
	BOOL 
#line 1742 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
AttackTarget(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_SkillingTarget 0x4c91003b
	BOOL 
#line 1747 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
SkillingTarget(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_SpellSkill 0x4c91003c
	BOOL 
#line 1752 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
SpellSkill(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_StopMovement 0x4c91003d
	BOOL 
#line 1757 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
StopMovement(const CEntityEvent &__eeInput);
#define  STATE_CWildPetBase_MovetoPoint 0x4c91003e
	BOOL 
#line 1770 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPetBase.es"
MovetoPoint(const CEntityEvent &__eeInput);
	BOOL H0x4c91003f_MovetoPoint_01(const CEntityEvent &__eeInput);
	BOOL H0x4c910040_MovetoPoint_02(const CEntityEvent &__eeInput);
	BOOL H0x4c910041_MovetoPoint_03(const CEntityEvent &__eeInput);
	BOOL H0x4c910042_MovetoPoint_04(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_WildPetBase_INCLUDED
