/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_WildPet_INCLUDED
#define _EntitiesMP_WildPet_INCLUDED 1
#include <EntitiesMP/WildPetBase.h>
#include <EntitiesMP/Global.h>
#include <EntitiesMP/BasicEffects.h>
#include <EntitiesMP/EnemyBase.h>
#include <EntitiesMP/Enemy.h>
#define EVENTCODE_EWildPetAttackDamage 0x4c900000
class DECL_DLL EWildPetAttackDamage : public CEntityEvent {
public:
	EWildPetAttackDamage();
	CEntityEvent *MakeCopy(void);
	BOOL CheckIDs(void);
	SLONG GetSizeOf(void);
};
DECL_DLL inline void ClearToDefault(EWildPetAttackDamage &e) { e = EWildPetAttackDamage(); } ;
extern "C" DECL_DLL CDLLEntityClass CWildPet_DLLClass;
class CWildPet : public CWildPetBase {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
	DECL_DLL virtual void SetDefaultProperties(void);
	FLOAT m_fBodyAnimTime;
	FLOAT m_fStretch;
	INDEX iAnimWildPet_Walk;
	INDEX iAnimWildPet_Idle1;
	INDEX iAnimWildPet_Idle2;
	INDEX iAnimWildPet_Run;
	INDEX iAnimWildPet_Death;
	INDEX iAnimWildPet_Damage;
	INDEX iAnimWildPet_Attack1;
	INDEX iAnimWildPet_Attack2;
	INDEX iAnimWildPet_NormalBox;
	INDEX iAnimWildPet_Hungry;
	INDEX iNetwarkID;
	INDEX iOwnerIndex;
	CPlacement3D plPetPlacement;
	INDEX iYLayer;
	INDEX sbAttributePos;
	INDEX iAttackAnim;
	CTString m_strName;
	FLOAT m_fActionAnimTime;
	enum EventType m_EventType;
	CEntityPointer m_penEventTarget;
	BOOL m_bIsRun;
	BOOL m_bDie;
	INDEX m_nSkillChack;
	BOOL m_bRove;
CEffectGroup * m_pSkillReadyEffect;
CStaticArray < FLOAT3D > m_aDeathItemPosDrop;
CStaticArray < CItemTarget > m_aDeathItemTargetDrop;
CStaticArray < void * > m_aDeathItemDataDrop;
CStaticArray < TagInfo > m_saLastEffectInfo;
INDEX m_nMagicAttackSequence;
sSkillEffectInfo m_SkillEffectInfo;
INDEX m_nEffectStep;
CPetAnimation m_PetAnimationIndices;
FLOAT m_fprevStretch;
BOOL m_bPlayAttackAnim;
FLOAT m_IdleStartTime;
   
#line 180 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
  
#line 203 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
virtual FLOAT GetLockRotationSpeed(void);
  
#line 209 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
virtual BOOL IsMovable();
  
#line 227 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
virtual BOOL IsAvailableRide();
   
#line 240 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void GetTargetDirection(FLOAT3D & vTargetPos,FLOAT3D & vDirection);
   
#line 275 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void OnInitialize(const CEntityEvent & eeInput);
   
#line 280 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void OnEnd(void);
   
#line 286 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void * GetEntityInfo(void);
   
#line 291 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void Precache(void);
  
#line 301 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
virtual BOOL IsWildPet(void)const;
   
#line 307 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void InflictDirectDamage(CEntity * penToDamage,CEntity * penInflictor,enum DamageType dmtType,
#line 308 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 408 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 409 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 430 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
INDEX AnimForDamage(FLOAT fDamage);
   
#line 457 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
INDEX AnimForDeath(void);
   
#line 471 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
FLOAT WaitForDust(FLOAT3D & vStretch);
   
#line 482 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void DeathNotify(void);
   
#line 494 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void ClickedEvent(void);
   
#line 502 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void StandingAnim(void);
   
#line 539 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void ActEventAnim(void);
   
#line 551 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void RunningAnim(void);
   
#line 560 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void WalkingAnim(void);
   
#line 576 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void HungryAnim(void);
  
#line 584 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
virtual BOOL UseSkill(int iSkillIndex);
   
#line 761 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void SkillAnim(INDEX iAnimIndex,DWORD dwFlag,float fSpeed);
   
#line 771 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void AttackAnim(void);
   
#line 802 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void RotatingAnim(void);
   
#line 815 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void EnemyPostInit(void);
   
#line 821 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void AISearch(void);
   
#line 888 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
FLOAT GetItemRange(int nset0);
   
#line 916 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
FLOAT GetItemPercent(int nset2);
   
#line 948 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
BOOL AIResult(FLOAT fRange,int nSet1,FLOAT fPercent,int nTargettype);
   
#line 1100 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void SearchNearItem(FLOAT fRange);
   
#line 1107 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
BOOL AISubChack(CEntity * pcurEnt,int nset1,FLOAT fset2);
   
#line 1186 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
void SkillAndAttackFire(int num);
#define  STATE_CWildPet_Main 1
	BOOL 
#line 1352 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
Main(const CEntityEvent &__eeInput);
#define  STATE_CWildPet_Fire 0x4c900001
	BOOL 
#line 1458 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
Fire(const CEntityEvent &__eeInput);
#define  STATE_CWildPet_Hit 0x4c900002
	BOOL 
#line 1463 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
Hit(const CEntityEvent &__eeInput);
	BOOL H0x4c900003_Hit_01(const CEntityEvent &__eeInput);
	BOOL H0x4c900004_Hit_02(const CEntityEvent &__eeInput);
#define  STATE_CWildPet_AttackTarget 0x4c900005
	BOOL 
#line 1470 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
AttackTarget(const CEntityEvent &__eeInput);
	BOOL H0x4c900006_AttackTarget_01(const CEntityEvent &__eeInput);
	BOOL H0x4c900007_AttackTarget_02(const CEntityEvent &__eeInput);
#define  STATE_CWildPet_SkillingTarget 0x4c900008
	BOOL 
#line 1543 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
SkillingTarget(const CEntityEvent &__eeInput);
	BOOL H0x4c900009_SkillingTarget_01(const CEntityEvent &__eeInput);
	BOOL H0x4c90000a_SkillingTarget_02(const CEntityEvent &__eeInput);
#define  STATE_CWildPet_SpellSkill 0x4c90000b
	BOOL 
#line 1560 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
SpellSkill(const CEntityEvent &__eeInput);
	BOOL H0x4c90000c_SpellSkill_01(const CEntityEvent &__eeInput);
	BOOL H0x4c90000d_SpellSkill_02(const CEntityEvent &__eeInput);
#define  STATE_CWildPet_PreSkillAnimation 0x4c90000e
	BOOL 
#line 1569 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
PreSkillAnimation(const CEntityEvent &__eeInput);
	BOOL H0x4c90000f_PreSkillAnimation_01(const CEntityEvent &__eeInput);
	BOOL H0x4c900010_PreSkillAnimation_02(const CEntityEvent &__eeInput);
	BOOL H0x4c900011_PreSkillAnimation_03(const CEntityEvent &__eeInput);
	BOOL H0x4c900012_PreSkillAnimation_04(const CEntityEvent &__eeInput);
#define  STATE_CWildPet_AttackAnimation 0x4c900013
	BOOL 
#line 1615 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
AttackAnimation(const CEntityEvent &__eeInput);
	BOOL H0x4c900014_AttackAnimation_01(const CEntityEvent &__eeInput);
	BOOL H0x4c900015_AttackAnimation_02(const CEntityEvent &__eeInput);
	BOOL H0x4c900016_AttackAnimation_03(const CEntityEvent &__eeInput);
	BOOL H0x4c900017_AttackAnimation_04(const CEntityEvent &__eeInput);
#define  STATE_CWildPet_SkillAnimation 0x4c900018
	BOOL 
#line 1743 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
SkillAnimation(const CEntityEvent &__eeInput);
	BOOL H0x4c900019_SkillAnimation_01(const CEntityEvent &__eeInput);
	BOOL H0x4c90001a_SkillAnimation_02(const CEntityEvent &__eeInput);
	BOOL H0x4c90001b_SkillAnimation_03(const CEntityEvent &__eeInput);
	BOOL H0x4c90001c_SkillAnimation_04(const CEntityEvent &__eeInput);
#define  STATE_CWildPet_SkillAndMagicAnimation 0x4c90001d
	BOOL 
#line 2100 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
SkillAndMagicAnimation(const CEntityEvent &__eeInput);
	BOOL H0x4c90001e_SkillAndMagicAnimation_01(const CEntityEvent &__eeInput);
	BOOL H0x4c90001f_SkillAndMagicAnimation_02(const CEntityEvent &__eeInput);
	BOOL H0x4c900020_SkillAndMagicAnimation_03(const CEntityEvent &__eeInput);
	BOOL H0x4c900021_SkillAndMagicAnimation_04(const CEntityEvent &__eeInput);
#define  STATE_CWildPet_NormalAttack 0x4c900022
	BOOL 
#line 2193 "D:/lc shit/MY ONLY SOURCE I NEED LC/dx9/Client/EntitiesMP/WildPet.es"
NormalAttack(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_WildPet_INCLUDED
