// Decompiled with JetBrains decompiler
// Type: LcDevPack_TeamDamonA.Tools.Lacaball_Editor
// Assembly: LcDevPack_TeamDamonA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: B13AD660-B9C7-4C88-A534-19FC9102A906
// Assembly location: C:\Users\westy\Desktop\my lc\LC_TOOLS\LCT\Debug\LcDevPack_TeamDamonA.exe

using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace LcDevPack_TeamDamonA.Tools
{
  public class Lacaball_Editor : Form
  {
    private IContainer components = (IContainer) null;
    private GroupBox groupBox1;
    private Button button5;
    private Button button4;
    private Button button3;
    private Button button1;
    private Button button2;
    private DataGridView dgItems;
    private DataGridViewImageColumn Column7;
    private DataGridViewTextBoxColumn GiftIndex;
    private DataGridViewTextBoxColumn ItemName;
    private DataGridViewTextBoxColumn Type;
    private DataGridViewTextBoxColumn GiftCount;
    private DataGridViewTextBoxColumn GiftProb;
    private DataGridViewTextBoxColumn GiftFlag;
    private DataGridViewTextBoxColumn ID;
    private GroupBox gbLeft;
    private GroupBox groupBox2;
    private DataGridView dataGridView1;
    private DataGridViewImageColumn dataGridViewImageColumn1;
    private DataGridViewTextBoxColumn dataGridViewTextBoxColumn1;
    private DataGridViewTextBoxColumn dataGridViewTextBoxColumn2;
    private DataGridViewTextBoxColumn dataGridViewTextBoxColumn3;
    private DataGridViewTextBoxColumn dataGridViewTextBoxColumn4;
    private DataGridViewTextBoxColumn dataGridViewTextBoxColumn5;
    private DataGridViewTextBoxColumn dataGridViewTextBoxColumn6;
    private DataGridViewTextBoxColumn dataGridViewTextBoxColumn7;
    private GroupBox groupBox3;
    private DataGridView dataGridView2;
    private DataGridViewTextBoxColumn ID2;
    private DataGridViewTextBoxColumn ItemName1;
    private DataGridViewTextBoxColumn ItemCount;
    private DataGridViewTextBoxColumn ItemMax;
    private DataGridViewTextBoxColumn ItemRemain;

    public Lacaball_Editor() => this.InitializeComponent();

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.groupBox1 = new GroupBox();
      this.button5 = new Button();
      this.button4 = new Button();
      this.button3 = new Button();
      this.button1 = new Button();
      this.button2 = new Button();
      this.dgItems = new DataGridView();
      this.Column7 = new DataGridViewImageColumn();
      this.GiftIndex = new DataGridViewTextBoxColumn();
      this.ItemName = new DataGridViewTextBoxColumn();
      this.Type = new DataGridViewTextBoxColumn();
      this.GiftCount = new DataGridViewTextBoxColumn();
      this.GiftProb = new DataGridViewTextBoxColumn();
      this.GiftFlag = new DataGridViewTextBoxColumn();
      this.ID = new DataGridViewTextBoxColumn();
      this.gbLeft = new GroupBox();
      this.groupBox2 = new GroupBox();
      this.dataGridView1 = new DataGridView();
      this.dataGridViewImageColumn1 = new DataGridViewImageColumn();
      this.dataGridViewTextBoxColumn1 = new DataGridViewTextBoxColumn();
      this.dataGridViewTextBoxColumn2 = new DataGridViewTextBoxColumn();
      this.dataGridViewTextBoxColumn3 = new DataGridViewTextBoxColumn();
      this.dataGridViewTextBoxColumn4 = new DataGridViewTextBoxColumn();
      this.dataGridViewTextBoxColumn5 = new DataGridViewTextBoxColumn();
      this.dataGridViewTextBoxColumn6 = new DataGridViewTextBoxColumn();
      this.dataGridViewTextBoxColumn7 = new DataGridViewTextBoxColumn();
      this.groupBox3 = new GroupBox();
      this.dataGridView2 = new DataGridView();
      this.ID2 = new DataGridViewTextBoxColumn();
      this.ItemName1 = new DataGridViewTextBoxColumn();
      this.ItemCount = new DataGridViewTextBoxColumn();
      this.ItemMax = new DataGridViewTextBoxColumn();
      this.ItemRemain = new DataGridViewTextBoxColumn();
      this.groupBox1.SuspendLayout();
      ((ISupportInitialize) this.dgItems).BeginInit();
      this.gbLeft.SuspendLayout();
      this.groupBox2.SuspendLayout();
      ((ISupportInitialize) this.dataGridView1).BeginInit();
      this.groupBox3.SuspendLayout();
      ((ISupportInitialize) this.dataGridView2).BeginInit();
      this.SuspendLayout();
      this.groupBox1.Controls.Add((Control) this.button5);
      this.groupBox1.Controls.Add((Control) this.button4);
      this.groupBox1.Controls.Add((Control) this.button3);
      this.groupBox1.Controls.Add((Control) this.button1);
      this.groupBox1.Controls.Add((Control) this.button2);
      this.groupBox1.Location = new Point(12, 12);
      this.groupBox1.Name = "groupBox1";
      this.groupBox1.Size = new Size(202, 55);
      this.groupBox1.TabIndex = 52;
      this.groupBox1.TabStop = false;
      this.groupBox1.Text = "Category";
      this.button5.FlatStyle = FlatStyle.Flat;
      this.button5.Location = new Point(158, 17);
      this.button5.Name = "button5";
      this.button5.Size = new Size(32, 32);
      this.button5.TabIndex = 49;
      this.button5.UseVisualStyleBackColor = true;
      this.button4.FlatStyle = FlatStyle.Flat;
      this.button4.Location = new Point(120, 17);
      this.button4.Name = "button4";
      this.button4.Size = new Size(32, 32);
      this.button4.TabIndex = 48;
      this.button4.UseVisualStyleBackColor = true;
      this.button3.FlatStyle = FlatStyle.Flat;
      this.button3.Location = new Point(44, 17);
      this.button3.Name = "button3";
      this.button3.Size = new Size(32, 32);
      this.button3.TabIndex = 47;
      this.button3.UseVisualStyleBackColor = true;
      this.button1.FlatStyle = FlatStyle.Flat;
      this.button1.Location = new Point(82, 17);
      this.button1.Name = "button1";
      this.button1.Size = new Size(32, 32);
      this.button1.TabIndex = 45;
      this.button1.UseVisualStyleBackColor = true;
      this.button2.FlatStyle = FlatStyle.Flat;
      this.button2.Location = new Point(6, 17);
      this.button2.Name = "button2";
      this.button2.Size = new Size(32, 32);
      this.button2.TabIndex = 46;
      this.button2.UseVisualStyleBackColor = true;
      this.dgItems.AllowUserToAddRows = false;
      this.dgItems.AllowUserToDeleteRows = false;
      this.dgItems.BackgroundColor = SystemColors.Control;
      this.dgItems.BorderStyle = BorderStyle.None;
      this.dgItems.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
      this.dgItems.Columns.AddRange((DataGridViewColumn) this.Column7, (DataGridViewColumn) this.GiftIndex, (DataGridViewColumn) this.ItemName, (DataGridViewColumn) this.Type, (DataGridViewColumn) this.GiftCount, (DataGridViewColumn) this.GiftProb, (DataGridViewColumn) this.GiftFlag, (DataGridViewColumn) this.ID);
      this.dgItems.EnableHeadersVisualStyles = false;
      this.dgItems.Location = new Point(1, 19);
      this.dgItems.Name = "dgItems";
      this.dgItems.RowHeadersVisible = false;
      this.dgItems.RowTemplate.Height = 32;
      this.dgItems.Size = new Size(675, 199);
      this.dgItems.TabIndex = 53;
      this.Column7.HeaderText = "";
      this.Column7.Name = "Column7";
      this.Column7.Width = 32;
      this.GiftIndex.HeaderText = "ID";
      this.GiftIndex.Name = "GiftIndex";
      this.GiftIndex.Width = 50;
      this.ItemName.HeaderText = "ItemName";
      this.ItemName.Name = "ItemName";
      this.ItemName.ReadOnly = true;
      this.ItemName.Width = 275;
      this.Type.HeaderText = "Type";
      this.Type.Name = "Type";
      this.Type.Visible = false;
      this.Type.Width = 75;
      this.GiftCount.HeaderText = "GiftCount";
      this.GiftCount.Name = "GiftCount";
      this.GiftProb.HeaderText = "GiftProb";
      this.GiftProb.Name = "GiftProb";
      this.GiftFlag.HeaderText = "GiftFlag";
      this.GiftFlag.Name = "GiftFlag";
      this.ID.HeaderText = "Index";
      this.ID.Name = "ID";
      this.ID.Visible = false;
      this.ID.Width = 60;
      this.gbLeft.Controls.Add((Control) this.dgItems);
      this.gbLeft.Location = new Point(18, 73);
      this.gbLeft.Name = "gbLeft";
      this.gbLeft.Size = new Size(681, 228);
      this.gbLeft.TabIndex = 54;
      this.gbLeft.TabStop = false;
      this.gbLeft.Text = "Left Lacaball";
      this.groupBox2.Controls.Add((Control) this.dataGridView1);
      this.groupBox2.Location = new Point(19, 307);
      this.groupBox2.Name = "groupBox2";
      this.groupBox2.Size = new Size(681, 228);
      this.groupBox2.TabIndex = 55;
      this.groupBox2.TabStop = false;
      this.groupBox2.Text = "Middle Lacaball";
      this.dataGridView1.AllowUserToAddRows = false;
      this.dataGridView1.AllowUserToDeleteRows = false;
      this.dataGridView1.BackgroundColor = SystemColors.Control;
      this.dataGridView1.BorderStyle = BorderStyle.None;
      this.dataGridView1.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
      this.dataGridView1.Columns.AddRange((DataGridViewColumn) this.dataGridViewImageColumn1, (DataGridViewColumn) this.dataGridViewTextBoxColumn1, (DataGridViewColumn) this.dataGridViewTextBoxColumn2, (DataGridViewColumn) this.dataGridViewTextBoxColumn3, (DataGridViewColumn) this.dataGridViewTextBoxColumn4, (DataGridViewColumn) this.dataGridViewTextBoxColumn5, (DataGridViewColumn) this.dataGridViewTextBoxColumn6, (DataGridViewColumn) this.dataGridViewTextBoxColumn7);
      this.dataGridView1.EnableHeadersVisualStyles = false;
      this.dataGridView1.Location = new Point(1, 19);
      this.dataGridView1.Name = "dataGridView1";
      this.dataGridView1.RowHeadersVisible = false;
      this.dataGridView1.RowTemplate.Height = 32;
      this.dataGridView1.Size = new Size(675, 199);
      this.dataGridView1.TabIndex = 53;
      this.dataGridViewImageColumn1.HeaderText = "";
      this.dataGridViewImageColumn1.Name = "dataGridViewImageColumn1";
      this.dataGridViewImageColumn1.Width = 32;
      this.dataGridViewTextBoxColumn1.HeaderText = "ID";
      this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
      this.dataGridViewTextBoxColumn1.Width = 50;
      this.dataGridViewTextBoxColumn2.HeaderText = "ItemName";
      this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
      this.dataGridViewTextBoxColumn2.ReadOnly = true;
      this.dataGridViewTextBoxColumn2.Width = 275;
      this.dataGridViewTextBoxColumn3.HeaderText = "Type";
      this.dataGridViewTextBoxColumn3.Name = "dataGridViewTextBoxColumn3";
      this.dataGridViewTextBoxColumn3.Visible = false;
      this.dataGridViewTextBoxColumn3.Width = 75;
      this.dataGridViewTextBoxColumn4.HeaderText = "GiftCount";
      this.dataGridViewTextBoxColumn4.Name = "dataGridViewTextBoxColumn4";
      this.dataGridViewTextBoxColumn5.HeaderText = "GiftProb";
      this.dataGridViewTextBoxColumn5.Name = "dataGridViewTextBoxColumn5";
      this.dataGridViewTextBoxColumn6.HeaderText = "GiftFlag";
      this.dataGridViewTextBoxColumn6.Name = "dataGridViewTextBoxColumn6";
      this.dataGridViewTextBoxColumn7.HeaderText = "Index";
      this.dataGridViewTextBoxColumn7.Name = "dataGridViewTextBoxColumn7";
      this.dataGridViewTextBoxColumn7.Visible = false;
      this.dataGridViewTextBoxColumn7.Width = 60;
      this.groupBox3.Controls.Add((Control) this.dataGridView2);
      this.groupBox3.Location = new Point(705, 73);
      this.groupBox3.Name = "groupBox3";
      this.groupBox3.Size = new Size(523, 228);
      this.groupBox3.TabIndex = 56;
      this.groupBox3.TabStop = false;
      this.groupBox3.Text = "Right Lacaball";
      this.dataGridView2.AllowUserToAddRows = false;
      this.dataGridView2.AllowUserToDeleteRows = false;
      this.dataGridView2.BackgroundColor = SystemColors.Control;
      this.dataGridView2.BorderStyle = BorderStyle.None;
      this.dataGridView2.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
      this.dataGridView2.Columns.AddRange((DataGridViewColumn) this.ID2, (DataGridViewColumn) this.ItemName1, (DataGridViewColumn) this.ItemCount, (DataGridViewColumn) this.ItemMax, (DataGridViewColumn) this.ItemRemain);
      this.dataGridView2.Location = new Point(6, 19);
      this.dataGridView2.Name = "dataGridView2";
      this.dataGridView2.RowHeadersVisible = false;
      this.dataGridView2.Size = new Size(497, 199);
      this.dataGridView2.TabIndex = 0;
      this.ID2.FillWeight = 50f;
      this.ID2.HeaderText = "ID";
      this.ID2.Name = "ID2";
      this.ID2.Width = 65;
      this.ItemName1.HeaderText = "ItemName";
      this.ItemName1.Name = "ItemName1";
      this.ItemName1.Width = 200;
      this.ItemCount.HeaderText = "ItemCount";
      this.ItemCount.Name = "ItemCount";
      this.ItemMax.HeaderText = "ItemMax";
      this.ItemMax.Name = "ItemMax";
      this.ItemMax.Width = 65;
      this.ItemRemain.HeaderText = "ItemRemain";
      this.ItemRemain.Name = "ItemRemain";
      this.ItemRemain.Width = 65;
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(1236, 573);
      this.Controls.Add((Control) this.groupBox3);
      this.Controls.Add((Control) this.groupBox2);
      this.Controls.Add((Control) this.gbLeft);
      this.Controls.Add((Control) this.groupBox1);
      this.Name = nameof (Lacaball_Editor);
      this.Text = nameof (Lacaball_Editor);
      this.groupBox1.ResumeLayout(false);
      ((ISupportInitialize) this.dgItems).EndInit();
      this.gbLeft.ResumeLayout(false);
      this.groupBox2.ResumeLayout(false);
      ((ISupportInitialize) this.dataGridView1).EndInit();
      this.groupBox3.ResumeLayout(false);
      ((ISupportInitialize) this.dataGridView2).EndInit();
      this.ResumeLayout(false);
    }
  }
}
