// Decompiled with JetBrains decompiler
// Type: LcDevPack_TeamDamonA.Tools.MassEditSeals
// Assembly: LcDevPack_TeamDamonA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: B13AD660-B9C7-4C88-A534-19FC9102A906
// Assembly location: C:\Users\westy\Desktop\my lc\LC_TOOLS\LCT\Debug\LcDevPack_TeamDamonA.exe

using LcDevPack_TeamDamonA.Properties;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace LcDevPack_TeamDamonA.Tools
{
  public class MassEditSeals : Form
  {
    private string Host = ItemEditor2.connection.Settings.SqlHost;
    private string User = ItemEditor2.connection.Settings.SqlUser;
    private string Password = ItemEditor2.connection.Settings.SqlPassword;
    private string Database = ItemEditor2.connection.Settings.SqlDatabase;
    private DatabaseHandle databaseHandle = new DatabaseHandle();
    private IContainer components = (IContainer) null;
    private GroupBox gbMassRareOption;
    public PictureBox pictureBox22;
    public PictureBox pictureBox21;
    public PictureBox pictureBox20;
    public PictureBox pictureBox19;
    public PictureBox pictureBox18;
    public PictureBox pictureBox17;
    public PictureBox pictureBox16;
    public PictureBox pictureBox15;
    public PictureBox pictureBox14;
    public PictureBox pictureBox13;
    private TextBox TbLevel9;
    private Label lbllevel9;
    private TextBox TbLevel8;
    private Label lbllevel8;
    private TextBox TbLevel7;
    private Label lbllevel7;
    private TextBox TbLevel6;
    private Label lbllevel6;
    private TextBox TbLevel5;
    private Label lbllevel5;
    private TextBox TbLevel4;
    private Label lbllevel4;
    private TextBox TbLevel3;
    private Label lbllevel3;
    private TextBox TbLevel2;
    private Label lbllevel2;
    private TextBox TbLevel1;
    private Label lbllevel1;
    private TextBox TbLevel0;
    private Label lbllevel0;
    private TextBox TbOption9;
    private Label lblOption9;
    private TextBox TbOption8;
    private Label lblOption8;
    private TextBox TbOption7;
    private Label lblOption7;
    private TextBox TbOption6;
    private Label lblOption6;
    private TextBox TbOption5;
    private Label lblOption5;
    private TextBox TbOption4;
    private Label lblOption4;
    private TextBox TbOption3;
    private Label lblOption3;
    private TextBox TbOption2;
    private Label lblOption2;
    private TextBox TbOption1;
    private Label lblOption1;
    private TextBox TbOption0;
    private Label lblOption0;
    private GroupBox GbRange;
    private Button btnTips;
    private Button btnUpdate;
    private TextBox tbRange2;
    private Label lblItemRange2;
    private TextBox tbRange1;
    private Label LblitemRange1;
    private Label lblNote1;
    private Label label1;
    private PictureBox PbSelectID2;
    private PictureBox PbSelectID1;
    private ToolTip toolTip1;

    public MassEditSeals() => this.InitializeComponent();

    private void btnTips_Click(object sender, EventArgs e)
    {
      switch (new Random().Next(1, 5))
      {
        case 1:
          int num1 = (int) MessageBox.Show("If you're dealing with rareoption items start with option 0 if not start with option 1");
          break;
        case 2:
          int num2 = (int) MessageBox.Show("Rare Options operate off a chance based off 10000 being 100%");
          break;
        case 3:
          int num3 = (int) MessageBox.Show("Option is a_type from t_option and level represents the value ");
          break;
        case 4:
          int num4 = (int) MessageBox.Show("The 7th slot is usually for weapon armor skills");
          break;
      }
    }

    private void btnSend_Click(object sender, EventArgs e)
    {
      if (this.TbOption0.Text != "" && this.TbLevel0.Text != "" && this.TbOption1.Text != "" && this.TbLevel1.Text != "" && this.TbOption2.Text != "" && this.TbLevel2.Text != "" && this.TbOption3.Text != "" && this.TbLevel3.Text != "" && this.TbOption4.Text != "" && this.TbLevel4.Text != "" && this.TbOption5.Text != "" && this.TbLevel5.Text != "" && this.TbOption6.Text != "" && this.TbLevel6.Text != "" && this.TbOption7.Text != "" && this.TbLevel7.Text != "" && this.TbOption8.Text != "" && this.TbLevel8.Text != "" && this.TbOption9.Text != "" && this.TbLevel9.Text != "" && this.tbRange1.Text != "" && this.tbRange2.Text != "")
      {
        this.databaseHandle.SendQueryMySql(this.Host, this.User, this.Password, this.Database, "UPDATE t_item SET a_rare_index_0 = '" + this.TbOption0.Text + "', a_rare_index_1 = '" + this.TbOption1.Text + "', a_rare_index_2 = '" + this.TbOption2.Text + "', a_rare_index_3 = '" + this.TbOption3.Text + "', a_rare_index_4 = '" + this.TbOption4.Text + "', a_rare_index_5 = '" + this.TbOption5.Text + "', a_rare_index_6 = '" + this.TbOption6.Text + "', a_rare_index_7 = '" + this.TbOption7.Text + "', a_rare_index_8 = '" + this.TbOption8.Text + "', a_rare_index_9 = '" + this.TbOption9.Text + "', " + "a_rare_prob_0 = '" + this.TbLevel0.Text + "', a_rare_prob_1 = '" + this.TbLevel1.Text + "', a_rare_prob_2 = '" + this.TbLevel2.Text + "', a_rare_prob_3 = '" + this.TbLevel3.Text + "', a_rare_prob_4 = '" + this.TbLevel4.Text + "', a_rare_prob_5 = '" + this.TbLevel5.Text + "', a_rare_prob_6 = '" + this.TbLevel6.Text + "', a_rare_prob_7 = '" + this.TbLevel7.Text + "', a_rare_prob_8 = '" + this.TbLevel8.Text + "', a_rare_prob_9 = '" + this.TbLevel9.Text + "' WHERE a_index BETWEEN  '" + this.tbRange1.Text + "'AND'" + this.tbRange2.Text + "';");
        int num = (int) new CustomMessage("Done :)").ShowDialog();
        this.Close();
      }
      else
      {
        if (!this.tbRange2.Text.Equals("") && !this.tbRange1.Text.Equals(""))
          return;
        int num = (int) new CustomMessage("Please Enter 2 Ranges of Numbers").ShowDialog();
      }
    }

    private void PbSelectID2_Click(object sender, EventArgs e)
    {
      ItemPicker itemPicker = new ItemPicker();
      if (itemPicker.ShowDialog() != DialogResult.OK)
        return;
      this.tbRange2.Text = Convert.ToString(itemPicker.ItemIndex);
    }

    private void PbSelectID1_Click(object sender, EventArgs e)
    {
      ItemPicker itemPicker = new ItemPicker();
      if (itemPicker.ShowDialog() != DialogResult.OK)
        return;
      this.tbRange1.Text = Convert.ToString(itemPicker.ItemIndex);
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.components = (IContainer) new System.ComponentModel.Container();
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (MassEditSeals));
      this.gbMassRareOption = new GroupBox();
      this.pictureBox22 = new PictureBox();
      this.pictureBox21 = new PictureBox();
      this.pictureBox20 = new PictureBox();
      this.pictureBox19 = new PictureBox();
      this.pictureBox18 = new PictureBox();
      this.pictureBox17 = new PictureBox();
      this.pictureBox16 = new PictureBox();
      this.pictureBox15 = new PictureBox();
      this.pictureBox14 = new PictureBox();
      this.pictureBox13 = new PictureBox();
      this.TbLevel9 = new TextBox();
      this.lbllevel9 = new Label();
      this.TbLevel8 = new TextBox();
      this.lbllevel8 = new Label();
      this.TbLevel7 = new TextBox();
      this.lbllevel7 = new Label();
      this.TbLevel6 = new TextBox();
      this.lbllevel6 = new Label();
      this.TbLevel5 = new TextBox();
      this.lbllevel5 = new Label();
      this.TbLevel4 = new TextBox();
      this.lbllevel4 = new Label();
      this.TbLevel3 = new TextBox();
      this.lbllevel3 = new Label();
      this.TbLevel2 = new TextBox();
      this.lbllevel2 = new Label();
      this.TbLevel1 = new TextBox();
      this.lbllevel1 = new Label();
      this.TbLevel0 = new TextBox();
      this.lbllevel0 = new Label();
      this.TbOption9 = new TextBox();
      this.lblOption9 = new Label();
      this.TbOption8 = new TextBox();
      this.lblOption8 = new Label();
      this.TbOption7 = new TextBox();
      this.lblOption7 = new Label();
      this.TbOption6 = new TextBox();
      this.lblOption6 = new Label();
      this.TbOption5 = new TextBox();
      this.lblOption5 = new Label();
      this.TbOption4 = new TextBox();
      this.lblOption4 = new Label();
      this.TbOption3 = new TextBox();
      this.lblOption3 = new Label();
      this.TbOption2 = new TextBox();
      this.lblOption2 = new Label();
      this.TbOption1 = new TextBox();
      this.lblOption1 = new Label();
      this.TbOption0 = new TextBox();
      this.lblOption0 = new Label();
      this.GbRange = new GroupBox();
      this.PbSelectID2 = new PictureBox();
      this.PbSelectID1 = new PictureBox();
      this.tbRange2 = new TextBox();
      this.lblItemRange2 = new Label();
      this.tbRange1 = new TextBox();
      this.LblitemRange1 = new Label();
      this.btnTips = new Button();
      this.btnUpdate = new Button();
      this.lblNote1 = new Label();
      this.label1 = new Label();
      this.toolTip1 = new ToolTip(this.components);
      this.gbMassRareOption.SuspendLayout();
      ((ISupportInitialize) this.pictureBox22).BeginInit();
      ((ISupportInitialize) this.pictureBox21).BeginInit();
      ((ISupportInitialize) this.pictureBox20).BeginInit();
      ((ISupportInitialize) this.pictureBox19).BeginInit();
      ((ISupportInitialize) this.pictureBox18).BeginInit();
      ((ISupportInitialize) this.pictureBox17).BeginInit();
      ((ISupportInitialize) this.pictureBox16).BeginInit();
      ((ISupportInitialize) this.pictureBox15).BeginInit();
      ((ISupportInitialize) this.pictureBox14).BeginInit();
      ((ISupportInitialize) this.pictureBox13).BeginInit();
      this.GbRange.SuspendLayout();
      ((ISupportInitialize) this.PbSelectID2).BeginInit();
      ((ISupportInitialize) this.PbSelectID1).BeginInit();
      this.SuspendLayout();
      this.gbMassRareOption.Controls.Add((Control) this.pictureBox22);
      this.gbMassRareOption.Controls.Add((Control) this.pictureBox21);
      this.gbMassRareOption.Controls.Add((Control) this.pictureBox20);
      this.gbMassRareOption.Controls.Add((Control) this.pictureBox19);
      this.gbMassRareOption.Controls.Add((Control) this.pictureBox18);
      this.gbMassRareOption.Controls.Add((Control) this.pictureBox17);
      this.gbMassRareOption.Controls.Add((Control) this.pictureBox16);
      this.gbMassRareOption.Controls.Add((Control) this.pictureBox15);
      this.gbMassRareOption.Controls.Add((Control) this.pictureBox14);
      this.gbMassRareOption.Controls.Add((Control) this.pictureBox13);
      this.gbMassRareOption.Controls.Add((Control) this.TbLevel9);
      this.gbMassRareOption.Controls.Add((Control) this.lbllevel9);
      this.gbMassRareOption.Controls.Add((Control) this.TbLevel8);
      this.gbMassRareOption.Controls.Add((Control) this.lbllevel8);
      this.gbMassRareOption.Controls.Add((Control) this.TbLevel7);
      this.gbMassRareOption.Controls.Add((Control) this.lbllevel7);
      this.gbMassRareOption.Controls.Add((Control) this.TbLevel6);
      this.gbMassRareOption.Controls.Add((Control) this.lbllevel6);
      this.gbMassRareOption.Controls.Add((Control) this.TbLevel5);
      this.gbMassRareOption.Controls.Add((Control) this.lbllevel5);
      this.gbMassRareOption.Controls.Add((Control) this.TbLevel4);
      this.gbMassRareOption.Controls.Add((Control) this.lbllevel4);
      this.gbMassRareOption.Controls.Add((Control) this.TbLevel3);
      this.gbMassRareOption.Controls.Add((Control) this.lbllevel3);
      this.gbMassRareOption.Controls.Add((Control) this.TbLevel2);
      this.gbMassRareOption.Controls.Add((Control) this.lbllevel2);
      this.gbMassRareOption.Controls.Add((Control) this.TbLevel1);
      this.gbMassRareOption.Controls.Add((Control) this.lbllevel1);
      this.gbMassRareOption.Controls.Add((Control) this.TbLevel0);
      this.gbMassRareOption.Controls.Add((Control) this.lbllevel0);
      this.gbMassRareOption.Controls.Add((Control) this.TbOption9);
      this.gbMassRareOption.Controls.Add((Control) this.lblOption9);
      this.gbMassRareOption.Controls.Add((Control) this.TbOption8);
      this.gbMassRareOption.Controls.Add((Control) this.lblOption8);
      this.gbMassRareOption.Controls.Add((Control) this.TbOption7);
      this.gbMassRareOption.Controls.Add((Control) this.lblOption7);
      this.gbMassRareOption.Controls.Add((Control) this.TbOption6);
      this.gbMassRareOption.Controls.Add((Control) this.lblOption6);
      this.gbMassRareOption.Controls.Add((Control) this.TbOption5);
      this.gbMassRareOption.Controls.Add((Control) this.lblOption5);
      this.gbMassRareOption.Controls.Add((Control) this.TbOption4);
      this.gbMassRareOption.Controls.Add((Control) this.lblOption4);
      this.gbMassRareOption.Controls.Add((Control) this.TbOption3);
      this.gbMassRareOption.Controls.Add((Control) this.lblOption3);
      this.gbMassRareOption.Controls.Add((Control) this.TbOption2);
      this.gbMassRareOption.Controls.Add((Control) this.lblOption2);
      this.gbMassRareOption.Controls.Add((Control) this.TbOption1);
      this.gbMassRareOption.Controls.Add((Control) this.lblOption1);
      this.gbMassRareOption.Controls.Add((Control) this.TbOption0);
      this.gbMassRareOption.Controls.Add((Control) this.lblOption0);
      this.gbMassRareOption.Location = new Point(12, 26);
      this.gbMassRareOption.Name = "gbMassRareOption";
      this.gbMassRareOption.Size = new Size(336, 286);
      this.gbMassRareOption.TabIndex = 1;
      this.gbMassRareOption.TabStop = false;
      this.gbMassRareOption.Text = "Rare Options";
      this.pictureBox22.BackgroundImageLayout = ImageLayout.Stretch;
      this.pictureBox22.Location = new Point(135, 254);
      this.pictureBox22.Name = "pictureBox22";
      this.pictureBox22.Size = new Size(22, 22);
      this.pictureBox22.TabIndex = 99;
      this.pictureBox22.TabStop = false;
      this.pictureBox21.BackgroundImageLayout = ImageLayout.Stretch;
      this.pictureBox21.Location = new Point(135, 228);
      this.pictureBox21.Name = "pictureBox21";
      this.pictureBox21.Size = new Size(22, 22);
      this.pictureBox21.TabIndex = 98;
      this.pictureBox21.TabStop = false;
      this.pictureBox20.BackgroundImageLayout = ImageLayout.Stretch;
      this.pictureBox20.Location = new Point(135, 202);
      this.pictureBox20.Name = "pictureBox20";
      this.pictureBox20.Size = new Size(22, 22);
      this.pictureBox20.TabIndex = 97;
      this.pictureBox20.TabStop = false;
      this.pictureBox19.BackgroundImageLayout = ImageLayout.Stretch;
      this.pictureBox19.Location = new Point(135, 175);
      this.pictureBox19.Name = "pictureBox19";
      this.pictureBox19.Size = new Size(22, 22);
      this.pictureBox19.TabIndex = 96;
      this.pictureBox19.TabStop = false;
      this.pictureBox18.BackgroundImageLayout = ImageLayout.Stretch;
      this.pictureBox18.Location = new Point(135, 149);
      this.pictureBox18.Name = "pictureBox18";
      this.pictureBox18.Size = new Size(22, 22);
      this.pictureBox18.TabIndex = 95;
      this.pictureBox18.TabStop = false;
      this.pictureBox17.BackgroundImageLayout = ImageLayout.Stretch;
      this.pictureBox17.Location = new Point(135, 123);
      this.pictureBox17.Name = "pictureBox17";
      this.pictureBox17.Size = new Size(22, 22);
      this.pictureBox17.TabIndex = 94;
      this.pictureBox17.TabStop = false;
      this.pictureBox16.BackgroundImageLayout = ImageLayout.Stretch;
      this.pictureBox16.Location = new Point(135, 97);
      this.pictureBox16.Name = "pictureBox16";
      this.pictureBox16.Size = new Size(22, 22);
      this.pictureBox16.TabIndex = 93;
      this.pictureBox16.TabStop = false;
      this.pictureBox15.BackgroundImageLayout = ImageLayout.Stretch;
      this.pictureBox15.Location = new Point(135, 71);
      this.pictureBox15.Name = "pictureBox15";
      this.pictureBox15.Size = new Size(22, 22);
      this.pictureBox15.TabIndex = 92;
      this.pictureBox15.TabStop = false;
      this.pictureBox14.BackgroundImageLayout = ImageLayout.Stretch;
      this.pictureBox14.Location = new Point(135, 45);
      this.pictureBox14.Name = "pictureBox14";
      this.pictureBox14.Size = new Size(22, 22);
      this.pictureBox14.TabIndex = 91;
      this.pictureBox14.TabStop = false;
      this.pictureBox13.BackgroundImageLayout = ImageLayout.Stretch;
      this.pictureBox13.Location = new Point(135, 19);
      this.pictureBox13.Name = "pictureBox13";
      this.pictureBox13.Size = new Size(22, 22);
      this.pictureBox13.TabIndex = 90;
      this.pictureBox13.TabStop = false;
      this.TbLevel9.BorderStyle = BorderStyle.FixedSingle;
      this.TbLevel9.Location = new Point(245, 257);
      this.TbLevel9.Name = "TbLevel9";
      this.TbLevel9.Size = new Size(61, 20);
      this.TbLevel9.TabIndex = 78;
      this.TbLevel9.Text = "0";
      this.toolTip1.SetToolTip((Control) this.TbLevel9, "Option Level/Rareoption Prob");
      this.lbllevel9.AutoSize = true;
      this.lbllevel9.Location = new Point(166, 259);
      this.lbllevel9.Name = "lbllevel9";
      this.lbllevel9.Size = new Size(73, 13);
      this.lbllevel9.TabIndex = 79;
      this.lbllevel9.Text = "Chance:Level";
      this.TbLevel8.BorderStyle = BorderStyle.FixedSingle;
      this.TbLevel8.Location = new Point(245, 231);
      this.TbLevel8.Name = "TbLevel8";
      this.TbLevel8.Size = new Size(61, 20);
      this.TbLevel8.TabIndex = 76;
      this.TbLevel8.Text = "0";
      this.toolTip1.SetToolTip((Control) this.TbLevel8, "Option Level/Rareoption Prob");
      this.lbllevel8.AutoSize = true;
      this.lbllevel8.Location = new Point(166, 233);
      this.lbllevel8.Name = "lbllevel8";
      this.lbllevel8.Size = new Size(73, 13);
      this.lbllevel8.TabIndex = 77;
      this.lbllevel8.Text = "Chance:Level";
      this.TbLevel7.BorderStyle = BorderStyle.FixedSingle;
      this.TbLevel7.Location = new Point(245, 205);
      this.TbLevel7.Name = "TbLevel7";
      this.TbLevel7.Size = new Size(61, 20);
      this.TbLevel7.TabIndex = 74;
      this.TbLevel7.Text = "0";
      this.toolTip1.SetToolTip((Control) this.TbLevel7, "Option Level/Rareoption Prob");
      this.lbllevel7.AutoSize = true;
      this.lbllevel7.Location = new Point(166, 207);
      this.lbllevel7.Name = "lbllevel7";
      this.lbllevel7.Size = new Size(73, 13);
      this.lbllevel7.TabIndex = 75;
      this.lbllevel7.Text = "Chance:Level";
      this.TbLevel6.BorderStyle = BorderStyle.FixedSingle;
      this.TbLevel6.Location = new Point(245, 179);
      this.TbLevel6.Name = "TbLevel6";
      this.TbLevel6.Size = new Size(61, 20);
      this.TbLevel6.TabIndex = 72;
      this.TbLevel6.Text = "0";
      this.toolTip1.SetToolTip((Control) this.TbLevel6, "Option Level/Rareoption Prob");
      this.lbllevel6.AutoSize = true;
      this.lbllevel6.Location = new Point(166, 181);
      this.lbllevel6.Name = "lbllevel6";
      this.lbllevel6.Size = new Size(73, 13);
      this.lbllevel6.TabIndex = 73;
      this.lbllevel6.Text = "Chance:Level";
      this.TbLevel5.BorderStyle = BorderStyle.FixedSingle;
      this.TbLevel5.Location = new Point(245, 153);
      this.TbLevel5.Name = "TbLevel5";
      this.TbLevel5.Size = new Size(61, 20);
      this.TbLevel5.TabIndex = 70;
      this.TbLevel5.Text = "0";
      this.toolTip1.SetToolTip((Control) this.TbLevel5, "Option Level/Rareoption Prob");
      this.lbllevel5.AutoSize = true;
      this.lbllevel5.Location = new Point(166, 155);
      this.lbllevel5.Name = "lbllevel5";
      this.lbllevel5.Size = new Size(73, 13);
      this.lbllevel5.TabIndex = 71;
      this.lbllevel5.Text = "Chance:Level";
      this.TbLevel4.BorderStyle = BorderStyle.FixedSingle;
      this.TbLevel4.Location = new Point(245, 126);
      this.TbLevel4.Name = "TbLevel4";
      this.TbLevel4.Size = new Size(61, 20);
      this.TbLevel4.TabIndex = 68;
      this.TbLevel4.Text = "0";
      this.toolTip1.SetToolTip((Control) this.TbLevel4, "Option Level/Rareoption Prob");
      this.lbllevel4.AutoSize = true;
      this.lbllevel4.Location = new Point(166, 131);
      this.lbllevel4.Name = "lbllevel4";
      this.lbllevel4.Size = new Size(73, 13);
      this.lbllevel4.TabIndex = 69;
      this.lbllevel4.Text = "Chance:Level";
      this.TbLevel3.BorderStyle = BorderStyle.FixedSingle;
      this.TbLevel3.Location = new Point(245, 98);
      this.TbLevel3.Name = "TbLevel3";
      this.TbLevel3.Size = new Size(61, 20);
      this.TbLevel3.TabIndex = 66;
      this.TbLevel3.Text = "0";
      this.toolTip1.SetToolTip((Control) this.TbLevel3, "Option Level/Rareoption Prob");
      this.lbllevel3.AutoSize = true;
      this.lbllevel3.Location = new Point(166, 100);
      this.lbllevel3.Name = "lbllevel3";
      this.lbllevel3.Size = new Size(73, 13);
      this.lbllevel3.TabIndex = 67;
      this.lbllevel3.Text = "Chance:Level";
      this.TbLevel2.BorderStyle = BorderStyle.FixedSingle;
      this.TbLevel2.Location = new Point(245, 72);
      this.TbLevel2.Name = "TbLevel2";
      this.TbLevel2.Size = new Size(61, 20);
      this.TbLevel2.TabIndex = 64;
      this.TbLevel2.Text = "0";
      this.toolTip1.SetToolTip((Control) this.TbLevel2, "Option Level/Rareoption Prob");
      this.lbllevel2.AutoSize = true;
      this.lbllevel2.Location = new Point(166, 74);
      this.lbllevel2.Name = "lbllevel2";
      this.lbllevel2.Size = new Size(73, 13);
      this.lbllevel2.TabIndex = 65;
      this.lbllevel2.Text = "Chance:Level";
      this.TbLevel1.BorderStyle = BorderStyle.FixedSingle;
      this.TbLevel1.Location = new Point(245, 46);
      this.TbLevel1.Name = "TbLevel1";
      this.TbLevel1.Size = new Size(61, 20);
      this.TbLevel1.TabIndex = 62;
      this.TbLevel1.Text = "0";
      this.toolTip1.SetToolTip((Control) this.TbLevel1, "Option Level/Rareoption Prob");
      this.lbllevel1.AutoSize = true;
      this.lbllevel1.Location = new Point(166, 48);
      this.lbllevel1.Name = "lbllevel1";
      this.lbllevel1.Size = new Size(73, 13);
      this.lbllevel1.TabIndex = 63;
      this.lbllevel1.Text = "Chance:Level";
      this.TbLevel0.BorderStyle = BorderStyle.FixedSingle;
      this.TbLevel0.Location = new Point(245, 20);
      this.TbLevel0.Name = "TbLevel0";
      this.TbLevel0.Size = new Size(61, 20);
      this.TbLevel0.TabIndex = 60;
      this.TbLevel0.Text = "0";
      this.toolTip1.SetToolTip((Control) this.TbLevel0, "Option Level/Rareoption Prob");
      this.lbllevel0.AutoSize = true;
      this.lbllevel0.Location = new Point(165, 22);
      this.lbllevel0.Name = "lbllevel0";
      this.lbllevel0.Size = new Size(73, 13);
      this.lbllevel0.TabIndex = 61;
      this.lbllevel0.Text = "Chance:Level";
      this.TbOption9.BorderStyle = BorderStyle.FixedSingle;
      this.TbOption9.Location = new Point(68, (int) byte.MaxValue);
      this.TbOption9.Name = "TbOption9";
      this.TbOption9.Size = new Size(61, 20);
      this.TbOption9.TabIndex = 58;
      this.TbOption9.Text = "-1";
      this.toolTip1.SetToolTip((Control) this.TbOption9, "Option Index/Rareoption Index");
      this.lblOption9.AutoSize = true;
      this.lblOption9.Location = new Point(15, 257);
      this.lblOption9.Name = "lblOption9";
      this.lblOption9.Size = new Size(47, 13);
      this.lblOption9.TabIndex = 59;
      this.lblOption9.Text = "Option9:";
      this.TbOption8.BorderStyle = BorderStyle.FixedSingle;
      this.TbOption8.Location = new Point(68, 229);
      this.TbOption8.Name = "TbOption8";
      this.TbOption8.Size = new Size(61, 20);
      this.TbOption8.TabIndex = 56;
      this.TbOption8.Text = "-1";
      this.toolTip1.SetToolTip((Control) this.TbOption8, "Option Index/Rareoption Index");
      this.lblOption8.AutoSize = true;
      this.lblOption8.Location = new Point(15, 231);
      this.lblOption8.Name = "lblOption8";
      this.lblOption8.Size = new Size(47, 13);
      this.lblOption8.TabIndex = 57;
      this.lblOption8.Text = "Option8:";
      this.TbOption7.BorderStyle = BorderStyle.FixedSingle;
      this.TbOption7.Location = new Point(68, 203);
      this.TbOption7.Name = "TbOption7";
      this.TbOption7.Size = new Size(61, 20);
      this.TbOption7.TabIndex = 54;
      this.TbOption7.Text = "-1";
      this.toolTip1.SetToolTip((Control) this.TbOption7, "Option Index/Rareoption Index");
      this.lblOption7.AutoSize = true;
      this.lblOption7.Location = new Point(15, 205);
      this.lblOption7.Name = "lblOption7";
      this.lblOption7.Size = new Size(47, 13);
      this.lblOption7.TabIndex = 55;
      this.lblOption7.Text = "Option7:";
      this.TbOption6.BorderStyle = BorderStyle.FixedSingle;
      this.TbOption6.Location = new Point(68, 177);
      this.TbOption6.Name = "TbOption6";
      this.TbOption6.Size = new Size(61, 20);
      this.TbOption6.TabIndex = 52;
      this.TbOption6.Text = "-1";
      this.toolTip1.SetToolTip((Control) this.TbOption6, "Option Index/Rareoption Index");
      this.lblOption6.AutoSize = true;
      this.lblOption6.Location = new Point(15, 179);
      this.lblOption6.Name = "lblOption6";
      this.lblOption6.Size = new Size(47, 13);
      this.lblOption6.TabIndex = 53;
      this.lblOption6.Text = "Option6:";
      this.TbOption5.BorderStyle = BorderStyle.FixedSingle;
      this.TbOption5.Location = new Point(68, 151);
      this.TbOption5.Name = "TbOption5";
      this.TbOption5.Size = new Size(61, 20);
      this.TbOption5.TabIndex = 50;
      this.TbOption5.Text = "-1";
      this.toolTip1.SetToolTip((Control) this.TbOption5, "Option Index/Rareoption Index");
      this.lblOption5.AutoSize = true;
      this.lblOption5.Location = new Point(15, 153);
      this.lblOption5.Name = "lblOption5";
      this.lblOption5.Size = new Size(47, 13);
      this.lblOption5.TabIndex = 51;
      this.lblOption5.Text = "Option5:";
      this.TbOption4.BorderStyle = BorderStyle.FixedSingle;
      this.TbOption4.Location = new Point(68, 124);
      this.TbOption4.Name = "TbOption4";
      this.TbOption4.Size = new Size(61, 20);
      this.TbOption4.TabIndex = 48;
      this.TbOption4.Text = "-1";
      this.toolTip1.SetToolTip((Control) this.TbOption4, "Option Index/Rareoption Index");
      this.lblOption4.AutoSize = true;
      this.lblOption4.Location = new Point(15, 126);
      this.lblOption4.Name = "lblOption4";
      this.lblOption4.Size = new Size(47, 13);
      this.lblOption4.TabIndex = 49;
      this.lblOption4.Text = "Option4:";
      this.TbOption3.BorderStyle = BorderStyle.FixedSingle;
      this.TbOption3.Location = new Point(68, 98);
      this.TbOption3.Name = "TbOption3";
      this.TbOption3.Size = new Size(61, 20);
      this.TbOption3.TabIndex = 46;
      this.TbOption3.Text = "-1";
      this.toolTip1.SetToolTip((Control) this.TbOption3, "Option Index/Rareoption Index");
      this.lblOption3.AutoSize = true;
      this.lblOption3.Location = new Point(15, 100);
      this.lblOption3.Name = "lblOption3";
      this.lblOption3.Size = new Size(47, 13);
      this.lblOption3.TabIndex = 47;
      this.lblOption3.Text = "Option3:";
      this.TbOption2.BorderStyle = BorderStyle.FixedSingle;
      this.TbOption2.Location = new Point(68, 72);
      this.TbOption2.Name = "TbOption2";
      this.TbOption2.Size = new Size(61, 20);
      this.TbOption2.TabIndex = 44;
      this.TbOption2.Text = "-1";
      this.toolTip1.SetToolTip((Control) this.TbOption2, "Option Index/Rareoption Index");
      this.lblOption2.AutoSize = true;
      this.lblOption2.Location = new Point(15, 74);
      this.lblOption2.Name = "lblOption2";
      this.lblOption2.Size = new Size(47, 13);
      this.lblOption2.TabIndex = 45;
      this.lblOption2.Text = "Option2:";
      this.TbOption1.BorderStyle = BorderStyle.FixedSingle;
      this.TbOption1.Location = new Point(68, 46);
      this.TbOption1.Name = "TbOption1";
      this.TbOption1.Size = new Size(61, 20);
      this.TbOption1.TabIndex = 42;
      this.TbOption1.Text = "-1";
      this.toolTip1.SetToolTip((Control) this.TbOption1, "Option Index/Rareoption Index");
      this.lblOption1.AutoSize = true;
      this.lblOption1.Location = new Point(15, 48);
      this.lblOption1.Name = "lblOption1";
      this.lblOption1.Size = new Size(47, 13);
      this.lblOption1.TabIndex = 43;
      this.lblOption1.Text = "Option1:";
      this.TbOption0.BorderStyle = BorderStyle.FixedSingle;
      this.TbOption0.Location = new Point(68, 20);
      this.TbOption0.Name = "TbOption0";
      this.TbOption0.Size = new Size(61, 20);
      this.TbOption0.TabIndex = 40;
      this.TbOption0.Text = "-1";
      this.toolTip1.SetToolTip((Control) this.TbOption0, "Option Index/Rareoption Index");
      this.lblOption0.AutoSize = true;
      this.lblOption0.Location = new Point(15, 22);
      this.lblOption0.Name = "lblOption0";
      this.lblOption0.Size = new Size(47, 13);
      this.lblOption0.TabIndex = 41;
      this.lblOption0.Text = "Option0:";
      this.GbRange.Controls.Add((Control) this.PbSelectID2);
      this.GbRange.Controls.Add((Control) this.PbSelectID1);
      this.GbRange.Controls.Add((Control) this.tbRange2);
      this.GbRange.Controls.Add((Control) this.lblItemRange2);
      this.GbRange.Controls.Add((Control) this.tbRange1);
      this.GbRange.Controls.Add((Control) this.LblitemRange1);
      this.GbRange.Location = new Point(354, 30);
      this.GbRange.Name = "GbRange";
      this.GbRange.Size = new Size(138, 282);
      this.GbRange.TabIndex = 2;
      this.GbRange.TabStop = false;
      this.GbRange.Text = "Range";
      this.PbSelectID2.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbSelectID2.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbSelectID2.Location = new Point(113, 91);
      this.PbSelectID2.Name = "PbSelectID2";
      this.PbSelectID2.Size = new Size(22, 22);
      this.PbSelectID2.TabIndex = 104;
      this.PbSelectID2.TabStop = false;
      this.PbSelectID2.Click += new EventHandler(this.PbSelectID2_Click);
      this.PbSelectID1.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbSelectID1.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbSelectID1.Location = new Point(111, 42);
      this.PbSelectID1.Name = "PbSelectID1";
      this.PbSelectID1.Size = new Size(22, 22);
      this.PbSelectID1.TabIndex = 103;
      this.PbSelectID1.TabStop = false;
      this.PbSelectID1.Click += new EventHandler(this.PbSelectID1_Click);
      this.tbRange2.BorderStyle = BorderStyle.FixedSingle;
      this.tbRange2.Location = new Point(9, 93);
      this.tbRange2.Name = "tbRange2";
      this.tbRange2.Size = new Size(98, 20);
      this.tbRange2.TabIndex = 102;
      this.toolTip1.SetToolTip((Control) this.tbRange2, "End Index");
      this.lblItemRange2.AutoSize = true;
      this.lblItemRange2.Location = new Point(9, 68);
      this.lblItemRange2.Name = "lblItemRange2";
      this.lblItemRange2.Size = new Size(88, 13);
      this.lblItemRange2.TabIndex = 101;
      this.lblItemRange2.Text = "Item ID Range 2:";
      this.tbRange1.BorderStyle = BorderStyle.FixedSingle;
      this.tbRange1.Location = new Point(9, 43);
      this.tbRange1.Name = "tbRange1";
      this.tbRange1.Size = new Size(98, 20);
      this.tbRange1.TabIndex = 100;
      this.toolTip1.SetToolTip((Control) this.tbRange1, "Start Index");
      this.LblitemRange1.AutoSize = true;
      this.LblitemRange1.Location = new Point(9, 23);
      this.LblitemRange1.Name = "LblitemRange1";
      this.LblitemRange1.Size = new Size(88, 13);
      this.LblitemRange1.TabIndex = 0;
      this.LblitemRange1.Text = "Item ID Range 1:";
      this.btnTips.Location = new Point(44, 318);
      this.btnTips.Name = "btnTips";
      this.btnTips.Size = new Size(107, 23);
      this.btnTips.TabIndex = 3;
      this.btnTips.Text = "Tips";
      this.btnTips.UseVisualStyleBackColor = true;
      this.btnTips.Click += new EventHandler(this.btnTips_Click);
      this.btnUpdate.Location = new Point(180, 318);
      this.btnUpdate.Name = "btnUpdate";
      this.btnUpdate.Size = new Size(107, 23);
      this.btnUpdate.TabIndex = 4;
      this.btnUpdate.Text = "Update";
      this.btnUpdate.UseVisualStyleBackColor = true;
      this.btnUpdate.Click += new EventHandler(this.btnSend_Click);
      this.lblNote1.AutoSize = true;
      this.lblNote1.ForeColor = SystemColors.ControlText;
      this.lblNote1.Location = new Point(13, 7);
      this.lblNote1.Name = "lblNote1";
      this.lblNote1.Size = new Size(275, 13);
      this.lblNote1.TabIndex = 5;
      this.lblNote1.Text = "Note: check the range of items for items that dont belong";
      this.label1.AutoSize = true;
      this.label1.Location = new Point(294, 7);
      this.label1.Name = "label1";
      this.label1.Size = new Size(141, 13);
      this.label1.TabIndex = 6;
      this.label1.Text = "Note2: must fill all boxes out.";
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(499, 342);
      this.Controls.Add((Control) this.label1);
      this.Controls.Add((Control) this.lblNote1);
      this.Controls.Add((Control) this.btnUpdate);
      this.Controls.Add((Control) this.btnTips);
      this.Controls.Add((Control) this.GbRange);
      this.Controls.Add((Control) this.gbMassRareOption);
      this.FormBorderStyle = FormBorderStyle.Fixed3D;
      this.Icon = (Icon) componentResourceManager.GetObject("$this.Icon");
      this.MaximizeBox = false;
      this.MinimizeBox = false;
      this.Name = nameof (MassEditSeals);
      this.StartPosition = FormStartPosition.CenterParent;
      this.Text = "MassEdit Seals";
      this.gbMassRareOption.ResumeLayout(false);
      this.gbMassRareOption.PerformLayout();
      ((ISupportInitialize) this.pictureBox22).EndInit();
      ((ISupportInitialize) this.pictureBox21).EndInit();
      ((ISupportInitialize) this.pictureBox20).EndInit();
      ((ISupportInitialize) this.pictureBox19).EndInit();
      ((ISupportInitialize) this.pictureBox18).EndInit();
      ((ISupportInitialize) this.pictureBox17).EndInit();
      ((ISupportInitialize) this.pictureBox16).EndInit();
      ((ISupportInitialize) this.pictureBox15).EndInit();
      ((ISupportInitialize) this.pictureBox14).EndInit();
      ((ISupportInitialize) this.pictureBox13).EndInit();
      this.GbRange.ResumeLayout(false);
      this.GbRange.PerformLayout();
      ((ISupportInitialize) this.PbSelectID2).EndInit();
      ((ISupportInitialize) this.PbSelectID1).EndInit();
      this.ResumeLayout(false);
      this.PerformLayout();
    }
  }
}
