// Decompiled with JetBrains decompiler
// Type: LcDevPack_TeamDamonA.Tools.MobMassEdit
// Assembly: LcDevPack_TeamDamonA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: B13AD660-B9C7-4C88-A534-19FC9102A906
// Assembly location: C:\Users\westy\Desktop\my lc\LC_TOOLS\LCT\Debug\LcDevPack_TeamDamonA.exe

using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace LcDevPack_TeamDamonA.Tools
{
  public class MobMassEdit : Form
  {
    private string Host = MobEditor.connection.Settings.SqlHost;
    private string User = MobEditor.connection.Settings.SqlUser;
    private string Password = MobEditor.connection.Settings.SqlPassword;
    private string Database = MobEditor.connection.Settings.SqlDatabase;
    private DatabaseHandle databaseHandle = new DatabaseHandle();
    private IContainer components = (IContainer) null;
    private CheckedListBox ClbMob;
    private Label lblName;
    private TextBox TbHP;
    private Label lblHP;
    private Label lblFlag;
    private TextBox TbFlag;
    private Label lblAttack;
    private TextBox TbAttack;
    private Label lblDefense;
    private TextBox TbDefense;
    private Label lblHit;
    private TextBox TbHit;
    private Label lblRecoverHP;
    private TextBox TbRecoverHP;
    private Label lblMP;
    private TextBox TbMP;
    private Label lblStateFlag;
    private TextBox TbStateFlag;
    private Label lblMAttack;
    private TextBox TbMagicAttack;
    private Label lblMagicDef;
    private TextBox TbMagicDef;
    private Label lblAvoid;
    private TextBox TbAvoid;
    private Label lblRecoverMP;
    private TextBox TbRecoverMP;
    private Button btnUpdate;
    private Label lblAttackSpeed;
    private Label lblMagicEva;
    private TextBox TbMagicEva;
    private Label lblAttackArea;
    private TextBox TbAttackArea;
    private Label lblWalkSpeed;
    private TextBox TbWalkSpeed;
    private TextBox TbMoveSpeed;
    private Label lblMoveSpeed;
    private TextBox TbAttackSpeed;

    public MobMassEdit() => this.InitializeComponent();

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.ClbMob = new CheckedListBox();
      this.lblName = new Label();
      this.TbHP = new TextBox();
      this.lblHP = new Label();
      this.lblFlag = new Label();
      this.TbFlag = new TextBox();
      this.lblAttack = new Label();
      this.TbAttack = new TextBox();
      this.lblDefense = new Label();
      this.TbDefense = new TextBox();
      this.lblHit = new Label();
      this.TbHit = new TextBox();
      this.lblRecoverHP = new Label();
      this.TbRecoverHP = new TextBox();
      this.lblMP = new Label();
      this.TbMP = new TextBox();
      this.lblStateFlag = new Label();
      this.TbStateFlag = new TextBox();
      this.lblMAttack = new Label();
      this.TbMagicAttack = new TextBox();
      this.lblMagicDef = new Label();
      this.TbMagicDef = new TextBox();
      this.lblAvoid = new Label();
      this.TbAvoid = new TextBox();
      this.lblRecoverMP = new Label();
      this.TbRecoverMP = new TextBox();
      this.btnUpdate = new Button();
      this.lblAttackSpeed = new Label();
      this.TbAttackSpeed = new TextBox();
      this.lblMagicEva = new Label();
      this.TbMagicEva = new TextBox();
      this.lblAttackArea = new Label();
      this.TbAttackArea = new TextBox();
      this.lblWalkSpeed = new Label();
      this.TbWalkSpeed = new TextBox();
      this.TbMoveSpeed = new TextBox();
      this.lblMoveSpeed = new Label();
      this.SuspendLayout();
      this.ClbMob.CheckOnClick = true;
      this.ClbMob.FormattingEnabled = true;
      this.ClbMob.Location = new Point(12, 32);
      this.ClbMob.Name = "ClbMob";
      this.ClbMob.Size = new Size(113, 289);
      this.ClbMob.TabIndex = 0;
      this.lblName.AutoSize = true;
      this.lblName.Location = new Point(12, 9);
      this.lblName.Name = "lblName";
      this.lblName.Size = new Size(62, 13);
      this.lblName.TabIndex = 1;
      this.lblName.Text = "Monster ID:";
      this.TbHP.Location = new Point(131, 32);
      this.TbHP.Name = "TbHP";
      this.TbHP.Size = new Size(91, 20);
      this.TbHP.TabIndex = 2;
      this.lblHP.AutoSize = true;
      this.lblHP.Location = new Point(128, 16);
      this.lblHP.Name = "lblHP";
      this.lblHP.Size = new Size(22, 13);
      this.lblHP.TabIndex = 3;
      this.lblHP.Text = "HP";
      this.lblFlag.AutoSize = true;
      this.lblFlag.Location = new Point(128, 55);
      this.lblFlag.Name = "lblFlag";
      this.lblFlag.Size = new Size(27, 13);
      this.lblFlag.TabIndex = 5;
      this.lblFlag.Text = "Flag";
      this.TbFlag.Location = new Point(131, 71);
      this.TbFlag.Name = "TbFlag";
      this.TbFlag.Size = new Size(91, 20);
      this.TbFlag.TabIndex = 4;
      this.lblAttack.AutoSize = true;
      this.lblAttack.Location = new Point(128, 94);
      this.lblAttack.Name = "lblAttack";
      this.lblAttack.Size = new Size(38, 13);
      this.lblAttack.TabIndex = 7;
      this.lblAttack.Text = "Attack";
      this.TbAttack.Location = new Point(131, 110);
      this.TbAttack.Name = "TbAttack";
      this.TbAttack.Size = new Size(91, 20);
      this.TbAttack.TabIndex = 6;
      this.lblDefense.AutoSize = true;
      this.lblDefense.Location = new Point(128, 133);
      this.lblDefense.Name = "lblDefense";
      this.lblDefense.Size = new Size(47, 13);
      this.lblDefense.TabIndex = 9;
      this.lblDefense.Text = "Defense";
      this.TbDefense.Location = new Point(131, 149);
      this.TbDefense.Name = "TbDefense";
      this.TbDefense.Size = new Size(91, 20);
      this.TbDefense.TabIndex = 8;
      this.lblHit.AutoSize = true;
      this.lblHit.Location = new Point(128, 172);
      this.lblHit.Name = "lblHit";
      this.lblHit.Size = new Size(20, 13);
      this.lblHit.TabIndex = 11;
      this.lblHit.Text = "Hit";
      this.TbHit.Location = new Point(131, 188);
      this.TbHit.Name = "TbHit";
      this.TbHit.Size = new Size(91, 20);
      this.TbHit.TabIndex = 10;
      this.lblRecoverHP.AutoSize = true;
      this.lblRecoverHP.Location = new Point(131, 211);
      this.lblRecoverHP.Name = "lblRecoverHP";
      this.lblRecoverHP.Size = new Size(63, 13);
      this.lblRecoverHP.TabIndex = 13;
      this.lblRecoverHP.Text = "RecoverHP";
      this.TbRecoverHP.Location = new Point(130, 227);
      this.TbRecoverHP.Name = "TbRecoverHP";
      this.TbRecoverHP.Size = new Size(91, 20);
      this.TbRecoverHP.TabIndex = 12;
      this.lblMP.AutoSize = true;
      this.lblMP.Location = new Point(229, 16);
      this.lblMP.Name = "lblMP";
      this.lblMP.Size = new Size(23, 13);
      this.lblMP.TabIndex = 15;
      this.lblMP.Text = "MP";
      this.TbMP.Location = new Point(232, 32);
      this.TbMP.Name = "TbMP";
      this.TbMP.Size = new Size(91, 20);
      this.TbMP.TabIndex = 14;
      this.lblStateFlag.AutoSize = true;
      this.lblStateFlag.Location = new Point(229, 55);
      this.lblStateFlag.Name = "lblStateFlag";
      this.lblStateFlag.Size = new Size(52, 13);
      this.lblStateFlag.TabIndex = 17;
      this.lblStateFlag.Text = "StateFlag";
      this.TbStateFlag.Location = new Point(232, 71);
      this.TbStateFlag.Name = "TbStateFlag";
      this.TbStateFlag.Size = new Size(91, 20);
      this.TbStateFlag.TabIndex = 16;
      this.lblMAttack.AutoSize = true;
      this.lblMAttack.Location = new Point(229, 94);
      this.lblMAttack.Name = "lblMAttack";
      this.lblMAttack.Size = new Size(75, 13);
      this.lblMAttack.TabIndex = 19;
      this.lblMAttack.Text = "MagicalAttack";
      this.TbMagicAttack.Location = new Point(232, 110);
      this.TbMagicAttack.Name = "TbMagicAttack";
      this.TbMagicAttack.Size = new Size(91, 20);
      this.TbMagicAttack.TabIndex = 18;
      this.lblMagicDef.AutoSize = true;
      this.lblMagicDef.Location = new Point(229, 133);
      this.lblMagicDef.Name = "lblMagicDef";
      this.lblMagicDef.Size = new Size(53, 13);
      this.lblMagicDef.TabIndex = 21;
      this.lblMagicDef.Text = "MagicDef";
      this.TbMagicDef.Location = new Point(232, 149);
      this.TbMagicDef.Name = "TbMagicDef";
      this.TbMagicDef.Size = new Size(91, 20);
      this.TbMagicDef.TabIndex = 20;
      this.lblAvoid.AutoSize = true;
      this.lblAvoid.Location = new Point(228, 172);
      this.lblAvoid.Name = "lblAvoid";
      this.lblAvoid.Size = new Size(34, 13);
      this.lblAvoid.TabIndex = 23;
      this.lblAvoid.Text = "Avoid";
      this.TbAvoid.Location = new Point(231, 188);
      this.TbAvoid.Name = "TbAvoid";
      this.TbAvoid.Size = new Size(91, 20);
      this.TbAvoid.TabIndex = 22;
      this.lblRecoverMP.AutoSize = true;
      this.lblRecoverMP.Location = new Point(228, 211);
      this.lblRecoverMP.Name = "lblRecoverMP";
      this.lblRecoverMP.Size = new Size(64, 13);
      this.lblRecoverMP.TabIndex = 25;
      this.lblRecoverMP.Text = "RecoverMP";
      this.TbRecoverMP.Location = new Point(231, 227);
      this.TbRecoverMP.Name = "TbRecoverMP";
      this.TbRecoverMP.Size = new Size(91, 20);
      this.TbRecoverMP.TabIndex = 24;
      this.btnUpdate.Location = new Point(130, 293);
      this.btnUpdate.Name = "btnUpdate";
      this.btnUpdate.Size = new Size(188, 38);
      this.btnUpdate.TabIndex = 26;
      this.btnUpdate.Text = "Update Selected";
      this.btnUpdate.UseVisualStyleBackColor = true;
      this.lblAttackSpeed.AutoSize = true;
      this.lblAttackSpeed.Location = new Point(228, 251);
      this.lblAttackSpeed.Name = "lblAttackSpeed";
      this.lblAttackSpeed.Size = new Size(72, 13);
      this.lblAttackSpeed.TabIndex = 30;
      this.lblAttackSpeed.Text = "Attack Speed";
      this.TbAttackSpeed.Location = new Point(231, 267);
      this.TbAttackSpeed.Name = "TbAttackSpeed";
      this.TbAttackSpeed.Size = new Size(91, 20);
      this.TbAttackSpeed.TabIndex = 29;
      this.lblMagicEva.AutoSize = true;
      this.lblMagicEva.Location = new Point(131, 251);
      this.lblMagicEva.Name = "lblMagicEva";
      this.lblMagicEva.Size = new Size(55, 13);
      this.lblMagicEva.TabIndex = 28;
      this.lblMagicEva.Text = "MagicEva";
      this.TbMagicEva.Location = new Point(130, 267);
      this.TbMagicEva.Name = "TbMagicEva";
      this.TbMagicEva.Size = new Size(91, 20);
      this.TbMagicEva.TabIndex = 27;
      this.lblAttackArea.AutoSize = true;
      this.lblAttackArea.Location = new Point(327, 94);
      this.lblAttackArea.Name = "lblAttackArea";
      this.lblAttackArea.Size = new Size(63, 13);
      this.lblAttackArea.TabIndex = 35;
      this.lblAttackArea.Text = "Attack Area";
      this.TbAttackArea.Location = new Point(330, 110);
      this.TbAttackArea.Name = "TbAttackArea";
      this.TbAttackArea.Size = new Size(91, 20);
      this.TbAttackArea.TabIndex = 34;
      this.lblWalkSpeed.AutoSize = true;
      this.lblWalkSpeed.Location = new Point(327, 55);
      this.lblWalkSpeed.Name = "lblWalkSpeed";
      this.lblWalkSpeed.Size = new Size(66, 13);
      this.lblWalkSpeed.TabIndex = 33;
      this.lblWalkSpeed.Text = "Walk Speed";
      this.TbWalkSpeed.Location = new Point(330, 71);
      this.TbWalkSpeed.Name = "TbWalkSpeed";
      this.TbWalkSpeed.Size = new Size(91, 20);
      this.TbWalkSpeed.TabIndex = 32;
      this.TbMoveSpeed.Location = new Point(330, 32);
      this.TbMoveSpeed.Name = "TbMoveSpeed";
      this.TbMoveSpeed.Size = new Size(91, 20);
      this.TbMoveSpeed.TabIndex = 31;
      this.lblMoveSpeed.AutoSize = true;
      this.lblMoveSpeed.Location = new Point(327, 16);
      this.lblMoveSpeed.Name = "lblMoveSpeed";
      this.lblMoveSpeed.Size = new Size(68, 13);
      this.lblMoveSpeed.TabIndex = 36;
      this.lblMoveSpeed.Text = "Move Speed";
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(433, 333);
      this.Controls.Add((Control) this.lblMoveSpeed);
      this.Controls.Add((Control) this.lblAttackArea);
      this.Controls.Add((Control) this.TbAttackArea);
      this.Controls.Add((Control) this.lblWalkSpeed);
      this.Controls.Add((Control) this.TbWalkSpeed);
      this.Controls.Add((Control) this.TbMoveSpeed);
      this.Controls.Add((Control) this.lblAttackSpeed);
      this.Controls.Add((Control) this.TbAttackSpeed);
      this.Controls.Add((Control) this.lblMagicEva);
      this.Controls.Add((Control) this.TbMagicEva);
      this.Controls.Add((Control) this.btnUpdate);
      this.Controls.Add((Control) this.lblRecoverMP);
      this.Controls.Add((Control) this.TbRecoverMP);
      this.Controls.Add((Control) this.lblAvoid);
      this.Controls.Add((Control) this.TbAvoid);
      this.Controls.Add((Control) this.lblMagicDef);
      this.Controls.Add((Control) this.TbMagicDef);
      this.Controls.Add((Control) this.lblMAttack);
      this.Controls.Add((Control) this.TbMagicAttack);
      this.Controls.Add((Control) this.lblStateFlag);
      this.Controls.Add((Control) this.TbStateFlag);
      this.Controls.Add((Control) this.lblMP);
      this.Controls.Add((Control) this.TbMP);
      this.Controls.Add((Control) this.lblRecoverHP);
      this.Controls.Add((Control) this.TbRecoverHP);
      this.Controls.Add((Control) this.lblHit);
      this.Controls.Add((Control) this.TbHit);
      this.Controls.Add((Control) this.lblDefense);
      this.Controls.Add((Control) this.TbDefense);
      this.Controls.Add((Control) this.lblAttack);
      this.Controls.Add((Control) this.TbAttack);
      this.Controls.Add((Control) this.lblFlag);
      this.Controls.Add((Control) this.TbFlag);
      this.Controls.Add((Control) this.lblHP);
      this.Controls.Add((Control) this.TbHP);
      this.Controls.Add((Control) this.lblName);
      this.Controls.Add((Control) this.ClbMob);
      this.Name = nameof (MobMassEdit);
      this.StartPosition = FormStartPosition.CenterParent;
      this.Text = nameof (MobMassEdit);
      this.ResumeLayout(false);
      this.PerformLayout();
    }
  }
}
