// Decompiled with JetBrains decompiler
// Type: LcDevPack_TeamDamonA.Tools.SetItemEditor
// Assembly: LcDevPack_TeamDamonA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: B13AD660-B9C7-4C88-A534-19FC9102A906
// Assembly location: C:\Users\westy\Desktop\my lc\LC_TOOLS\LCT\Debug\LcDevPack_TeamDamonA.exe

using LcDevPack_TeamDamonA.Properties;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace LcDevPack_TeamDamonA.Tools
{
  public class SetItemEditor : Form
  {
    private IContainer components = (IContainer) null;
    private MenuStrip menuStrip1;
    private ToolStripMenuItem exportToolStripMenuItem;
    private ListBox LbSetItem;
    private Label lblSearch;
    private TextBox tbSearch;
    private GroupBox GbComposition;
    private GroupBox GbConfigure;
    private Button btnAdd;
    private Button btnDelete;
    private Button BtnCopy;
    private Label lblIndex;
    private TextBox TbIndex;
    private Label lblName;
    private TextBox tbName;
    private Label lblJob;
    private ComboBox CbJob;
    private TextBox tbEnable;
    private CheckBox checkBox1;
    private TextBox TbBack;
    private PictureBox PbBack;
    private Label lblBack;
    private TextBox TbAcc3;
    private PictureBox PbAcc3;
    private Label lblAcc3;
    private TextBox TbAcc2;
    private PictureBox PbAcc2;
    private Label lblAcc2;
    private TextBox TbAcc1;
    private PictureBox PbAcc1;
    private Label lblAcc1;
    private TextBox TbBoots;
    private PictureBox PbBoots;
    private Label lblBoots;
    private TextBox TbGlove;
    private PictureBox PbGlove;
    private Label lblGlove;
    private TextBox TbShield;
    private PictureBox PbShield;
    private Label lblShield;
    private TextBox TbPants;
    private PictureBox PbPants;
    private Label lblPants;
    private TextBox TbWeapon;
    private PictureBox PbWeapon;
    private Label lblWeapon;
    private TextBox TbShirt;
    private PictureBox PbShirt;
    private Label lblShirt;
    private TextBox TbHelmet;
    private PictureBox PbHelmet;
    private Label lblHelmet;
    private PictureBox PbSelect3;
    private PictureBox PbSelect2;
    private PictureBox PbSelect1;
    private TextBox TbLevel3;
    private TextBox TbLevel2;
    private TextBox Tblevel1;
    private ComboBox CbEffectType3;
    private ComboBox CbEffectType2;
    private ComboBox CbEffectType1;
    private TextBox TbWearCount3;
    private TextBox TbWearCount2;
    private TextBox TbWearCount1;
    private Label lblLevel;
    private Label label2;
    private Label lblNumber;
    private TextBox TbOptionSkill4;
    private PictureBox PbSelect4;
    private TextBox TbLevel4;
    private ComboBox CbEffectType4;
    private TextBox TbWearCount4;
    private Label lblOptionSkill;
    private TextBox TbOptionSkill3;
    private TextBox TbOptionSkill2;
    private TextBox TbOptionSkill1;

    public SetItemEditor() => this.InitializeComponent();

    private void checkBox1_CheckedChanged(object sender, EventArgs e)
    {
      if (this.checkBox1.Checked)
        this.tbEnable.Text = "1";
      else
        this.tbEnable.Text = "0";
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (SetItemEditor));
      this.menuStrip1 = new MenuStrip();
      this.exportToolStripMenuItem = new ToolStripMenuItem();
      this.LbSetItem = new ListBox();
      this.lblSearch = new Label();
      this.tbSearch = new TextBox();
      this.GbComposition = new GroupBox();
      this.TbBack = new TextBox();
      this.PbBack = new PictureBox();
      this.lblBack = new Label();
      this.TbAcc3 = new TextBox();
      this.PbAcc3 = new PictureBox();
      this.lblAcc3 = new Label();
      this.TbAcc2 = new TextBox();
      this.PbAcc2 = new PictureBox();
      this.lblAcc2 = new Label();
      this.TbAcc1 = new TextBox();
      this.PbAcc1 = new PictureBox();
      this.lblAcc1 = new Label();
      this.TbBoots = new TextBox();
      this.PbBoots = new PictureBox();
      this.lblBoots = new Label();
      this.TbGlove = new TextBox();
      this.PbGlove = new PictureBox();
      this.lblGlove = new Label();
      this.TbShield = new TextBox();
      this.PbShield = new PictureBox();
      this.lblShield = new Label();
      this.TbPants = new TextBox();
      this.PbPants = new PictureBox();
      this.lblPants = new Label();
      this.TbWeapon = new TextBox();
      this.PbWeapon = new PictureBox();
      this.lblWeapon = new Label();
      this.TbShirt = new TextBox();
      this.PbShirt = new PictureBox();
      this.lblShirt = new Label();
      this.TbHelmet = new TextBox();
      this.PbHelmet = new PictureBox();
      this.lblHelmet = new Label();
      this.GbConfigure = new GroupBox();
      this.TbOptionSkill4 = new TextBox();
      this.PbSelect4 = new PictureBox();
      this.TbLevel4 = new TextBox();
      this.CbEffectType4 = new ComboBox();
      this.TbWearCount4 = new TextBox();
      this.lblOptionSkill = new Label();
      this.TbOptionSkill3 = new TextBox();
      this.TbOptionSkill2 = new TextBox();
      this.TbOptionSkill1 = new TextBox();
      this.PbSelect3 = new PictureBox();
      this.PbSelect2 = new PictureBox();
      this.PbSelect1 = new PictureBox();
      this.TbLevel3 = new TextBox();
      this.TbLevel2 = new TextBox();
      this.Tblevel1 = new TextBox();
      this.CbEffectType3 = new ComboBox();
      this.CbEffectType2 = new ComboBox();
      this.CbEffectType1 = new ComboBox();
      this.TbWearCount3 = new TextBox();
      this.TbWearCount2 = new TextBox();
      this.TbWearCount1 = new TextBox();
      this.lblLevel = new Label();
      this.label2 = new Label();
      this.lblNumber = new Label();
      this.btnAdd = new Button();
      this.btnDelete = new Button();
      this.BtnCopy = new Button();
      this.lblIndex = new Label();
      this.TbIndex = new TextBox();
      this.lblName = new Label();
      this.tbName = new TextBox();
      this.lblJob = new Label();
      this.CbJob = new ComboBox();
      this.tbEnable = new TextBox();
      this.checkBox1 = new CheckBox();
      this.menuStrip1.SuspendLayout();
      this.GbComposition.SuspendLayout();
      ((ISupportInitialize) this.PbBack).BeginInit();
      ((ISupportInitialize) this.PbAcc3).BeginInit();
      ((ISupportInitialize) this.PbAcc2).BeginInit();
      ((ISupportInitialize) this.PbAcc1).BeginInit();
      ((ISupportInitialize) this.PbBoots).BeginInit();
      ((ISupportInitialize) this.PbGlove).BeginInit();
      ((ISupportInitialize) this.PbShield).BeginInit();
      ((ISupportInitialize) this.PbPants).BeginInit();
      ((ISupportInitialize) this.PbWeapon).BeginInit();
      ((ISupportInitialize) this.PbShirt).BeginInit();
      ((ISupportInitialize) this.PbHelmet).BeginInit();
      this.GbConfigure.SuspendLayout();
      ((ISupportInitialize) this.PbSelect4).BeginInit();
      ((ISupportInitialize) this.PbSelect3).BeginInit();
      ((ISupportInitialize) this.PbSelect2).BeginInit();
      ((ISupportInitialize) this.PbSelect1).BeginInit();
      this.SuspendLayout();
      this.menuStrip1.Items.AddRange(new ToolStripItem[1]
      {
        (ToolStripItem) this.exportToolStripMenuItem
      });
      this.menuStrip1.Location = new Point(0, 0);
      this.menuStrip1.Name = "menuStrip1";
      this.menuStrip1.Size = new Size(865, 24);
      this.menuStrip1.TabIndex = 0;
      this.menuStrip1.Text = "menuStrip1";
      this.exportToolStripMenuItem.Name = "exportToolStripMenuItem";
      this.exportToolStripMenuItem.Size = new Size(51, 20);
      this.exportToolStripMenuItem.Text = "Export";
      this.LbSetItem.FormattingEnabled = true;
      this.LbSetItem.Location = new Point(12, 58);
      this.LbSetItem.Name = "LbSetItem";
      this.LbSetItem.Size = new Size(169, 407);
      this.LbSetItem.TabIndex = 1;
      this.lblSearch.AutoSize = true;
      this.lblSearch.Location = new Point(13, 35);
      this.lblSearch.Name = "lblSearch";
      this.lblSearch.Size = new Size(44, 13);
      this.lblSearch.TabIndex = 3;
      this.lblSearch.Text = "Search:";
      this.tbSearch.Location = new Point(56, 32);
      this.tbSearch.Name = "tbSearch";
      this.tbSearch.Size = new Size(125, 20);
      this.tbSearch.TabIndex = 4;
      this.GbComposition.Controls.Add((Control) this.TbBack);
      this.GbComposition.Controls.Add((Control) this.PbBack);
      this.GbComposition.Controls.Add((Control) this.lblBack);
      this.GbComposition.Controls.Add((Control) this.TbAcc3);
      this.GbComposition.Controls.Add((Control) this.PbAcc3);
      this.GbComposition.Controls.Add((Control) this.lblAcc3);
      this.GbComposition.Controls.Add((Control) this.TbAcc2);
      this.GbComposition.Controls.Add((Control) this.PbAcc2);
      this.GbComposition.Controls.Add((Control) this.lblAcc2);
      this.GbComposition.Controls.Add((Control) this.TbAcc1);
      this.GbComposition.Controls.Add((Control) this.PbAcc1);
      this.GbComposition.Controls.Add((Control) this.lblAcc1);
      this.GbComposition.Controls.Add((Control) this.TbBoots);
      this.GbComposition.Controls.Add((Control) this.PbBoots);
      this.GbComposition.Controls.Add((Control) this.lblBoots);
      this.GbComposition.Controls.Add((Control) this.TbGlove);
      this.GbComposition.Controls.Add((Control) this.PbGlove);
      this.GbComposition.Controls.Add((Control) this.lblGlove);
      this.GbComposition.Controls.Add((Control) this.TbShield);
      this.GbComposition.Controls.Add((Control) this.PbShield);
      this.GbComposition.Controls.Add((Control) this.lblShield);
      this.GbComposition.Controls.Add((Control) this.TbPants);
      this.GbComposition.Controls.Add((Control) this.PbPants);
      this.GbComposition.Controls.Add((Control) this.lblPants);
      this.GbComposition.Controls.Add((Control) this.TbWeapon);
      this.GbComposition.Controls.Add((Control) this.PbWeapon);
      this.GbComposition.Controls.Add((Control) this.lblWeapon);
      this.GbComposition.Controls.Add((Control) this.TbShirt);
      this.GbComposition.Controls.Add((Control) this.PbShirt);
      this.GbComposition.Controls.Add((Control) this.lblShirt);
      this.GbComposition.Controls.Add((Control) this.TbHelmet);
      this.GbComposition.Controls.Add((Control) this.PbHelmet);
      this.GbComposition.Controls.Add((Control) this.lblHelmet);
      this.GbComposition.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.GbComposition.Location = new Point(187, 58);
      this.GbComposition.Name = "GbComposition";
      this.GbComposition.Size = new Size((int) byte.MaxValue, 407);
      this.GbComposition.TabIndex = 5;
      this.GbComposition.TabStop = false;
      this.GbComposition.Text = "Composition of set items";
      this.TbBack.Location = new Point(122, 367);
      this.TbBack.Name = "TbBack";
      this.TbBack.Size = new Size((int) sbyte.MaxValue, 22);
      this.TbBack.TabIndex = 32;
      this.PbBack.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbBack.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbBack.Location = new Point(89, 366);
      this.PbBack.Name = "PbBack";
      this.PbBack.Size = new Size(22, 22);
      this.PbBack.TabIndex = 31;
      this.PbBack.TabStop = false;
      this.lblBack.AutoSize = true;
      this.lblBack.Location = new Point(27, 369);
      this.lblBack.Name = "lblBack";
      this.lblBack.Size = new Size(43, 16);
      this.lblBack.TabIndex = 30;
      this.lblBack.Text = "BACK";
      this.TbAcc3.Location = new Point(122, 333);
      this.TbAcc3.Name = "TbAcc3";
      this.TbAcc3.Size = new Size((int) sbyte.MaxValue, 22);
      this.TbAcc3.TabIndex = 29;
      this.PbAcc3.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbAcc3.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbAcc3.Location = new Point(89, 332);
      this.PbAcc3.Name = "PbAcc3";
      this.PbAcc3.Size = new Size(22, 22);
      this.PbAcc3.TabIndex = 28;
      this.PbAcc3.TabStop = false;
      this.lblAcc3.AutoSize = true;
      this.lblAcc3.Location = new Point(27, 335);
      this.lblAcc3.Name = "lblAcc3";
      this.lblAcc3.Size = new Size(42, 16);
      this.lblAcc3.TabIndex = 27;
      this.lblAcc3.Text = "ACC3";
      this.TbAcc2.Location = new Point(122, 301);
      this.TbAcc2.Name = "TbAcc2";
      this.TbAcc2.Size = new Size((int) sbyte.MaxValue, 22);
      this.TbAcc2.TabIndex = 26;
      this.PbAcc2.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbAcc2.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbAcc2.Location = new Point(89, 300);
      this.PbAcc2.Name = "PbAcc2";
      this.PbAcc2.Size = new Size(22, 22);
      this.PbAcc2.TabIndex = 25;
      this.PbAcc2.TabStop = false;
      this.lblAcc2.AutoSize = true;
      this.lblAcc2.Location = new Point(30, 303);
      this.lblAcc2.Name = "lblAcc2";
      this.lblAcc2.Size = new Size(42, 16);
      this.lblAcc2.TabIndex = 24;
      this.lblAcc2.Text = "ACC2";
      this.TbAcc1.Location = new Point(122, 268);
      this.TbAcc1.Name = "TbAcc1";
      this.TbAcc1.Size = new Size((int) sbyte.MaxValue, 22);
      this.TbAcc1.TabIndex = 23;
      this.PbAcc1.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbAcc1.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbAcc1.Location = new Point(89, 267);
      this.PbAcc1.Name = "PbAcc1";
      this.PbAcc1.Size = new Size(22, 22);
      this.PbAcc1.TabIndex = 22;
      this.PbAcc1.TabStop = false;
      this.lblAcc1.AutoSize = true;
      this.lblAcc1.Location = new Point(30, 270);
      this.lblAcc1.Name = "lblAcc1";
      this.lblAcc1.Size = new Size(42, 16);
      this.lblAcc1.TabIndex = 21;
      this.lblAcc1.Text = "ACC1";
      this.TbBoots.Location = new Point(122, 237);
      this.TbBoots.Name = "TbBoots";
      this.TbBoots.Size = new Size((int) sbyte.MaxValue, 22);
      this.TbBoots.TabIndex = 20;
      this.PbBoots.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbBoots.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbBoots.Location = new Point(89, 236);
      this.PbBoots.Name = "PbBoots";
      this.PbBoots.Size = new Size(22, 22);
      this.PbBoots.TabIndex = 19;
      this.PbBoots.TabStop = false;
      this.lblBoots.AutoSize = true;
      this.lblBoots.Location = new Point(24, 239);
      this.lblBoots.Name = "lblBoots";
      this.lblBoots.Size = new Size(55, 16);
      this.lblBoots.TabIndex = 18;
      this.lblBoots.Text = "BOOTS";
      this.TbGlove.Location = new Point(122, 206);
      this.TbGlove.Name = "TbGlove";
      this.TbGlove.Size = new Size((int) sbyte.MaxValue, 22);
      this.TbGlove.TabIndex = 17;
      this.PbGlove.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbGlove.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbGlove.Location = new Point(89, 205);
      this.PbGlove.Name = "PbGlove";
      this.PbGlove.Size = new Size(22, 22);
      this.PbGlove.TabIndex = 16;
      this.PbGlove.TabStop = false;
      this.lblGlove.AutoSize = true;
      this.lblGlove.Location = new Point(24, 208);
      this.lblGlove.Name = "lblGlove";
      this.lblGlove.Size = new Size(53, 16);
      this.lblGlove.TabIndex = 15;
      this.lblGlove.Text = "GLOVE";
      this.TbShield.Location = new Point(122, 172);
      this.TbShield.Name = "TbShield";
      this.TbShield.Size = new Size((int) sbyte.MaxValue, 22);
      this.TbShield.TabIndex = 14;
      this.PbShield.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbShield.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbShield.Location = new Point(89, 171);
      this.PbShield.Name = "PbShield";
      this.PbShield.Size = new Size(22, 22);
      this.PbShield.TabIndex = 13;
      this.PbShield.TabStop = false;
      this.lblShield.AutoSize = true;
      this.lblShield.Location = new Point(24, 174);
      this.lblShield.Name = "lblShield";
      this.lblShield.Size = new Size(56, 16);
      this.lblShield.TabIndex = 12;
      this.lblShield.Text = "SHIELD";
      this.TbPants.Location = new Point(122, 137);
      this.TbPants.Name = "TbPants";
      this.TbPants.Size = new Size((int) sbyte.MaxValue, 22);
      this.TbPants.TabIndex = 11;
      this.PbPants.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbPants.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbPants.Location = new Point(89, 136);
      this.PbPants.Name = "PbPants";
      this.PbPants.Size = new Size(22, 22);
      this.PbPants.TabIndex = 10;
      this.PbPants.TabStop = false;
      this.lblPants.AutoSize = true;
      this.lblPants.Location = new Point(25, 139);
      this.lblPants.Name = "lblPants";
      this.lblPants.Size = new Size(54, 16);
      this.lblPants.TabIndex = 9;
      this.lblPants.Text = "PANTS";
      this.TbWeapon.Location = new Point(122, 103);
      this.TbWeapon.Name = "TbWeapon";
      this.TbWeapon.Size = new Size((int) sbyte.MaxValue, 22);
      this.TbWeapon.TabIndex = 8;
      this.PbWeapon.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbWeapon.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbWeapon.Location = new Point(89, 102);
      this.PbWeapon.Name = "PbWeapon";
      this.PbWeapon.Size = new Size(22, 22);
      this.PbWeapon.TabIndex = 7;
      this.PbWeapon.TabStop = false;
      this.lblWeapon.AutoSize = true;
      this.lblWeapon.Location = new Point(20, 105);
      this.lblWeapon.Name = "lblWeapon";
      this.lblWeapon.Size = new Size(68, 16);
      this.lblWeapon.TabIndex = 6;
      this.lblWeapon.Text = "WEAPON";
      this.TbShirt.Location = new Point(122, 70);
      this.TbShirt.Name = "TbShirt";
      this.TbShirt.Size = new Size((int) sbyte.MaxValue, 22);
      this.TbShirt.TabIndex = 5;
      this.PbShirt.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbShirt.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbShirt.Location = new Point(89, 69);
      this.PbShirt.Name = "PbShirt";
      this.PbShirt.Size = new Size(22, 22);
      this.PbShirt.TabIndex = 4;
      this.PbShirt.TabStop = false;
      this.lblShirt.AutoSize = true;
      this.lblShirt.Location = new Point(24, 73);
      this.lblShirt.Name = "lblShirt";
      this.lblShirt.Size = new Size(49, 16);
      this.lblShirt.TabIndex = 3;
      this.lblShirt.Text = "SHIRT";
      this.TbHelmet.Location = new Point(122, 37);
      this.TbHelmet.Name = "TbHelmet";
      this.TbHelmet.Size = new Size((int) sbyte.MaxValue, 22);
      this.TbHelmet.TabIndex = 2;
      this.PbHelmet.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbHelmet.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbHelmet.Location = new Point(89, 36);
      this.PbHelmet.Name = "PbHelmet";
      this.PbHelmet.Size = new Size(22, 22);
      this.PbHelmet.TabIndex = 1;
      this.PbHelmet.TabStop = false;
      this.lblHelmet.AutoSize = true;
      this.lblHelmet.Location = new Point(24, 39);
      this.lblHelmet.Name = "lblHelmet";
      this.lblHelmet.Size = new Size(63, 16);
      this.lblHelmet.TabIndex = 0;
      this.lblHelmet.Text = "HELMET";
      this.GbConfigure.Controls.Add((Control) this.TbOptionSkill4);
      this.GbConfigure.Controls.Add((Control) this.PbSelect4);
      this.GbConfigure.Controls.Add((Control) this.TbLevel4);
      this.GbConfigure.Controls.Add((Control) this.CbEffectType4);
      this.GbConfigure.Controls.Add((Control) this.TbWearCount4);
      this.GbConfigure.Controls.Add((Control) this.lblOptionSkill);
      this.GbConfigure.Controls.Add((Control) this.TbOptionSkill3);
      this.GbConfigure.Controls.Add((Control) this.TbOptionSkill2);
      this.GbConfigure.Controls.Add((Control) this.TbOptionSkill1);
      this.GbConfigure.Controls.Add((Control) this.PbSelect3);
      this.GbConfigure.Controls.Add((Control) this.PbSelect2);
      this.GbConfigure.Controls.Add((Control) this.PbSelect1);
      this.GbConfigure.Controls.Add((Control) this.TbLevel3);
      this.GbConfigure.Controls.Add((Control) this.TbLevel2);
      this.GbConfigure.Controls.Add((Control) this.Tblevel1);
      this.GbConfigure.Controls.Add((Control) this.CbEffectType3);
      this.GbConfigure.Controls.Add((Control) this.CbEffectType2);
      this.GbConfigure.Controls.Add((Control) this.CbEffectType1);
      this.GbConfigure.Controls.Add((Control) this.TbWearCount3);
      this.GbConfigure.Controls.Add((Control) this.TbWearCount2);
      this.GbConfigure.Controls.Add((Control) this.TbWearCount1);
      this.GbConfigure.Controls.Add((Control) this.lblLevel);
      this.GbConfigure.Controls.Add((Control) this.label2);
      this.GbConfigure.Controls.Add((Control) this.lblNumber);
      this.GbConfigure.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.GbConfigure.Location = new Point(448, 58);
      this.GbConfigure.Name = "GbConfigure";
      this.GbConfigure.Size = new Size(405, 407);
      this.GbConfigure.TabIndex = 6;
      this.GbConfigure.TabStop = false;
      this.GbConfigure.Text = "Configuring a set effect";
      this.TbOptionSkill4.Location = new Point(262, 251);
      this.TbOptionSkill4.Name = "TbOptionSkill4";
      this.TbOptionSkill4.Size = new Size(62, 22);
      this.TbOptionSkill4.TabIndex = 24;
      this.PbSelect4.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbSelect4.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbSelect4.Location = new Point(215, 251);
      this.PbSelect4.Name = "PbSelect4";
      this.PbSelect4.Size = new Size(27, 24);
      this.PbSelect4.TabIndex = 23;
      this.PbSelect4.TabStop = false;
      this.TbLevel4.Location = new Point(345, 251);
      this.TbLevel4.Name = "TbLevel4";
      this.TbLevel4.Size = new Size(39, 22);
      this.TbLevel4.TabIndex = 22;
      this.CbEffectType4.FormattingEnabled = true;
      this.CbEffectType4.Location = new Point(129, 251);
      this.CbEffectType4.Name = "CbEffectType4";
      this.CbEffectType4.Size = new Size(73, 24);
      this.CbEffectType4.TabIndex = 21;
      this.TbWearCount4.Location = new Point(37, 251);
      this.TbWearCount4.Name = "TbWearCount4";
      this.TbWearCount4.Size = new Size(60, 22);
      this.TbWearCount4.TabIndex = 20;
      this.lblOptionSkill.AutoSize = true;
      this.lblOptionSkill.Location = new Point(265, 36);
      this.lblOptionSkill.Name = "lblOptionSkill";
      this.lblOptionSkill.Size = new Size(47, 16);
      this.lblOptionSkill.TabIndex = 19;
      this.lblOptionSkill.Text = "Option";
      this.TbOptionSkill3.Location = new Point(262, 189);
      this.TbOptionSkill3.Name = "TbOptionSkill3";
      this.TbOptionSkill3.Size = new Size(62, 22);
      this.TbOptionSkill3.TabIndex = 18;
      this.TbOptionSkill2.Location = new Point(262, 131);
      this.TbOptionSkill2.Name = "TbOptionSkill2";
      this.TbOptionSkill2.Size = new Size(62, 22);
      this.TbOptionSkill2.TabIndex = 17;
      this.TbOptionSkill1.Location = new Point(262, 73);
      this.TbOptionSkill1.Name = "TbOptionSkill1";
      this.TbOptionSkill1.Size = new Size(62, 22);
      this.TbOptionSkill1.TabIndex = 16;
      this.PbSelect3.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbSelect3.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbSelect3.Location = new Point(215, 189);
      this.PbSelect3.Name = "PbSelect3";
      this.PbSelect3.Size = new Size(27, 24);
      this.PbSelect3.TabIndex = 15;
      this.PbSelect3.TabStop = false;
      this.PbSelect2.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbSelect2.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbSelect2.Location = new Point(215, 131);
      this.PbSelect2.Name = "PbSelect2";
      this.PbSelect2.Size = new Size(27, 24);
      this.PbSelect2.TabIndex = 14;
      this.PbSelect2.TabStop = false;
      this.PbSelect1.BackgroundImage = (Image) Resources.oie_transparent;
      this.PbSelect1.BackgroundImageLayout = ImageLayout.Stretch;
      this.PbSelect1.Location = new Point(215, 73);
      this.PbSelect1.Name = "PbSelect1";
      this.PbSelect1.Size = new Size(27, 24);
      this.PbSelect1.TabIndex = 13;
      this.PbSelect1.TabStop = false;
      this.TbLevel3.Location = new Point(345, 189);
      this.TbLevel3.Name = "TbLevel3";
      this.TbLevel3.Size = new Size(39, 22);
      this.TbLevel3.TabIndex = 12;
      this.TbLevel2.Location = new Point(345, 131);
      this.TbLevel2.Name = "TbLevel2";
      this.TbLevel2.Size = new Size(39, 22);
      this.TbLevel2.TabIndex = 11;
      this.Tblevel1.Location = new Point(345, 73);
      this.Tblevel1.Name = "Tblevel1";
      this.Tblevel1.Size = new Size(39, 22);
      this.Tblevel1.TabIndex = 10;
      this.CbEffectType3.FormattingEnabled = true;
      this.CbEffectType3.Location = new Point(129, 189);
      this.CbEffectType3.Name = "CbEffectType3";
      this.CbEffectType3.Size = new Size(73, 24);
      this.CbEffectType3.TabIndex = 9;
      this.CbEffectType2.FormattingEnabled = true;
      this.CbEffectType2.Location = new Point(126, 131);
      this.CbEffectType2.Name = "CbEffectType2";
      this.CbEffectType2.Size = new Size(73, 24);
      this.CbEffectType2.TabIndex = 8;
      this.CbEffectType1.FormattingEnabled = true;
      this.CbEffectType1.Location = new Point(126, 73);
      this.CbEffectType1.Name = "CbEffectType1";
      this.CbEffectType1.Size = new Size(73, 24);
      this.CbEffectType1.TabIndex = 7;
      this.TbWearCount3.Location = new Point(37, 189);
      this.TbWearCount3.Name = "TbWearCount3";
      this.TbWearCount3.Size = new Size(60, 22);
      this.TbWearCount3.TabIndex = 6;
      this.TbWearCount2.Location = new Point(37, 131);
      this.TbWearCount2.Name = "TbWearCount2";
      this.TbWearCount2.Size = new Size(60, 22);
      this.TbWearCount2.TabIndex = 5;
      this.TbWearCount1.Location = new Point(37, 73);
      this.TbWearCount1.Name = "TbWearCount1";
      this.TbWearCount1.Size = new Size(60, 22);
      this.TbWearCount1.TabIndex = 4;
      this.lblLevel.AutoSize = true;
      this.lblLevel.Location = new Point(343, 36);
      this.lblLevel.Name = "lblLevel";
      this.lblLevel.Size = new Size(41, 16);
      this.lblLevel.TabIndex = 3;
      this.lblLevel.Text = "Level";
      this.label2.AutoSize = true;
      this.label2.Location = new Point(123, 36);
      this.label2.Name = "label2";
      this.label2.Size = new Size(76, 16);
      this.label2.TabIndex = 1;
      this.label2.Text = "Effect Type";
      this.lblNumber.AutoSize = true;
      this.lblNumber.Location = new Point(32, 36);
      this.lblNumber.Name = "lblNumber";
      this.lblNumber.Size = new Size(65, 16);
      this.lblNumber.TabIndex = 0;
      this.lblNumber.Text = "# of Wear";
      this.btnAdd.Location = new Point(12, 471);
      this.btnAdd.Name = "btnAdd";
      this.btnAdd.Size = new Size(45, 23);
      this.btnAdd.TabIndex = 7;
      this.btnAdd.Text = "Add";
      this.btnAdd.UseVisualStyleBackColor = true;
      this.btnDelete.Location = new Point(121, 471);
      this.btnDelete.Name = "btnDelete";
      this.btnDelete.Size = new Size(60, 23);
      this.btnDelete.TabIndex = 8;
      this.btnDelete.Text = "Delete";
      this.btnDelete.UseVisualStyleBackColor = true;
      this.BtnCopy.Location = new Point(64, 471);
      this.BtnCopy.Name = "BtnCopy";
      this.BtnCopy.Size = new Size(45, 23);
      this.BtnCopy.TabIndex = 9;
      this.BtnCopy.Text = "Copy";
      this.BtnCopy.UseVisualStyleBackColor = true;
      this.lblIndex.AutoSize = true;
      this.lblIndex.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.lblIndex.Location = new Point(198, 33);
      this.lblIndex.Name = "lblIndex";
      this.lblIndex.Size = new Size(43, 16);
      this.lblIndex.TabIndex = 10;
      this.lblIndex.Text = "Index:";
      this.TbIndex.Location = new Point(242, 33);
      this.TbIndex.Name = "TbIndex";
      this.TbIndex.Size = new Size(48, 20);
      this.TbIndex.TabIndex = 11;
      this.lblName.AutoSize = true;
      this.lblName.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.lblName.Location = new Point(296, 34);
      this.lblName.Name = "lblName";
      this.lblName.Size = new Size(48, 16);
      this.lblName.TabIndex = 12;
      this.lblName.Text = "Name:";
      this.tbName.Location = new Point(340, 33);
      this.tbName.Name = "tbName";
      this.tbName.Size = new Size(136, 20);
      this.tbName.TabIndex = 13;
      this.lblJob.AutoSize = true;
      this.lblJob.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.lblJob.Location = new Point(482, 33);
      this.lblJob.Name = "lblJob";
      this.lblJob.Size = new Size(34, 16);
      this.lblJob.TabIndex = 14;
      this.lblJob.Text = "Job:";
      this.CbJob.FormattingEnabled = true;
      this.CbJob.Location = new Point(523, 33);
      this.CbJob.Name = "CbJob";
      this.CbJob.Size = new Size(124, 21);
      this.CbJob.TabIndex = 15;
      this.tbEnable.Location = new Point(793, 34);
      this.tbEnable.Name = "tbEnable";
      this.tbEnable.Size = new Size(26, 20);
      this.tbEnable.TabIndex = 17;
      this.tbEnable.Visible = false;
      this.checkBox1.AutoSize = true;
      this.checkBox1.FlatStyle = FlatStyle.Flat;
      this.checkBox1.Location = new Point(716, 35);
      this.checkBox1.Name = "checkBox1";
      this.checkBox1.Size = new Size(56, 17);
      this.checkBox1.TabIndex = 18;
      this.checkBox1.Text = "Enable";
      this.checkBox1.UseVisualStyleBackColor = true;
      this.checkBox1.CheckedChanged += new EventHandler(this.checkBox1_CheckedChanged);
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(865, 494);
      this.Controls.Add((Control) this.checkBox1);
      this.Controls.Add((Control) this.tbEnable);
      this.Controls.Add((Control) this.CbJob);
      this.Controls.Add((Control) this.lblJob);
      this.Controls.Add((Control) this.tbName);
      this.Controls.Add((Control) this.lblName);
      this.Controls.Add((Control) this.TbIndex);
      this.Controls.Add((Control) this.lblIndex);
      this.Controls.Add((Control) this.BtnCopy);
      this.Controls.Add((Control) this.btnDelete);
      this.Controls.Add((Control) this.btnAdd);
      this.Controls.Add((Control) this.GbConfigure);
      this.Controls.Add((Control) this.GbComposition);
      this.Controls.Add((Control) this.tbSearch);
      this.Controls.Add((Control) this.lblSearch);
      this.Controls.Add((Control) this.LbSetItem);
      this.Controls.Add((Control) this.menuStrip1);
      this.Icon = (Icon) componentResourceManager.GetObject("$this.Icon");
      this.MainMenuStrip = this.menuStrip1;
      this.Name = nameof (SetItemEditor);
      this.Text = nameof (SetItemEditor);
      this.menuStrip1.ResumeLayout(false);
      this.menuStrip1.PerformLayout();
      this.GbComposition.ResumeLayout(false);
      this.GbComposition.PerformLayout();
      ((ISupportInitialize) this.PbBack).EndInit();
      ((ISupportInitialize) this.PbAcc3).EndInit();
      ((ISupportInitialize) this.PbAcc2).EndInit();
      ((ISupportInitialize) this.PbAcc1).EndInit();
      ((ISupportInitialize) this.PbBoots).EndInit();
      ((ISupportInitialize) this.PbGlove).EndInit();
      ((ISupportInitialize) this.PbShield).EndInit();
      ((ISupportInitialize) this.PbPants).EndInit();
      ((ISupportInitialize) this.PbWeapon).EndInit();
      ((ISupportInitialize) this.PbShirt).EndInit();
      ((ISupportInitialize) this.PbHelmet).EndInit();
      this.GbConfigure.ResumeLayout(false);
      this.GbConfigure.PerformLayout();
      ((ISupportInitialize) this.PbSelect4).EndInit();
      ((ISupportInitialize) this.PbSelect3).EndInit();
      ((ISupportInitialize) this.PbSelect2).EndInit();
      ((ISupportInitialize) this.PbSelect1).EndInit();
      this.ResumeLayout(false);
      this.PerformLayout();
    }
  }
}
