// Decompiled with JetBrains decompiler
// Type: LcDevPack_TeamDamonA.RatesEditor
// Assembly: LcDevPack_TeamDamonA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: B13AD660-B9C7-4C88-A534-19FC9102A906
// Assembly location: C:\Users\westy\Desktop\my lc\LC_TOOLS\LCT\Debug\LcDevPack_TeamDamonA.exe

using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace LcDevPack_TeamDamonA
{
  public class RatesEditor : Form
  {
    private IContainer components = (IContainer) null;
    private TabControl tbRates;
    private TabPage tbQuest;
    private TabPage tbSkill;
    private TabPage tbAffinity;
    private TabPage tbNPC;
    private GroupBox gbInfo;
    private GroupBox groupBox1;
    private GroupBox gbRate;
    private Label label4;
    private Label label3;
    private Label label2;
    private Label label1;
    private GroupBox gbAtribute;
    private TextBox textBox1;
    private Label Atribute;
    private TextBox tbDrop;
    private TextBox tbGold;
    private TextBox tbSp;
    private TextBox tbExp;
    private GroupBox gbJewelProb;
    private Label label7;
    private TextBox textBox2;
    private Label label5;
    private Label label6;
    private Label label8;
    private Label label11;
    private Label label10;
    private Label label9;
    private Button button12;
    private Button button13;
    private Button button14;
    private Button button15;
    private Label label14;
    private GroupBox groupBox2;
    private Button button24;
    private Button button25;
    private Label label12;
    private TextBox textBox3;
    private Label label13;
    private Button button22;
    private Button button23;
    private Button button20;
    private Button button21;
    private Button button18;
    private Button button19;
    private Button button16;
    private Button button17;
    private CheckBox cbMinus;
    private CheckBox cbPlus;
    private GroupBox groupBox7;
    private CheckBox checkBox21;
    private CheckBox checkBox22;
    private CheckBox checkBox23;
    private CheckBox checkBox24;
    private CheckBox checkBox25;
    private CheckBox checkBox26;
    private Button button9;
    private Button button10;
    private Button button11;
    private Button button26;
    private Button button27;
    private Button button28;
    private Label label23;
    private Label label24;
    private Label label25;
    private TextBox textBox8;
    private TextBox textBox9;
    private TextBox textBox10;
    private Label label27;
    private Label label28;
    private Label label29;
    private CheckBox checkBox11;
    private CheckBox checkBox12;
    private CheckBox checkBox9;
    private CheckBox checkBox10;
    private CheckBox checkBox7;
    private CheckBox checkBox8;
    private CheckBox checkBox5;
    private CheckBox checkBox6;
    private CheckBox checkBox3;
    private CheckBox checkBox4;
    private CheckBox checkBox1;
    private CheckBox checkBox2;
    private GroupBox groupBox5;
    private CheckBox checkBox33;
    private CheckBox checkBox34;
    private Button button35;
    private Button button36;
    private Label label35;
    private TextBox textBox14;
    private Label label36;
    private CheckBox checkBox31;
    private CheckBox checkBox32;
    private Button button33;
    private Button button34;
    private Label label33;
    private TextBox textBox13;
    private Label label34;
    private GroupBox groupBox4;
    private CheckBox checkBox19;
    private CheckBox checkBox20;
    private CheckBox checkBox27;
    private CheckBox checkBox28;
    private CheckBox checkBox29;
    private CheckBox checkBox30;
    private Button button7;
    private Button button8;
    private Button button29;
    private Button button30;
    private Button button31;
    private Button button32;
    private Label label21;
    private Label label22;
    private Label label26;
    private TextBox textBox7;
    private TextBox textBox11;
    private TextBox textBox12;
    private Label label30;
    private Label label31;
    private Label label32;
    private GroupBox groupBox3;
    private CheckBox checkBox13;
    private CheckBox checkBox14;
    private CheckBox checkBox15;
    private CheckBox checkBox16;
    private CheckBox checkBox17;
    private CheckBox checkBox18;
    private Button button1;
    private Button button2;
    private Button button3;
    private Button button4;
    private Button button5;
    private Button button6;
    private Label label15;
    private Label label16;
    private Label label17;
    private TextBox textBox4;
    private TextBox textBox5;
    private TextBox textBox6;
    private Label label18;
    private Label label19;
    private Label label20;

    public RatesEditor() => this.InitializeComponent();

    private void RatesEditor_Load(object sender, EventArgs e)
    {
    }

    private void Attriburte_Enter(object sender, EventArgs e)
    {
    }

    private void groupBox1_Enter(object sender, EventArgs e)
    {
    }

    private void gbInfo_Enter(object sender, EventArgs e)
    {
    }

    private void button15_Click(object sender, EventArgs e)
    {
    }

    private void button14_Click(object sender, EventArgs e)
    {
    }

    private void button17_Click(object sender, EventArgs e)
    {
    }

    private void button16_Click(object sender, EventArgs e)
    {
    }

    private void button19_Click(object sender, EventArgs e)
    {
    }

    private void button18_Click(object sender, EventArgs e)
    {
    }

    private void button21_Click(object sender, EventArgs e)
    {
    }

    private void button20_Click(object sender, EventArgs e)
    {
    }

    private void button13_Click(object sender, EventArgs e)
    {
    }

    private void button12_Click(object sender, EventArgs e)
    {
    }

    private void button23_Click(object sender, EventArgs e)
    {
    }

    private void button22_Click(object sender, EventArgs e)
    {
    }

    private void button25_Click(object sender, EventArgs e)
    {
    }

    private void button24_Click(object sender, EventArgs e)
    {
    }

    private void gbRate_Enter(object sender, EventArgs e)
    {
    }

    private void button28_Click(object sender, EventArgs e)
    {
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.tbRates = new TabControl();
      this.tbQuest = new TabPage();
      this.tbSkill = new TabPage();
      this.tbAffinity = new TabPage();
      this.tbNPC = new TabPage();
      this.gbInfo = new GroupBox();
      this.groupBox1 = new GroupBox();
      this.gbAtribute = new GroupBox();
      this.textBox1 = new TextBox();
      this.Atribute = new Label();
      this.gbRate = new GroupBox();
      this.tbDrop = new TextBox();
      this.tbGold = new TextBox();
      this.tbSp = new TextBox();
      this.tbExp = new TextBox();
      this.label4 = new Label();
      this.label3 = new Label();
      this.label2 = new Label();
      this.label1 = new Label();
      this.gbJewelProb = new GroupBox();
      this.textBox2 = new TextBox();
      this.label5 = new Label();
      this.label6 = new Label();
      this.label7 = new Label();
      this.label8 = new Label();
      this.label9 = new Label();
      this.label10 = new Label();
      this.label11 = new Label();
      this.button12 = new Button();
      this.button13 = new Button();
      this.button14 = new Button();
      this.button15 = new Button();
      this.button16 = new Button();
      this.button17 = new Button();
      this.button18 = new Button();
      this.button19 = new Button();
      this.button20 = new Button();
      this.button21 = new Button();
      this.button22 = new Button();
      this.button23 = new Button();
      this.groupBox2 = new GroupBox();
      this.button24 = new Button();
      this.button25 = new Button();
      this.label12 = new Label();
      this.textBox3 = new TextBox();
      this.label13 = new Label();
      this.label14 = new Label();
      this.cbPlus = new CheckBox();
      this.cbMinus = new CheckBox();
      this.checkBox1 = new CheckBox();
      this.checkBox2 = new CheckBox();
      this.checkBox3 = new CheckBox();
      this.checkBox4 = new CheckBox();
      this.checkBox5 = new CheckBox();
      this.checkBox6 = new CheckBox();
      this.checkBox7 = new CheckBox();
      this.checkBox8 = new CheckBox();
      this.checkBox9 = new CheckBox();
      this.checkBox10 = new CheckBox();
      this.checkBox11 = new CheckBox();
      this.checkBox12 = new CheckBox();
      this.groupBox7 = new GroupBox();
      this.checkBox21 = new CheckBox();
      this.checkBox22 = new CheckBox();
      this.checkBox23 = new CheckBox();
      this.checkBox24 = new CheckBox();
      this.checkBox25 = new CheckBox();
      this.checkBox26 = new CheckBox();
      this.button9 = new Button();
      this.button10 = new Button();
      this.button11 = new Button();
      this.button26 = new Button();
      this.button27 = new Button();
      this.button28 = new Button();
      this.label23 = new Label();
      this.label24 = new Label();
      this.label25 = new Label();
      this.textBox8 = new TextBox();
      this.textBox9 = new TextBox();
      this.textBox10 = new TextBox();
      this.label27 = new Label();
      this.label28 = new Label();
      this.label29 = new Label();
      this.groupBox3 = new GroupBox();
      this.checkBox13 = new CheckBox();
      this.checkBox14 = new CheckBox();
      this.checkBox15 = new CheckBox();
      this.checkBox16 = new CheckBox();
      this.checkBox17 = new CheckBox();
      this.checkBox18 = new CheckBox();
      this.button1 = new Button();
      this.button2 = new Button();
      this.button3 = new Button();
      this.button4 = new Button();
      this.button5 = new Button();
      this.button6 = new Button();
      this.label15 = new Label();
      this.label16 = new Label();
      this.label17 = new Label();
      this.textBox4 = new TextBox();
      this.textBox5 = new TextBox();
      this.textBox6 = new TextBox();
      this.label18 = new Label();
      this.label19 = new Label();
      this.label20 = new Label();
      this.groupBox4 = new GroupBox();
      this.checkBox19 = new CheckBox();
      this.checkBox20 = new CheckBox();
      this.checkBox27 = new CheckBox();
      this.checkBox28 = new CheckBox();
      this.checkBox29 = new CheckBox();
      this.checkBox30 = new CheckBox();
      this.button7 = new Button();
      this.button8 = new Button();
      this.button29 = new Button();
      this.button30 = new Button();
      this.button31 = new Button();
      this.button32 = new Button();
      this.label21 = new Label();
      this.label22 = new Label();
      this.label26 = new Label();
      this.textBox7 = new TextBox();
      this.textBox11 = new TextBox();
      this.textBox12 = new TextBox();
      this.label30 = new Label();
      this.label31 = new Label();
      this.label32 = new Label();
      this.groupBox5 = new GroupBox();
      this.checkBox31 = new CheckBox();
      this.checkBox32 = new CheckBox();
      this.button33 = new Button();
      this.button34 = new Button();
      this.label33 = new Label();
      this.textBox13 = new TextBox();
      this.label34 = new Label();
      this.checkBox33 = new CheckBox();
      this.checkBox34 = new CheckBox();
      this.button35 = new Button();
      this.button36 = new Button();
      this.label35 = new Label();
      this.textBox14 = new TextBox();
      this.label36 = new Label();
      this.tbRates.SuspendLayout();
      this.tbSkill.SuspendLayout();
      this.tbAffinity.SuspendLayout();
      this.tbNPC.SuspendLayout();
      this.gbInfo.SuspendLayout();
      this.groupBox1.SuspendLayout();
      this.gbAtribute.SuspendLayout();
      this.gbRate.SuspendLayout();
      this.gbJewelProb.SuspendLayout();
      this.groupBox2.SuspendLayout();
      this.groupBox7.SuspendLayout();
      this.groupBox3.SuspendLayout();
      this.groupBox4.SuspendLayout();
      this.groupBox5.SuspendLayout();
      this.SuspendLayout();
      this.tbRates.Controls.Add((Control) this.tbQuest);
      this.tbRates.Controls.Add((Control) this.tbSkill);
      this.tbRates.Controls.Add((Control) this.tbAffinity);
      this.tbRates.Controls.Add((Control) this.tbNPC);
      this.tbRates.Location = new Point(12, 12);
      this.tbRates.Name = "tbRates";
      this.tbRates.SelectedIndex = 0;
      this.tbRates.Size = new Size(297, 533);
      this.tbRates.TabIndex = 0;
      this.tbQuest.Location = new Point(4, 22);
      this.tbQuest.Name = "tbQuest";
      this.tbQuest.Padding = new Padding(3);
      this.tbQuest.Size = new Size(289, 507);
      this.tbQuest.TabIndex = 0;
      this.tbQuest.Text = "Quest";
      this.tbQuest.UseVisualStyleBackColor = true;
      this.tbSkill.Controls.Add((Control) this.groupBox5);
      this.tbSkill.Controls.Add((Control) this.groupBox4);
      this.tbSkill.Controls.Add((Control) this.groupBox3);
      this.tbSkill.Location = new Point(4, 22);
      this.tbSkill.Name = "tbSkill";
      this.tbSkill.Padding = new Padding(3);
      this.tbSkill.Size = new Size(289, 507);
      this.tbSkill.TabIndex = 1;
      this.tbSkill.Text = "Skill";
      this.tbSkill.UseVisualStyleBackColor = true;
      this.tbAffinity.Controls.Add((Control) this.groupBox7);
      this.tbAffinity.Location = new Point(4, 22);
      this.tbAffinity.Name = "tbAffinity";
      this.tbAffinity.Padding = new Padding(3);
      this.tbAffinity.Size = new Size(289, 507);
      this.tbAffinity.TabIndex = 2;
      this.tbAffinity.Text = "Affinity";
      this.tbAffinity.UseVisualStyleBackColor = true;
      this.tbNPC.Controls.Add((Control) this.gbInfo);
      this.tbNPC.Location = new Point(4, 22);
      this.tbNPC.Name = "tbNPC";
      this.tbNPC.Padding = new Padding(3);
      this.tbNPC.Size = new Size(289, 507);
      this.tbNPC.TabIndex = 3;
      this.tbNPC.Text = "NPC";
      this.tbNPC.UseVisualStyleBackColor = true;
      this.gbInfo.Controls.Add((Control) this.groupBox1);
      this.gbInfo.Controls.Add((Control) this.gbRate);
      this.gbInfo.Location = new Point(6, 6);
      this.gbInfo.Name = "gbInfo";
      this.gbInfo.Size = new Size(282, 505);
      this.gbInfo.TabIndex = 0;
      this.gbInfo.TabStop = false;
      this.gbInfo.Text = "Info";
      this.gbInfo.Enter += new EventHandler(this.gbInfo_Enter);
      this.groupBox1.Controls.Add((Control) this.label14);
      this.groupBox1.Controls.Add((Control) this.groupBox2);
      this.groupBox1.Controls.Add((Control) this.gbJewelProb);
      this.groupBox1.Controls.Add((Control) this.gbAtribute);
      this.groupBox1.Location = new Point((int) sbyte.MaxValue, 12);
      this.groupBox1.Name = "groupBox1";
      this.groupBox1.Size = new Size(154, 481);
      this.groupBox1.TabIndex = 1;
      this.groupBox1.TabStop = false;
      this.groupBox1.Text = "Misc";
      this.groupBox1.Enter += new EventHandler(this.groupBox1_Enter);
      this.gbAtribute.Controls.Add((Control) this.checkBox7);
      this.gbAtribute.Controls.Add((Control) this.checkBox8);
      this.gbAtribute.Controls.Add((Control) this.button12);
      this.gbAtribute.Controls.Add((Control) this.label6);
      this.gbAtribute.Controls.Add((Control) this.button13);
      this.gbAtribute.Controls.Add((Control) this.textBox1);
      this.gbAtribute.Controls.Add((Control) this.Atribute);
      this.gbAtribute.Location = new Point(5, 16);
      this.gbAtribute.Name = "gbAtribute";
      this.gbAtribute.Size = new Size(148, 124);
      this.gbAtribute.TabIndex = 0;
      this.gbAtribute.TabStop = false;
      this.gbAtribute.Text = "Atribute";
      this.gbAtribute.Enter += new EventHandler(this.Attriburte_Enter);
      this.textBox1.Location = new Point(28, 38);
      this.textBox1.Name = "textBox1";
      this.textBox1.Size = new Size(94, 20);
      this.textBox1.TabIndex = 46;
      this.Atribute.AutoSize = true;
      this.Atribute.Location = new Point(19, 16);
      this.Atribute.Name = "Atribute";
      this.Atribute.Size = new Size(46, 13);
      this.Atribute.TabIndex = 43;
      this.Atribute.Text = "Atribute:";
      this.gbRate.Controls.Add((Control) this.checkBox5);
      this.gbRate.Controls.Add((Control) this.checkBox6);
      this.gbRate.Controls.Add((Control) this.checkBox3);
      this.gbRate.Controls.Add((Control) this.checkBox4);
      this.gbRate.Controls.Add((Control) this.checkBox1);
      this.gbRate.Controls.Add((Control) this.checkBox2);
      this.gbRate.Controls.Add((Control) this.cbPlus);
      this.gbRate.Controls.Add((Control) this.cbMinus);
      this.gbRate.Controls.Add((Control) this.button20);
      this.gbRate.Controls.Add((Control) this.button21);
      this.gbRate.Controls.Add((Control) this.button18);
      this.gbRate.Controls.Add((Control) this.button19);
      this.gbRate.Controls.Add((Control) this.button16);
      this.gbRate.Controls.Add((Control) this.button17);
      this.gbRate.Controls.Add((Control) this.button14);
      this.gbRate.Controls.Add((Control) this.button15);
      this.gbRate.Controls.Add((Control) this.label11);
      this.gbRate.Controls.Add((Control) this.label10);
      this.gbRate.Controls.Add((Control) this.label9);
      this.gbRate.Controls.Add((Control) this.label8);
      this.gbRate.Controls.Add((Control) this.tbDrop);
      this.gbRate.Controls.Add((Control) this.tbGold);
      this.gbRate.Controls.Add((Control) this.tbSp);
      this.gbRate.Controls.Add((Control) this.tbExp);
      this.gbRate.Controls.Add((Control) this.label4);
      this.gbRate.Controls.Add((Control) this.label3);
      this.gbRate.Controls.Add((Control) this.label2);
      this.gbRate.Controls.Add((Control) this.label1);
      this.gbRate.Location = new Point(6, 11);
      this.gbRate.Name = "gbRate";
      this.gbRate.Size = new Size(120, 484);
      this.gbRate.TabIndex = 0;
      this.gbRate.TabStop = false;
      this.gbRate.Text = "Rate";
      this.gbRate.Enter += new EventHandler(this.gbRate_Enter);
      this.tbDrop.Location = new Point(6, 396);
      this.tbDrop.Name = "tbDrop";
      this.tbDrop.Size = new Size(94, 20);
      this.tbDrop.TabIndex = 42;
      this.tbGold.Location = new Point(7, 276);
      this.tbGold.Name = "tbGold";
      this.tbGold.Size = new Size(94, 20);
      this.tbGold.TabIndex = 41;
      this.tbSp.Location = new Point(6, 162);
      this.tbSp.Name = "tbSp";
      this.tbSp.Size = new Size(94, 20);
      this.tbSp.TabIndex = 40;
      this.tbExp.Location = new Point(6, 42);
      this.tbExp.Name = "tbExp";
      this.tbExp.Size = new Size(94, 20);
      this.tbExp.TabIndex = 39;
      this.label4.AutoSize = true;
      this.label4.Location = new Point(8, 374);
      this.label4.Name = "label4";
      this.label4.Size = new Size(33, 13);
      this.label4.TabIndex = 3;
      this.label4.Text = "Drop:";
      this.label3.AutoSize = true;
      this.label3.Location = new Point(6, 252);
      this.label3.Name = "label3";
      this.label3.Size = new Size(40, 13);
      this.label3.TabIndex = 2;
      this.label3.Text = "GOLD:";
      this.label2.AutoSize = true;
      this.label2.Location = new Point(7, 133);
      this.label2.Name = "label2";
      this.label2.Size = new Size(24, 13);
      this.label2.TabIndex = 1;
      this.label2.Text = "SP:";
      this.label1.AutoSize = true;
      this.label1.Location = new Point(7, 19);
      this.label1.Name = "label1";
      this.label1.Size = new Size(31, 13);
      this.label1.TabIndex = 0;
      this.label1.Text = "EXP:";
      this.gbJewelProb.Controls.Add((Control) this.checkBox9);
      this.gbJewelProb.Controls.Add((Control) this.checkBox10);
      this.gbJewelProb.Controls.Add((Control) this.button22);
      this.gbJewelProb.Controls.Add((Control) this.button23);
      this.gbJewelProb.Controls.Add((Control) this.label7);
      this.gbJewelProb.Controls.Add((Control) this.textBox2);
      this.gbJewelProb.Controls.Add((Control) this.label5);
      this.gbJewelProb.Location = new Point(2, 146);
      this.gbJewelProb.Name = "gbJewelProb";
      this.gbJewelProb.Size = new Size(148, 129);
      this.gbJewelProb.TabIndex = 47;
      this.gbJewelProb.TabStop = false;
      this.gbJewelProb.Text = "JewelProb";
      this.textBox2.Location = new Point(28, 38);
      this.textBox2.Name = "textBox2";
      this.textBox2.Size = new Size(94, 20);
      this.textBox2.TabIndex = 46;
      this.label5.AutoSize = true;
      this.label5.Location = new Point(8, 16);
      this.label5.Name = "label5";
      this.label5.Size = new Size(59, 13);
      this.label5.TabIndex = 43;
      this.label5.Text = "JewelProb:";
      this.label6.AutoSize = true;
      this.label6.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label6.Location = new Point(125, 41);
      this.label6.Name = "label6";
      this.label6.Size = new Size(16, 13);
      this.label6.TabIndex = 43;
      this.label6.Text = "%";
      this.label7.AutoSize = true;
      this.label7.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label7.Location = new Point(125, 41);
      this.label7.Name = "label7";
      this.label7.Size = new Size(16, 13);
      this.label7.TabIndex = 48;
      this.label7.Text = "%";
      this.label8.AutoSize = true;
      this.label8.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label8.Location = new Point(101, 45);
      this.label8.Name = "label8";
      this.label8.Size = new Size(16, 13);
      this.label8.TabIndex = 48;
      this.label8.Text = "%";
      this.label9.AutoSize = true;
      this.label9.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label9.Location = new Point(101, 165);
      this.label9.Name = "label9";
      this.label9.Size = new Size(16, 13);
      this.label9.TabIndex = 49;
      this.label9.Text = "%";
      this.label10.AutoSize = true;
      this.label10.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label10.Location = new Point(101, 279);
      this.label10.Name = "label10";
      this.label10.Size = new Size(16, 13);
      this.label10.TabIndex = 50;
      this.label10.Text = "%";
      this.label11.AutoSize = true;
      this.label11.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label11.Location = new Point(101, 401);
      this.label11.Name = "label11";
      this.label11.Size = new Size(16, 13);
      this.label11.TabIndex = 49;
      this.label11.Text = "%";
      this.button12.BackColor = Color.Aquamarine;
      this.button12.BackgroundImageLayout = ImageLayout.None;
      this.button12.FlatAppearance.BorderSize = 0;
      this.button12.FlatStyle = FlatStyle.Flat;
      this.button12.Location = new Point(25, 93);
      this.button12.Name = "button12";
      this.button12.Size = new Size(112, 23);
      this.button12.TabIndex = 49;
      this.button12.Text = "Export Query";
      this.button12.UseVisualStyleBackColor = false;
      this.button12.Click += new EventHandler(this.button12_Click);
      this.button13.BackColor = SystemColors.ActiveCaption;
      this.button13.BackgroundImageLayout = ImageLayout.None;
      this.button13.FlatAppearance.BorderSize = 0;
      this.button13.FlatStyle = FlatStyle.Flat;
      this.button13.Location = new Point(25, 64);
      this.button13.Name = "button13";
      this.button13.Size = new Size(112, 23);
      this.button13.TabIndex = 48;
      this.button13.Text = "Send Query";
      this.button13.UseVisualStyleBackColor = false;
      this.button13.Click += new EventHandler(this.button13_Click);
      this.button14.BackColor = Color.Aquamarine;
      this.button14.BackgroundImageLayout = ImageLayout.None;
      this.button14.FlatAppearance.BorderSize = 0;
      this.button14.FlatStyle = FlatStyle.Flat;
      this.button14.Location = new Point(2, 97);
      this.button14.Name = "button14";
      this.button14.Size = new Size(108, 27);
      this.button14.TabIndex = 52;
      this.button14.Text = "Export Query";
      this.button14.UseVisualStyleBackColor = false;
      this.button14.Click += new EventHandler(this.button14_Click);
      this.button15.BackColor = SystemColors.ActiveCaption;
      this.button15.BackgroundImageLayout = ImageLayout.None;
      this.button15.FlatAppearance.BorderSize = 0;
      this.button15.FlatStyle = FlatStyle.Flat;
      this.button15.Location = new Point(2, 68);
      this.button15.Name = "button15";
      this.button15.Size = new Size(108, 27);
      this.button15.TabIndex = 51;
      this.button15.Text = "Send Query";
      this.button15.UseVisualStyleBackColor = false;
      this.button15.Click += new EventHandler(this.button15_Click);
      this.button16.BackColor = Color.Aquamarine;
      this.button16.BackgroundImageLayout = ImageLayout.None;
      this.button16.FlatAppearance.BorderSize = 0;
      this.button16.FlatStyle = FlatStyle.Flat;
      this.button16.Location = new Point(6, 217);
      this.button16.Name = "button16";
      this.button16.Size = new Size(108, 27);
      this.button16.TabIndex = 54;
      this.button16.Text = "Export Query";
      this.button16.UseVisualStyleBackColor = false;
      this.button16.Click += new EventHandler(this.button16_Click);
      this.button17.BackColor = SystemColors.ActiveCaption;
      this.button17.BackgroundImageLayout = ImageLayout.None;
      this.button17.FlatAppearance.BorderSize = 0;
      this.button17.FlatStyle = FlatStyle.Flat;
      this.button17.Location = new Point(6, 188);
      this.button17.Name = "button17";
      this.button17.Size = new Size(108, 27);
      this.button17.TabIndex = 53;
      this.button17.Text = "Send Query";
      this.button17.UseVisualStyleBackColor = false;
      this.button17.Click += new EventHandler(this.button17_Click);
      this.button18.BackColor = Color.Aquamarine;
      this.button18.BackgroundImageLayout = ImageLayout.None;
      this.button18.FlatAppearance.BorderSize = 0;
      this.button18.FlatStyle = FlatStyle.Flat;
      this.button18.Location = new Point(6, 331);
      this.button18.Name = "button18";
      this.button18.Size = new Size(108, 27);
      this.button18.TabIndex = 56;
      this.button18.Text = "Export Query";
      this.button18.UseVisualStyleBackColor = false;
      this.button18.Click += new EventHandler(this.button18_Click);
      this.button19.BackColor = SystemColors.ActiveCaption;
      this.button19.BackgroundImageLayout = ImageLayout.None;
      this.button19.FlatAppearance.BorderSize = 0;
      this.button19.FlatStyle = FlatStyle.Flat;
      this.button19.Location = new Point(6, 302);
      this.button19.Name = "button19";
      this.button19.Size = new Size(108, 27);
      this.button19.TabIndex = 55;
      this.button19.Text = "Send Query";
      this.button19.UseVisualStyleBackColor = false;
      this.button19.Click += new EventHandler(this.button19_Click);
      this.button20.BackColor = Color.Aquamarine;
      this.button20.BackgroundImageLayout = ImageLayout.None;
      this.button20.FlatAppearance.BorderSize = 0;
      this.button20.FlatStyle = FlatStyle.Flat;
      this.button20.Location = new Point(7, 451);
      this.button20.Name = "button20";
      this.button20.Size = new Size(108, 27);
      this.button20.TabIndex = 58;
      this.button20.Text = "Export Query";
      this.button20.UseVisualStyleBackColor = false;
      this.button20.Click += new EventHandler(this.button20_Click);
      this.button21.BackColor = SystemColors.ActiveCaption;
      this.button21.BackgroundImageLayout = ImageLayout.None;
      this.button21.FlatAppearance.BorderSize = 0;
      this.button21.FlatStyle = FlatStyle.Flat;
      this.button21.Location = new Point(7, 422);
      this.button21.Name = "button21";
      this.button21.Size = new Size(108, 27);
      this.button21.TabIndex = 57;
      this.button21.Text = "Send Query";
      this.button21.UseVisualStyleBackColor = false;
      this.button21.Click += new EventHandler(this.button21_Click);
      this.button22.BackColor = Color.Aquamarine;
      this.button22.BackgroundImageLayout = ImageLayout.None;
      this.button22.FlatAppearance.BorderSize = 0;
      this.button22.FlatStyle = FlatStyle.Flat;
      this.button22.Location = new Point(22, 93);
      this.button22.Name = "button22";
      this.button22.Size = new Size(112, 23);
      this.button22.TabIndex = 51;
      this.button22.Text = "Export Query";
      this.button22.UseVisualStyleBackColor = false;
      this.button22.Click += new EventHandler(this.button22_Click);
      this.button23.BackColor = SystemColors.ActiveCaption;
      this.button23.BackgroundImageLayout = ImageLayout.None;
      this.button23.FlatAppearance.BorderSize = 0;
      this.button23.FlatStyle = FlatStyle.Flat;
      this.button23.Location = new Point(22, 64);
      this.button23.Name = "button23";
      this.button23.Size = new Size(112, 23);
      this.button23.TabIndex = 50;
      this.button23.Text = "Send Query";
      this.button23.UseVisualStyleBackColor = false;
      this.button23.Click += new EventHandler(this.button23_Click);
      this.groupBox2.Controls.Add((Control) this.checkBox11);
      this.groupBox2.Controls.Add((Control) this.checkBox12);
      this.groupBox2.Controls.Add((Control) this.button24);
      this.groupBox2.Controls.Add((Control) this.button25);
      this.groupBox2.Controls.Add((Control) this.label12);
      this.groupBox2.Controls.Add((Control) this.textBox3);
      this.groupBox2.Controls.Add((Control) this.label13);
      this.groupBox2.Location = new Point(5, 286);
      this.groupBox2.Name = "groupBox2";
      this.groupBox2.Size = new Size(148, 129);
      this.groupBox2.TabIndex = 52;
      this.groupBox2.TabStop = false;
      this.groupBox2.Text = "HitRate";
      this.button24.BackColor = Color.Aquamarine;
      this.button24.BackgroundImageLayout = ImageLayout.None;
      this.button24.FlatAppearance.BorderSize = 0;
      this.button24.FlatStyle = FlatStyle.Flat;
      this.button24.Location = new Point(22, 93);
      this.button24.Name = "button24";
      this.button24.Size = new Size(112, 23);
      this.button24.TabIndex = 51;
      this.button24.Text = "Export Query";
      this.button24.UseVisualStyleBackColor = false;
      this.button24.Click += new EventHandler(this.button24_Click);
      this.button25.BackColor = SystemColors.ActiveCaption;
      this.button25.BackgroundImageLayout = ImageLayout.None;
      this.button25.FlatAppearance.BorderSize = 0;
      this.button25.FlatStyle = FlatStyle.Flat;
      this.button25.Location = new Point(22, 64);
      this.button25.Name = "button25";
      this.button25.Size = new Size(112, 23);
      this.button25.TabIndex = 50;
      this.button25.Text = "Send Query";
      this.button25.UseVisualStyleBackColor = false;
      this.button25.Click += new EventHandler(this.button25_Click);
      this.label12.AutoSize = true;
      this.label12.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label12.Location = new Point(125, 41);
      this.label12.Name = "label12";
      this.label12.Size = new Size(16, 13);
      this.label12.TabIndex = 48;
      this.label12.Text = "%";
      this.textBox3.Location = new Point(28, 38);
      this.textBox3.Name = "textBox3";
      this.textBox3.Size = new Size(94, 20);
      this.textBox3.TabIndex = 46;
      this.label13.AutoSize = true;
      this.label13.Location = new Point(19, 16);
      this.label13.Name = "label13";
      this.label13.Size = new Size(41, 13);
      this.label13.TabIndex = 43;
      this.label13.Text = "Hitrate:";
      this.label14.AutoSize = true;
      this.label14.Location = new Point(2, 436);
      this.label14.Name = "label14";
      this.label14.Size = new Size(153, 13);
      this.label14.TabIndex = 53;
      this.label14.Text = "Note: All Mobs will be effected ";
      this.cbPlus.AutoSize = true;
      this.cbPlus.Location = new Point(44, 19);
      this.cbPlus.Name = "cbPlus";
      this.cbPlus.Size = new Size(32, 17);
      this.cbPlus.TabIndex = 59;
      this.cbPlus.Text = "+";
      this.cbPlus.UseVisualStyleBackColor = true;
      this.cbMinus.AutoSize = true;
      this.cbMinus.Location = new Point(78, 19);
      this.cbMinus.Name = "cbMinus";
      this.cbMinus.Size = new Size(29, 17);
      this.cbMinus.TabIndex = 60;
      this.cbMinus.Text = "-";
      this.cbMinus.UseVisualStyleBackColor = true;
      this.checkBox1.AutoSize = true;
      this.checkBox1.Location = new Point(44, 133);
      this.checkBox1.Name = "checkBox1";
      this.checkBox1.Size = new Size(32, 17);
      this.checkBox1.TabIndex = 61;
      this.checkBox1.Text = "+";
      this.checkBox1.UseVisualStyleBackColor = true;
      this.checkBox2.AutoSize = true;
      this.checkBox2.Location = new Point(78, 133);
      this.checkBox2.Name = "checkBox2";
      this.checkBox2.Size = new Size(29, 17);
      this.checkBox2.TabIndex = 62;
      this.checkBox2.Text = "-";
      this.checkBox2.UseVisualStyleBackColor = true;
      this.checkBox3.AutoSize = true;
      this.checkBox3.Location = new Point(44, 252);
      this.checkBox3.Name = "checkBox3";
      this.checkBox3.Size = new Size(32, 17);
      this.checkBox3.TabIndex = 63;
      this.checkBox3.Text = "+";
      this.checkBox3.UseVisualStyleBackColor = true;
      this.checkBox4.AutoSize = true;
      this.checkBox4.Location = new Point(78, 252);
      this.checkBox4.Name = "checkBox4";
      this.checkBox4.Size = new Size(29, 17);
      this.checkBox4.TabIndex = 64;
      this.checkBox4.Text = "-";
      this.checkBox4.UseVisualStyleBackColor = true;
      this.checkBox5.AutoSize = true;
      this.checkBox5.Location = new Point(44, 374);
      this.checkBox5.Name = "checkBox5";
      this.checkBox5.Size = new Size(32, 17);
      this.checkBox5.TabIndex = 65;
      this.checkBox5.Text = "+";
      this.checkBox5.UseVisualStyleBackColor = true;
      this.checkBox6.AutoSize = true;
      this.checkBox6.Location = new Point(78, 374);
      this.checkBox6.Name = "checkBox6";
      this.checkBox6.Size = new Size(29, 17);
      this.checkBox6.TabIndex = 66;
      this.checkBox6.Text = "-";
      this.checkBox6.UseVisualStyleBackColor = true;
      this.checkBox7.AutoSize = true;
      this.checkBox7.Location = new Point(65, 15);
      this.checkBox7.Name = "checkBox7";
      this.checkBox7.Size = new Size(32, 17);
      this.checkBox7.TabIndex = 67;
      this.checkBox7.Text = "+";
      this.checkBox7.UseVisualStyleBackColor = true;
      this.checkBox8.AutoSize = true;
      this.checkBox8.Location = new Point(99, 15);
      this.checkBox8.Name = "checkBox8";
      this.checkBox8.Size = new Size(29, 17);
      this.checkBox8.TabIndex = 68;
      this.checkBox8.Text = "-";
      this.checkBox8.UseVisualStyleBackColor = true;
      this.checkBox9.AutoSize = true;
      this.checkBox9.Location = new Point(68, 17);
      this.checkBox9.Name = "checkBox9";
      this.checkBox9.Size = new Size(32, 17);
      this.checkBox9.TabIndex = 69;
      this.checkBox9.Text = "+";
      this.checkBox9.UseVisualStyleBackColor = true;
      this.checkBox10.AutoSize = true;
      this.checkBox10.Location = new Point(102, 17);
      this.checkBox10.Name = "checkBox10";
      this.checkBox10.Size = new Size(29, 17);
      this.checkBox10.TabIndex = 70;
      this.checkBox10.Text = "-";
      this.checkBox10.UseVisualStyleBackColor = true;
      this.checkBox11.AutoSize = true;
      this.checkBox11.Location = new Point(65, 15);
      this.checkBox11.Name = "checkBox11";
      this.checkBox11.Size = new Size(32, 17);
      this.checkBox11.TabIndex = 71;
      this.checkBox11.Text = "+";
      this.checkBox11.UseVisualStyleBackColor = true;
      this.checkBox12.AutoSize = true;
      this.checkBox12.Location = new Point(99, 15);
      this.checkBox12.Name = "checkBox12";
      this.checkBox12.Size = new Size(29, 17);
      this.checkBox12.TabIndex = 72;
      this.checkBox12.Text = "-";
      this.checkBox12.UseVisualStyleBackColor = true;
      this.groupBox7.Controls.Add((Control) this.checkBox21);
      this.groupBox7.Controls.Add((Control) this.checkBox22);
      this.groupBox7.Controls.Add((Control) this.checkBox23);
      this.groupBox7.Controls.Add((Control) this.checkBox24);
      this.groupBox7.Controls.Add((Control) this.checkBox25);
      this.groupBox7.Controls.Add((Control) this.checkBox26);
      this.groupBox7.Controls.Add((Control) this.button9);
      this.groupBox7.Controls.Add((Control) this.button10);
      this.groupBox7.Controls.Add((Control) this.button11);
      this.groupBox7.Controls.Add((Control) this.button26);
      this.groupBox7.Controls.Add((Control) this.button27);
      this.groupBox7.Controls.Add((Control) this.button28);
      this.groupBox7.Controls.Add((Control) this.label23);
      this.groupBox7.Controls.Add((Control) this.label24);
      this.groupBox7.Controls.Add((Control) this.label25);
      this.groupBox7.Controls.Add((Control) this.textBox8);
      this.groupBox7.Controls.Add((Control) this.textBox9);
      this.groupBox7.Controls.Add((Control) this.textBox10);
      this.groupBox7.Controls.Add((Control) this.label27);
      this.groupBox7.Controls.Add((Control) this.label28);
      this.groupBox7.Controls.Add((Control) this.label29);
      this.groupBox7.Location = new Point(7, 11);
      this.groupBox7.Name = "groupBox7";
      this.groupBox7.Size = new Size(120, 484);
      this.groupBox7.TabIndex = 2;
      this.groupBox7.TabStop = false;
      this.groupBox7.Text = "AffinityWork";
      this.checkBox21.AutoSize = true;
      this.checkBox21.Location = new Point(44, 252);
      this.checkBox21.Name = "checkBox21";
      this.checkBox21.Size = new Size(32, 17);
      this.checkBox21.TabIndex = 63;
      this.checkBox21.Text = "+";
      this.checkBox21.UseVisualStyleBackColor = true;
      this.checkBox22.AutoSize = true;
      this.checkBox22.Location = new Point(78, 252);
      this.checkBox22.Name = "checkBox22";
      this.checkBox22.Size = new Size(29, 17);
      this.checkBox22.TabIndex = 64;
      this.checkBox22.Text = "-";
      this.checkBox22.UseVisualStyleBackColor = true;
      this.checkBox23.AutoSize = true;
      this.checkBox23.Location = new Point(44, 133);
      this.checkBox23.Name = "checkBox23";
      this.checkBox23.Size = new Size(32, 17);
      this.checkBox23.TabIndex = 61;
      this.checkBox23.Text = "+";
      this.checkBox23.UseVisualStyleBackColor = true;
      this.checkBox24.AutoSize = true;
      this.checkBox24.Location = new Point(78, 133);
      this.checkBox24.Name = "checkBox24";
      this.checkBox24.Size = new Size(29, 17);
      this.checkBox24.TabIndex = 62;
      this.checkBox24.Text = "-";
      this.checkBox24.UseVisualStyleBackColor = true;
      this.checkBox25.AutoSize = true;
      this.checkBox25.Location = new Point(44, 19);
      this.checkBox25.Name = "checkBox25";
      this.checkBox25.Size = new Size(32, 17);
      this.checkBox25.TabIndex = 59;
      this.checkBox25.Text = "+";
      this.checkBox25.UseVisualStyleBackColor = true;
      this.checkBox26.AutoSize = true;
      this.checkBox26.Location = new Point(78, 19);
      this.checkBox26.Name = "checkBox26";
      this.checkBox26.Size = new Size(29, 17);
      this.checkBox26.TabIndex = 60;
      this.checkBox26.Text = "-";
      this.checkBox26.UseVisualStyleBackColor = true;
      this.button9.BackColor = Color.Aquamarine;
      this.button9.BackgroundImageLayout = ImageLayout.None;
      this.button9.FlatAppearance.BorderSize = 0;
      this.button9.FlatStyle = FlatStyle.Flat;
      this.button9.Location = new Point(6, 331);
      this.button9.Name = "button9";
      this.button9.Size = new Size(108, 27);
      this.button9.TabIndex = 56;
      this.button9.Text = "Export Query";
      this.button9.UseVisualStyleBackColor = false;
      this.button10.BackColor = SystemColors.ActiveCaption;
      this.button10.BackgroundImageLayout = ImageLayout.None;
      this.button10.FlatAppearance.BorderSize = 0;
      this.button10.FlatStyle = FlatStyle.Flat;
      this.button10.Location = new Point(6, 302);
      this.button10.Name = "button10";
      this.button10.Size = new Size(108, 27);
      this.button10.TabIndex = 55;
      this.button10.Text = "Send Query";
      this.button10.UseVisualStyleBackColor = false;
      this.button11.BackColor = Color.Aquamarine;
      this.button11.BackgroundImageLayout = ImageLayout.None;
      this.button11.FlatAppearance.BorderSize = 0;
      this.button11.FlatStyle = FlatStyle.Flat;
      this.button11.Location = new Point(6, 217);
      this.button11.Name = "button11";
      this.button11.Size = new Size(108, 27);
      this.button11.TabIndex = 54;
      this.button11.Text = "Export Query";
      this.button11.UseVisualStyleBackColor = false;
      this.button26.BackColor = SystemColors.ActiveCaption;
      this.button26.BackgroundImageLayout = ImageLayout.None;
      this.button26.FlatAppearance.BorderSize = 0;
      this.button26.FlatStyle = FlatStyle.Flat;
      this.button26.Location = new Point(6, 188);
      this.button26.Name = "button26";
      this.button26.Size = new Size(108, 27);
      this.button26.TabIndex = 53;
      this.button26.Text = "Send Query";
      this.button26.UseVisualStyleBackColor = false;
      this.button27.BackColor = Color.Aquamarine;
      this.button27.BackgroundImageLayout = ImageLayout.None;
      this.button27.FlatAppearance.BorderSize = 0;
      this.button27.FlatStyle = FlatStyle.Flat;
      this.button27.Location = new Point(2, 97);
      this.button27.Name = "button27";
      this.button27.Size = new Size(108, 27);
      this.button27.TabIndex = 52;
      this.button27.Text = "Export Query";
      this.button27.UseVisualStyleBackColor = false;
      this.button28.BackColor = SystemColors.ActiveCaption;
      this.button28.BackgroundImageLayout = ImageLayout.None;
      this.button28.FlatAppearance.BorderSize = 0;
      this.button28.FlatStyle = FlatStyle.Flat;
      this.button28.Location = new Point(2, 68);
      this.button28.Name = "button28";
      this.button28.Size = new Size(108, 27);
      this.button28.TabIndex = 51;
      this.button28.Text = "Send Query";
      this.button28.UseVisualStyleBackColor = false;
      this.button28.Click += new EventHandler(this.button28_Click);
      this.label23.AutoSize = true;
      this.label23.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label23.Location = new Point(101, 279);
      this.label23.Name = "label23";
      this.label23.Size = new Size(16, 13);
      this.label23.TabIndex = 50;
      this.label23.Text = "%";
      this.label24.AutoSize = true;
      this.label24.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label24.Location = new Point(101, 165);
      this.label24.Name = "label24";
      this.label24.Size = new Size(16, 13);
      this.label24.TabIndex = 49;
      this.label24.Text = "%";
      this.label25.AutoSize = true;
      this.label25.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label25.Location = new Point(101, 45);
      this.label25.Name = "label25";
      this.label25.Size = new Size(16, 13);
      this.label25.TabIndex = 48;
      this.label25.Text = "%";
      this.textBox8.Location = new Point(7, 276);
      this.textBox8.Name = "textBox8";
      this.textBox8.Size = new Size(94, 20);
      this.textBox8.TabIndex = 41;
      this.textBox9.Location = new Point(6, 162);
      this.textBox9.Name = "textBox9";
      this.textBox9.Size = new Size(94, 20);
      this.textBox9.TabIndex = 40;
      this.textBox10.Location = new Point(6, 42);
      this.textBox10.Name = "textBox10";
      this.textBox10.Size = new Size(94, 20);
      this.textBox10.TabIndex = 39;
      this.label27.AutoSize = true;
      this.label27.Location = new Point(6, 252);
      this.label27.Name = "label27";
      this.label27.Size = new Size(32, 13);
      this.label27.TabIndex = 2;
      this.label27.Text = "NPC:";
      this.label28.AutoSize = true;
      this.label28.Location = new Point(7, 133);
      this.label28.Name = "label28";
      this.label28.Size = new Size(30, 13);
      this.label28.TabIndex = 1;
      this.label28.Text = "Item:";
      this.label29.AutoSize = true;
      this.label29.Location = new Point(7, 19);
      this.label29.Name = "label29";
      this.label29.Size = new Size(38, 13);
      this.label29.TabIndex = 0;
      this.label29.Text = "Quest:";
      this.groupBox3.Controls.Add((Control) this.checkBox13);
      this.groupBox3.Controls.Add((Control) this.checkBox14);
      this.groupBox3.Controls.Add((Control) this.checkBox15);
      this.groupBox3.Controls.Add((Control) this.checkBox16);
      this.groupBox3.Controls.Add((Control) this.checkBox17);
      this.groupBox3.Controls.Add((Control) this.checkBox18);
      this.groupBox3.Controls.Add((Control) this.button1);
      this.groupBox3.Controls.Add((Control) this.button2);
      this.groupBox3.Controls.Add((Control) this.button3);
      this.groupBox3.Controls.Add((Control) this.button4);
      this.groupBox3.Controls.Add((Control) this.button5);
      this.groupBox3.Controls.Add((Control) this.button6);
      this.groupBox3.Controls.Add((Control) this.label15);
      this.groupBox3.Controls.Add((Control) this.label16);
      this.groupBox3.Controls.Add((Control) this.label17);
      this.groupBox3.Controls.Add((Control) this.textBox4);
      this.groupBox3.Controls.Add((Control) this.textBox5);
      this.groupBox3.Controls.Add((Control) this.textBox6);
      this.groupBox3.Controls.Add((Control) this.label18);
      this.groupBox3.Controls.Add((Control) this.label19);
      this.groupBox3.Controls.Add((Control) this.label20);
      this.groupBox3.Location = new Point(6, 17);
      this.groupBox3.Name = "groupBox3";
      this.groupBox3.Size = new Size(122, 363);
      this.groupBox3.TabIndex = 3;
      this.groupBox3.TabStop = false;
      this.groupBox3.Text = "AffinityWork";
      this.checkBox13.AutoSize = true;
      this.checkBox13.Location = new Point(44, 252);
      this.checkBox13.Name = "checkBox13";
      this.checkBox13.Size = new Size(32, 17);
      this.checkBox13.TabIndex = 63;
      this.checkBox13.Text = "+";
      this.checkBox13.UseVisualStyleBackColor = true;
      this.checkBox14.AutoSize = true;
      this.checkBox14.Location = new Point(78, 252);
      this.checkBox14.Name = "checkBox14";
      this.checkBox14.Size = new Size(29, 17);
      this.checkBox14.TabIndex = 64;
      this.checkBox14.Text = "-";
      this.checkBox14.UseVisualStyleBackColor = true;
      this.checkBox15.AutoSize = true;
      this.checkBox15.Location = new Point(44, 133);
      this.checkBox15.Name = "checkBox15";
      this.checkBox15.Size = new Size(32, 17);
      this.checkBox15.TabIndex = 61;
      this.checkBox15.Text = "+";
      this.checkBox15.UseVisualStyleBackColor = true;
      this.checkBox16.AutoSize = true;
      this.checkBox16.Location = new Point(78, 133);
      this.checkBox16.Name = "checkBox16";
      this.checkBox16.Size = new Size(29, 17);
      this.checkBox16.TabIndex = 62;
      this.checkBox16.Text = "-";
      this.checkBox16.UseVisualStyleBackColor = true;
      this.checkBox17.AutoSize = true;
      this.checkBox17.Location = new Point(44, 19);
      this.checkBox17.Name = "checkBox17";
      this.checkBox17.Size = new Size(32, 17);
      this.checkBox17.TabIndex = 59;
      this.checkBox17.Text = "+";
      this.checkBox17.UseVisualStyleBackColor = true;
      this.checkBox18.AutoSize = true;
      this.checkBox18.Location = new Point(78, 19);
      this.checkBox18.Name = "checkBox18";
      this.checkBox18.Size = new Size(29, 17);
      this.checkBox18.TabIndex = 60;
      this.checkBox18.Text = "-";
      this.checkBox18.UseVisualStyleBackColor = true;
      this.button1.BackColor = Color.Aquamarine;
      this.button1.BackgroundImageLayout = ImageLayout.None;
      this.button1.FlatAppearance.BorderSize = 0;
      this.button1.FlatStyle = FlatStyle.Flat;
      this.button1.Location = new Point(6, 331);
      this.button1.Name = "button1";
      this.button1.Size = new Size(108, 27);
      this.button1.TabIndex = 56;
      this.button1.Text = "Export Query";
      this.button1.UseVisualStyleBackColor = false;
      this.button2.BackColor = SystemColors.ActiveCaption;
      this.button2.BackgroundImageLayout = ImageLayout.None;
      this.button2.FlatAppearance.BorderSize = 0;
      this.button2.FlatStyle = FlatStyle.Flat;
      this.button2.Location = new Point(6, 302);
      this.button2.Name = "button2";
      this.button2.Size = new Size(108, 27);
      this.button2.TabIndex = 55;
      this.button2.Text = "Send Query";
      this.button2.UseVisualStyleBackColor = false;
      this.button3.BackColor = Color.Aquamarine;
      this.button3.BackgroundImageLayout = ImageLayout.None;
      this.button3.FlatAppearance.BorderSize = 0;
      this.button3.FlatStyle = FlatStyle.Flat;
      this.button3.Location = new Point(6, 217);
      this.button3.Name = "button3";
      this.button3.Size = new Size(108, 27);
      this.button3.TabIndex = 54;
      this.button3.Text = "Export Query";
      this.button3.UseVisualStyleBackColor = false;
      this.button4.BackColor = SystemColors.ActiveCaption;
      this.button4.BackgroundImageLayout = ImageLayout.None;
      this.button4.FlatAppearance.BorderSize = 0;
      this.button4.FlatStyle = FlatStyle.Flat;
      this.button4.Location = new Point(6, 188);
      this.button4.Name = "button4";
      this.button4.Size = new Size(108, 27);
      this.button4.TabIndex = 53;
      this.button4.Text = "Send Query";
      this.button4.UseVisualStyleBackColor = false;
      this.button5.BackColor = Color.Aquamarine;
      this.button5.BackgroundImageLayout = ImageLayout.None;
      this.button5.FlatAppearance.BorderSize = 0;
      this.button5.FlatStyle = FlatStyle.Flat;
      this.button5.Location = new Point(2, 97);
      this.button5.Name = "button5";
      this.button5.Size = new Size(108, 27);
      this.button5.TabIndex = 52;
      this.button5.Text = "Export Query";
      this.button5.UseVisualStyleBackColor = false;
      this.button6.BackColor = SystemColors.ActiveCaption;
      this.button6.BackgroundImageLayout = ImageLayout.None;
      this.button6.FlatAppearance.BorderSize = 0;
      this.button6.FlatStyle = FlatStyle.Flat;
      this.button6.Location = new Point(2, 68);
      this.button6.Name = "button6";
      this.button6.Size = new Size(108, 27);
      this.button6.TabIndex = 51;
      this.button6.Text = "Send Query";
      this.button6.UseVisualStyleBackColor = false;
      this.label15.AutoSize = true;
      this.label15.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label15.Location = new Point(101, 279);
      this.label15.Name = "label15";
      this.label15.Size = new Size(16, 13);
      this.label15.TabIndex = 50;
      this.label15.Text = "%";
      this.label16.AutoSize = true;
      this.label16.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label16.Location = new Point(101, 165);
      this.label16.Name = "label16";
      this.label16.Size = new Size(16, 13);
      this.label16.TabIndex = 49;
      this.label16.Text = "%";
      this.label17.AutoSize = true;
      this.label17.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label17.Location = new Point(101, 45);
      this.label17.Name = "label17";
      this.label17.Size = new Size(16, 13);
      this.label17.TabIndex = 48;
      this.label17.Text = "%";
      this.textBox4.Location = new Point(7, 276);
      this.textBox4.Name = "textBox4";
      this.textBox4.Size = new Size(94, 20);
      this.textBox4.TabIndex = 41;
      this.textBox5.Location = new Point(6, 162);
      this.textBox5.Name = "textBox5";
      this.textBox5.Size = new Size(94, 20);
      this.textBox5.TabIndex = 40;
      this.textBox6.Location = new Point(6, 42);
      this.textBox6.Name = "textBox6";
      this.textBox6.Size = new Size(94, 20);
      this.textBox6.TabIndex = 39;
      this.label18.AutoSize = true;
      this.label18.Location = new Point(6, 252);
      this.label18.Name = "label18";
      this.label18.Size = new Size(32, 13);
      this.label18.TabIndex = 2;
      this.label18.Text = "NPC:";
      this.label19.AutoSize = true;
      this.label19.Location = new Point(7, 133);
      this.label19.Name = "label19";
      this.label19.Size = new Size(30, 13);
      this.label19.TabIndex = 1;
      this.label19.Text = "Item:";
      this.label20.AutoSize = true;
      this.label20.Location = new Point(7, 19);
      this.label20.Name = "label20";
      this.label20.Size = new Size(38, 13);
      this.label20.TabIndex = 0;
      this.label20.Text = "Quest:";
      this.groupBox4.Controls.Add((Control) this.checkBox19);
      this.groupBox4.Controls.Add((Control) this.checkBox20);
      this.groupBox4.Controls.Add((Control) this.checkBox27);
      this.groupBox4.Controls.Add((Control) this.checkBox28);
      this.groupBox4.Controls.Add((Control) this.checkBox29);
      this.groupBox4.Controls.Add((Control) this.checkBox30);
      this.groupBox4.Controls.Add((Control) this.button7);
      this.groupBox4.Controls.Add((Control) this.button8);
      this.groupBox4.Controls.Add((Control) this.button29);
      this.groupBox4.Controls.Add((Control) this.button30);
      this.groupBox4.Controls.Add((Control) this.button31);
      this.groupBox4.Controls.Add((Control) this.button32);
      this.groupBox4.Controls.Add((Control) this.label21);
      this.groupBox4.Controls.Add((Control) this.label22);
      this.groupBox4.Controls.Add((Control) this.label26);
      this.groupBox4.Controls.Add((Control) this.textBox7);
      this.groupBox4.Controls.Add((Control) this.textBox11);
      this.groupBox4.Controls.Add((Control) this.textBox12);
      this.groupBox4.Controls.Add((Control) this.label30);
      this.groupBox4.Controls.Add((Control) this.label31);
      this.groupBox4.Controls.Add((Control) this.label32);
      this.groupBox4.Location = new Point(149, 17);
      this.groupBox4.Name = "groupBox4";
      this.groupBox4.Size = new Size(122, 363);
      this.groupBox4.TabIndex = 65;
      this.groupBox4.TabStop = false;
      this.groupBox4.Text = "AffinityWork";
      this.checkBox19.AutoSize = true;
      this.checkBox19.Location = new Point(44, 252);
      this.checkBox19.Name = "checkBox19";
      this.checkBox19.Size = new Size(32, 17);
      this.checkBox19.TabIndex = 63;
      this.checkBox19.Text = "+";
      this.checkBox19.UseVisualStyleBackColor = true;
      this.checkBox20.AutoSize = true;
      this.checkBox20.Location = new Point(78, 252);
      this.checkBox20.Name = "checkBox20";
      this.checkBox20.Size = new Size(29, 17);
      this.checkBox20.TabIndex = 64;
      this.checkBox20.Text = "-";
      this.checkBox20.UseVisualStyleBackColor = true;
      this.checkBox27.AutoSize = true;
      this.checkBox27.Location = new Point(44, 133);
      this.checkBox27.Name = "checkBox27";
      this.checkBox27.Size = new Size(32, 17);
      this.checkBox27.TabIndex = 61;
      this.checkBox27.Text = "+";
      this.checkBox27.UseVisualStyleBackColor = true;
      this.checkBox28.AutoSize = true;
      this.checkBox28.Location = new Point(78, 133);
      this.checkBox28.Name = "checkBox28";
      this.checkBox28.Size = new Size(29, 17);
      this.checkBox28.TabIndex = 62;
      this.checkBox28.Text = "-";
      this.checkBox28.UseVisualStyleBackColor = true;
      this.checkBox29.AutoSize = true;
      this.checkBox29.Location = new Point(44, 19);
      this.checkBox29.Name = "checkBox29";
      this.checkBox29.Size = new Size(32, 17);
      this.checkBox29.TabIndex = 59;
      this.checkBox29.Text = "+";
      this.checkBox29.UseVisualStyleBackColor = true;
      this.checkBox30.AutoSize = true;
      this.checkBox30.Location = new Point(78, 19);
      this.checkBox30.Name = "checkBox30";
      this.checkBox30.Size = new Size(29, 17);
      this.checkBox30.TabIndex = 60;
      this.checkBox30.Text = "-";
      this.checkBox30.UseVisualStyleBackColor = true;
      this.button7.BackColor = Color.Aquamarine;
      this.button7.BackgroundImageLayout = ImageLayout.None;
      this.button7.FlatAppearance.BorderSize = 0;
      this.button7.FlatStyle = FlatStyle.Flat;
      this.button7.Location = new Point(6, 331);
      this.button7.Name = "button7";
      this.button7.Size = new Size(108, 27);
      this.button7.TabIndex = 56;
      this.button7.Text = "Export Query";
      this.button7.UseVisualStyleBackColor = false;
      this.button8.BackColor = SystemColors.ActiveCaption;
      this.button8.BackgroundImageLayout = ImageLayout.None;
      this.button8.FlatAppearance.BorderSize = 0;
      this.button8.FlatStyle = FlatStyle.Flat;
      this.button8.Location = new Point(6, 302);
      this.button8.Name = "button8";
      this.button8.Size = new Size(108, 27);
      this.button8.TabIndex = 55;
      this.button8.Text = "Send Query";
      this.button8.UseVisualStyleBackColor = false;
      this.button29.BackColor = Color.Aquamarine;
      this.button29.BackgroundImageLayout = ImageLayout.None;
      this.button29.FlatAppearance.BorderSize = 0;
      this.button29.FlatStyle = FlatStyle.Flat;
      this.button29.Location = new Point(6, 217);
      this.button29.Name = "button29";
      this.button29.Size = new Size(108, 27);
      this.button29.TabIndex = 54;
      this.button29.Text = "Export Query";
      this.button29.UseVisualStyleBackColor = false;
      this.button30.BackColor = SystemColors.ActiveCaption;
      this.button30.BackgroundImageLayout = ImageLayout.None;
      this.button30.FlatAppearance.BorderSize = 0;
      this.button30.FlatStyle = FlatStyle.Flat;
      this.button30.Location = new Point(6, 188);
      this.button30.Name = "button30";
      this.button30.Size = new Size(108, 27);
      this.button30.TabIndex = 53;
      this.button30.Text = "Send Query";
      this.button30.UseVisualStyleBackColor = false;
      this.button31.BackColor = Color.Aquamarine;
      this.button31.BackgroundImageLayout = ImageLayout.None;
      this.button31.FlatAppearance.BorderSize = 0;
      this.button31.FlatStyle = FlatStyle.Flat;
      this.button31.Location = new Point(2, 97);
      this.button31.Name = "button31";
      this.button31.Size = new Size(108, 27);
      this.button31.TabIndex = 52;
      this.button31.Text = "Export Query";
      this.button31.UseVisualStyleBackColor = false;
      this.button32.BackColor = SystemColors.ActiveCaption;
      this.button32.BackgroundImageLayout = ImageLayout.None;
      this.button32.FlatAppearance.BorderSize = 0;
      this.button32.FlatStyle = FlatStyle.Flat;
      this.button32.Location = new Point(2, 68);
      this.button32.Name = "button32";
      this.button32.Size = new Size(108, 27);
      this.button32.TabIndex = 51;
      this.button32.Text = "Send Query";
      this.button32.UseVisualStyleBackColor = false;
      this.label21.AutoSize = true;
      this.label21.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label21.Location = new Point(101, 279);
      this.label21.Name = "label21";
      this.label21.Size = new Size(16, 13);
      this.label21.TabIndex = 50;
      this.label21.Text = "%";
      this.label22.AutoSize = true;
      this.label22.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label22.Location = new Point(101, 165);
      this.label22.Name = "label22";
      this.label22.Size = new Size(16, 13);
      this.label22.TabIndex = 49;
      this.label22.Text = "%";
      this.label26.AutoSize = true;
      this.label26.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label26.Location = new Point(101, 45);
      this.label26.Name = "label26";
      this.label26.Size = new Size(16, 13);
      this.label26.TabIndex = 48;
      this.label26.Text = "%";
      this.textBox7.Location = new Point(7, 276);
      this.textBox7.Name = "textBox7";
      this.textBox7.Size = new Size(94, 20);
      this.textBox7.TabIndex = 41;
      this.textBox11.Location = new Point(6, 162);
      this.textBox11.Name = "textBox11";
      this.textBox11.Size = new Size(94, 20);
      this.textBox11.TabIndex = 40;
      this.textBox12.Location = new Point(6, 42);
      this.textBox12.Name = "textBox12";
      this.textBox12.Size = new Size(94, 20);
      this.textBox12.TabIndex = 39;
      this.label30.AutoSize = true;
      this.label30.Location = new Point(6, 252);
      this.label30.Name = "label30";
      this.label30.Size = new Size(32, 13);
      this.label30.TabIndex = 2;
      this.label30.Text = "NPC:";
      this.label31.AutoSize = true;
      this.label31.Location = new Point(7, 133);
      this.label31.Name = "label31";
      this.label31.Size = new Size(30, 13);
      this.label31.TabIndex = 1;
      this.label31.Text = "Item:";
      this.label32.AutoSize = true;
      this.label32.Location = new Point(7, 19);
      this.label32.Name = "label32";
      this.label32.Size = new Size(38, 13);
      this.label32.TabIndex = 0;
      this.label32.Text = "Quest:";
      this.groupBox5.Controls.Add((Control) this.checkBox33);
      this.groupBox5.Controls.Add((Control) this.checkBox34);
      this.groupBox5.Controls.Add((Control) this.button35);
      this.groupBox5.Controls.Add((Control) this.button36);
      this.groupBox5.Controls.Add((Control) this.label35);
      this.groupBox5.Controls.Add((Control) this.textBox14);
      this.groupBox5.Controls.Add((Control) this.label36);
      this.groupBox5.Controls.Add((Control) this.checkBox31);
      this.groupBox5.Controls.Add((Control) this.checkBox32);
      this.groupBox5.Controls.Add((Control) this.button33);
      this.groupBox5.Controls.Add((Control) this.button34);
      this.groupBox5.Controls.Add((Control) this.label33);
      this.groupBox5.Controls.Add((Control) this.textBox13);
      this.groupBox5.Controls.Add((Control) this.label34);
      this.groupBox5.Location = new Point(16, 380);
      this.groupBox5.Name = "groupBox5";
      this.groupBox5.Size = new Size((int) byte.MaxValue, (int) sbyte.MaxValue);
      this.groupBox5.TabIndex = 65;
      this.groupBox5.TabStop = false;
      this.groupBox5.Text = "groupBox5";
      this.checkBox31.AutoSize = true;
      this.checkBox31.Location = new Point(44, 16);
      this.checkBox31.Name = "checkBox31";
      this.checkBox31.Size = new Size(32, 17);
      this.checkBox31.TabIndex = 70;
      this.checkBox31.Text = "+";
      this.checkBox31.UseVisualStyleBackColor = true;
      this.checkBox32.AutoSize = true;
      this.checkBox32.Location = new Point(78, 16);
      this.checkBox32.Name = "checkBox32";
      this.checkBox32.Size = new Size(29, 17);
      this.checkBox32.TabIndex = 71;
      this.checkBox32.Text = "-";
      this.checkBox32.UseVisualStyleBackColor = true;
      this.button33.BackColor = Color.Aquamarine;
      this.button33.BackgroundImageLayout = ImageLayout.None;
      this.button33.FlatAppearance.BorderSize = 0;
      this.button33.FlatStyle = FlatStyle.Flat;
      this.button33.Location = new Point(6, 95);
      this.button33.Name = "button33";
      this.button33.Size = new Size(108, 27);
      this.button33.TabIndex = 69;
      this.button33.Text = "Export Query";
      this.button33.UseVisualStyleBackColor = false;
      this.button34.BackColor = SystemColors.ActiveCaption;
      this.button34.BackgroundImageLayout = ImageLayout.None;
      this.button34.FlatAppearance.BorderSize = 0;
      this.button34.FlatStyle = FlatStyle.Flat;
      this.button34.Location = new Point(6, 66);
      this.button34.Name = "button34";
      this.button34.Size = new Size(108, 27);
      this.button34.TabIndex = 68;
      this.button34.Text = "Send Query";
      this.button34.UseVisualStyleBackColor = false;
      this.label33.AutoSize = true;
      this.label33.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label33.Location = new Point(101, 43);
      this.label33.Name = "label33";
      this.label33.Size = new Size(16, 13);
      this.label33.TabIndex = 67;
      this.label33.Text = "%";
      this.textBox13.Location = new Point(7, 40);
      this.textBox13.Name = "textBox13";
      this.textBox13.Size = new Size(94, 20);
      this.textBox13.TabIndex = 66;
      this.label34.AutoSize = true;
      this.label34.Location = new Point(6, 16);
      this.label34.Name = "label34";
      this.label34.Size = new Size(32, 13);
      this.label34.TabIndex = 65;
      this.label34.Text = "NPC:";
      this.checkBox33.AutoSize = true;
      this.checkBox33.Location = new Point(174, 17);
      this.checkBox33.Name = "checkBox33";
      this.checkBox33.Size = new Size(32, 17);
      this.checkBox33.TabIndex = 77;
      this.checkBox33.Text = "+";
      this.checkBox33.UseVisualStyleBackColor = true;
      this.checkBox34.AutoSize = true;
      this.checkBox34.Location = new Point(208, 17);
      this.checkBox34.Name = "checkBox34";
      this.checkBox34.Size = new Size(29, 17);
      this.checkBox34.TabIndex = 78;
      this.checkBox34.Text = "-";
      this.checkBox34.UseVisualStyleBackColor = true;
      this.button35.BackColor = Color.Aquamarine;
      this.button35.BackgroundImageLayout = ImageLayout.None;
      this.button35.FlatAppearance.BorderSize = 0;
      this.button35.FlatStyle = FlatStyle.Flat;
      this.button35.Location = new Point(136, 96);
      this.button35.Name = "button35";
      this.button35.Size = new Size(108, 27);
      this.button35.TabIndex = 76;
      this.button35.Text = "Export Query";
      this.button35.UseVisualStyleBackColor = false;
      this.button36.BackColor = SystemColors.ActiveCaption;
      this.button36.BackgroundImageLayout = ImageLayout.None;
      this.button36.FlatAppearance.BorderSize = 0;
      this.button36.FlatStyle = FlatStyle.Flat;
      this.button36.Location = new Point(136, 67);
      this.button36.Name = "button36";
      this.button36.Size = new Size(108, 27);
      this.button36.TabIndex = 75;
      this.button36.Text = "Send Query";
      this.button36.UseVisualStyleBackColor = false;
      this.label35.AutoSize = true;
      this.label35.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label35.Location = new Point(231, 44);
      this.label35.Name = "label35";
      this.label35.Size = new Size(16, 13);
      this.label35.TabIndex = 74;
      this.label35.Text = "%";
      this.textBox14.Location = new Point(137, 41);
      this.textBox14.Name = "textBox14";
      this.textBox14.Size = new Size(94, 20);
      this.textBox14.TabIndex = 73;
      this.label36.AutoSize = true;
      this.label36.Location = new Point(136, 17);
      this.label36.Name = "label36";
      this.label36.Size = new Size(32, 13);
      this.label36.TabIndex = 72;
      this.label36.Text = "NPC:";
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(308, 557);
      this.Controls.Add((Control) this.tbRates);
      this.Name = nameof (RatesEditor);
      this.Text = nameof (RatesEditor);
      this.Load += new EventHandler(this.RatesEditor_Load);
      this.tbRates.ResumeLayout(false);
      this.tbSkill.ResumeLayout(false);
      this.tbAffinity.ResumeLayout(false);
      this.tbNPC.ResumeLayout(false);
      this.gbInfo.ResumeLayout(false);
      this.groupBox1.ResumeLayout(false);
      this.groupBox1.PerformLayout();
      this.gbAtribute.ResumeLayout(false);
      this.gbAtribute.PerformLayout();
      this.gbRate.ResumeLayout(false);
      this.gbRate.PerformLayout();
      this.gbJewelProb.ResumeLayout(false);
      this.gbJewelProb.PerformLayout();
      this.groupBox2.ResumeLayout(false);
      this.groupBox2.PerformLayout();
      this.groupBox7.ResumeLayout(false);
      this.groupBox7.PerformLayout();
      this.groupBox3.ResumeLayout(false);
      this.groupBox3.PerformLayout();
      this.groupBox4.ResumeLayout(false);
      this.groupBox4.PerformLayout();
      this.groupBox5.ResumeLayout(false);
      this.groupBox5.PerformLayout();
      this.ResumeLayout(false);
    }
  }
}
